version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'esbuild'
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - 'zone.js'
          - 'rxjs'
          - 'tslib'
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - '@eslint/*'
          - 'typescript-eslint'
      testing:
        patterns:
          - 'vitest'
          - '@playwright/*'
          - 'playwright'
  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'uuid'
      - dependency-name: 'esbuild'
  - package-ecosystem: 'bundler'
    directory: '/apps/mobile/android'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
