/**
 * @fileoverview Storage constants for Firebase Storage integration
 * @version 1.1.0
 *
 * Defines paths, thumbnail sizes, and configuration for the
 * Firebase Resize Images extension.
 *
 * Extension Configuration (must match Firebase Console exactly):
 * - Cloud Storage bucket: nxt-1-staging.appspot.com
 * - Trigger path: users slash star slash profile
 * - Sizes: 200x200, 400x400, 800x800
 * - Formats: jpeg, webp, png
 * - Output path: same directory as original
 * - Thumbnail naming: filename underscore widthxheight dot format
 * - Cache-Control: 1 year public
 * - Delete original: false
 * - Make public: false
 */

// ============================================
// STORAGE PATHS
// ============================================

/**
 * Storage path templates for different file types.
 * Use these to ensure consistency and extension compatibility.
 */
export const STORAGE_PATHS = {
  /** Profile photos */
  PROFILE_PHOTO: 'Profiles/ProfileImages/{userId}',
  /** Team logos */
  TEAM_LOGO: 'teams/{teamId}/logo',
  /** Team banners */
  TEAM_BANNER: 'teams/{teamId}/banner',
  /** Documents (PDFs, etc.) */
  DOCUMENTS: 'Users/{userId}/documents',
  /** Video thumbnails */
  VIDEO_THUMBNAILS: 'Users/{userId}/video-thumbnails',
  /** Temporary uploads */
  TEMP: 'temp/{userId}',
} as const;

// ============================================
// THUMBNAIL CONFIGURATION
// ============================================

/**
 * Thumbnail sizes generated by Firebase Resize Images extension.
 * Must match extension configuration in Firebase console.
 */
export const THUMBNAIL_SIZES = {
  /** Small thumbnail - avatars, list items */
  SMALL: { width: 200, height: 200, suffix: '200x200' },
  /** Medium thumbnail - profile cards, preview */
  MEDIUM: { width: 400, height: 400, suffix: '400x400' },
  /** Large thumbnail - detailed view, high-res preview */
  LARGE: { width: 800, height: 800, suffix: '800x800' },
} as const;

/**
 * Directory where extension places generated thumbnails.
 * Empty string = same directory as original (current extension config).
 * If you configure a custom path in the extension, update this value.
 */
export const THUMBNAIL_DIR = '';

/**
 * Supported image formats for thumbnails.
 * Extension generates ALL formats for each size.
 * Order matches extension config: jpeg, webp, png
 */
export const IMAGE_FORMATS = {
  /** JPEG - universal compatibility, good compression */
  JPEG: 'jpg',
  /** WebP - best compression, modern browsers */
  WEBP: 'webp',
  /** PNG - lossless, supports transparency */
  PNG: 'png',
} as const;

// ============================================
// FILE VALIDATION
// ============================================

/**
 * Maximum file sizes per category (in bytes)
 */
export const MAX_FILE_SIZES = {
  /** Profile photo - 5MB */
  PROFILE_PHOTO: 5 * 1024 * 1024,
  /** Cover photo - 10MB */
  COVER_PHOTO: 10 * 1024 * 1024,
  /** Team logo - 2MB */
  TEAM_LOGO: 2 * 1024 * 1024,
  /** Document - 25MB */
  DOCUMENT: 25 * 1024 * 1024,
} as const;

/**
 * Allowed MIME types for image uploads
 */
export const ALLOWED_IMAGE_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
  'image/heic',
  'image/heif',
] as const;

/**
 * Allowed MIME types for documents
 */
export const ALLOWED_DOCUMENT_TYPES = [
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
] as const;

// ============================================
// CACHE CONTROL
// ============================================

/**
 * Cache control headers for different file types
 */
export const STORAGE_CACHE_CONTROL = {
  /** Profile images - cache for 1 week, allow revalidation */
  PROFILE: 'public, max-age=604800, stale-while-revalidate=86400',
  /** Cover images - cache for 1 week */
  COVER: 'public, max-age=604800',
  /** Thumbnails - cache for 1 year (immutable by name) */
  THUMBNAIL: 'public, max-age=31536000, immutable',
  /** Documents - cache for 1 day */
  DOCUMENT: 'private, max-age=86400',
} as const;

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Build a storage path from a template.
 *
 * @param template - Path template from STORAGE_PATHS
 * @param params - Parameters to substitute
 * @returns Resolved storage path
 *
 * @example
 * buildPath(STORAGE_PATHS.PROFILE_PHOTO, { userId: 'abc123' })
 * // Returns: 'users/abc123/profile'
 */
export function buildPath(template: string, params: Record<string, string>): string {
  return Object.entries(params).reduce(
    (path, [key, value]) => path.replace(`{${key}}`, value),
    template
  );
}

/**
 * Get thumbnail path for an original image.
 * Extension places thumbnails in SAME directory with size suffix.
 *
 * @param originalPath - Path to original image
 * @param size - Thumbnail size key
 * @param format - Image format
 * @returns Path to thumbnail
 *
 * @example
 * getThumbnailPath('users/123/profile/avatar_1234567890.jpg', 'SMALL', 'WEBP')
 * // Returns: 'users/123/profile/avatar_1234567890_200x200.webp'
 */
export function getThumbnailPath(
  originalPath: string,
  size: keyof typeof THUMBNAIL_SIZES,
  format: keyof typeof IMAGE_FORMATS = 'WEBP'
): string {
  const dir = originalPath.substring(0, originalPath.lastIndexOf('/'));
  const fileName = originalPath.substring(originalPath.lastIndexOf('/') + 1);
  const baseName = fileName.substring(0, fileName.lastIndexOf('.'));

  const sizeConfig = THUMBNAIL_SIZES[size];
  const ext = IMAGE_FORMATS[format];

  // Extension places thumbnails in same directory (no subdirectory)
  // Format: {baseName}_{width}x{height}.{format}
  return `${dir}/${baseName}_${sizeConfig.suffix}.${ext}`;
}

/**
 * Get all thumbnail paths for an original image.
 * Extension generates 3 formats × 3 sizes = 9 thumbnails total.
 *
 * @param originalPath - Path to original image
 * @returns Object with paths for all sizes/formats
 */
export function getAllThumbnailPaths(originalPath: string): {
  small: { jpg: string; webp: string; png: string };
  medium: { jpg: string; webp: string; png: string };
  large: { jpg: string; webp: string; png: string };
} {
  return {
    small: {
      jpg: getThumbnailPath(originalPath, 'SMALL', 'JPEG'),
      webp: getThumbnailPath(originalPath, 'SMALL', 'WEBP'),
      png: getThumbnailPath(originalPath, 'SMALL', 'PNG'),
    },
    medium: {
      jpg: getThumbnailPath(originalPath, 'MEDIUM', 'JPEG'),
      webp: getThumbnailPath(originalPath, 'MEDIUM', 'WEBP'),
      png: getThumbnailPath(originalPath, 'MEDIUM', 'PNG'),
    },
    large: {
      jpg: getThumbnailPath(originalPath, 'LARGE', 'JPEG'),
      webp: getThumbnailPath(originalPath, 'LARGE', 'WEBP'),
      png: getThumbnailPath(originalPath, 'LARGE', 'PNG'),
    },
  };
}

/**
 * Check if a path is monitored by the resize extension.
 *
 * @param path - Storage path to check
 * @returns True if extension will process uploads to this path
 */
export function isExtensionMonitoredPath(path: string): boolean {
  // Extension is configured to monitor: /users/*/profile
  return /^users\/[^/]+\/profile/.test(path);
}

/**
 * Validate image file for upload.
 *
 * @param mimeType - File MIME type
 * @param size - File size in bytes
 * @param category - Upload category
 * @returns Validation result
 */
export function validateImageUpload(
  mimeType: string,
  size: number,
  category: 'PROFILE_PHOTO' | 'COVER_PHOTO' | 'TEAM_LOGO'
): { valid: boolean; error?: string } {
  if (!ALLOWED_IMAGE_TYPES.includes(mimeType as (typeof ALLOWED_IMAGE_TYPES)[number])) {
    return {
      valid: false,
      error: `Invalid file type. Allowed: ${ALLOWED_IMAGE_TYPES.join(', ')}`,
    };
  }

  const maxSize = MAX_FILE_SIZES[category];
  if (size > maxSize) {
    const maxMB = maxSize / (1024 * 1024);
    return {
      valid: false,
      error: `File too large. Maximum: ${maxMB}MB`,
    };
  }

  return { valid: true };
}
