#!/usr/bin/env node
/**
 * @fileoverview NXT1 Design Token Build System
 * @module @nxt1/design-tokens
 *
 * Professional design token pipeline following industry best practices.
 * Similar to Style Dictionary, Figma Tokens, or Amazon Style Dictionary.
 *
 * Flow:
 *   tokens.json/ (DTCG source) → build.mjs → dist/ (generated outputs)
 *
 * Outputs:
 *   - dist/css/tokens.css      (CSS custom properties)
 *   - dist/css/themes/dark.css (Dark theme)
 *   - dist/css/themes/light.css (Light theme)
 *   - dist/scss/_tokens.scss   (SCSS variables)
 *   - dist/js/tokens.mjs       (ES Module)
 *   - dist/js/tokens.d.ts      (TypeScript definitions)
 *   - dist/json/resolved.json  (Resolved JSON for tools)
 *
 * Usage:
 *   npm run build
 *   node build.mjs
 *   node build.mjs --watch
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST_DIR = join(__dirname, 'dist');

// ============================================
// TOKEN FILE LOADING
// ============================================

function loadTokens() {
  const primitiveTokens = JSON.parse(
    readFileSync(join(__dirname, 'tokens.json/primitive.tokens.json'), 'utf-8')
  );
  const semanticTokens = JSON.parse(
    readFileSync(join(__dirname, 'tokens.json/semantic.tokens.json'), 'utf-8')
  );
  const componentTokens = JSON.parse(
    readFileSync(join(__dirname, 'tokens.json/component.tokens.json'), 'utf-8')
  );

  return { primitiveTokens, semanticTokens, componentTokens };
}

// ============================================
// TOKEN REFERENCE RESOLUTION
// ============================================

/**
 * Resolve token references like {color.brand.volt.400}
 */
function resolveReference(value, allTokens) {
  if (typeof value !== 'string') return value;

  const refPattern = /\{([^}]+)\}/g;

  return value.replace(refPattern, (match, path) => {
    const resolved = getValueByPath(allTokens, path);
    if (resolved !== undefined) {
      // Recursively resolve nested references
      return resolveReference(resolved, allTokens);
    }
    console.warn(`⚠️  Unresolved reference: ${match}`);
    return match;
  });
}

function getValueByPath(obj, path) {
  const parts = path.split('.');
  let current = obj;

  for (const part of parts) {
    if (current && typeof current === 'object') {
      // Check for $value at current level
      if (current[part] !== undefined) {
        current = current[part];
      } else {
        return undefined;
      }
    } else {
      return undefined;
    }
  }

  // Return $value if it exists, otherwise the object itself
  return current?.$value ?? current;
}

// ============================================
// CSS GENERATION
// ============================================

/**
 * Sanitize a token key for CSS custom property names
 * CSS vars shouldn't have dots (causes parsing issues in some tools)
 * @param {string} key - The token key (e.g., "spacing-0.5")
 * @returns {string} - Sanitized key (e.g., "spacing-0_5")
 */
function sanitizeCssKey(key) {
  return key.replace(/\./g, '_');
}

function toCssVarName(path) {
  return `--nxt1-${path.join('-').replace(/\./g, '_')}`;
}

function flattenTokens(obj, path = [], result = {}) {
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue; // Skip metadata

    const newPath = [...path, key];

    if (value && typeof value === 'object' && value.$value !== undefined) {
      // This is a token
      result[newPath.join('-')] = {
        value: value.$value,
        type: value.$type,
        description: value.$description,
        path: newPath,
      };
    } else if (value && typeof value === 'object') {
      // Nested group
      flattenTokens(value, newPath, result);
    }
  }

  return result;
}

function generateCssTokens(primitiveTokens, allTokens) {
  const flattened = flattenTokens(primitiveTokens);
  const lines = [
    '/**',
    ' * @fileoverview NXT1 Design Tokens - CSS Custom Properties',
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' * @source tokens.json/',
    ' */',
    '',
    ':root {',
  ];

  for (const [key, token] of Object.entries(flattened)) {
    const cssKey = sanitizeCssKey(key);
    const cssVar = `--nxt1-${cssKey}`;
    const resolved = resolveReference(token.value, allTokens);

    if (token.description) {
      lines.push(`  /* ${token.description} */`);
    }
    lines.push(`  ${cssVar}: ${resolved};`);
  }

  lines.push('}');
  return lines.join('\n');
}

function generateThemeCss(themeTokens, themeName, allTokens) {
  const flattened = flattenTokens(themeTokens);

  // Dynamic selector based on theme name
  let selector;
  let colorScheme;
  const isSportOrTeamTheme = themeName !== 'dark' && themeName !== 'light';

  if (themeName === 'dark') {
    selector = ':root,\n[data-theme="dark"],\n.dark-theme';
    colorScheme = 'dark';
  } else if (themeName === 'light') {
    selector = '[data-theme="light"],\n.light-theme';
    colorScheme = 'light';
  } else {
    // Custom themes (sport-football, sport-basketball, etc.)
    selector = `[data-theme="${themeName}"],\n.${themeName}-theme`;
    // Determine color scheme from background - dark backgrounds = dark scheme
    const bgPrimary = themeTokens.color?.background?.primary?.$value;
    colorScheme = bgPrimary && bgPrimary.match(/#[0-3]/) ? 'dark' : 'light';
  }

  // Format theme name for display (e.g., "sport-football" → "Sport Football")
  const displayName = themeName
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');

  const lines = [
    '/**',
    ` * @fileoverview NXT1 ${displayName} Theme`,
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' */',
    '',
    `${selector} {`,
    `  color-scheme: ${colorScheme};`,
    '',
  ];

  for (const [key, token] of Object.entries(flattened)) {
    // Convert semantic paths like "background-primary" to "bg-primary"
    let cssKey = sanitizeCssKey(
      key
        .replace(/^color-background-/, 'color-bg-')
        .replace(/^color-text-on/, 'color-text-on-')
        .replace(/^color-feedback-/, 'color-')
    );

    const cssVar = `--nxt1-${cssKey}`;
    const resolved = resolveReference(token.value, allTokens);
    lines.push(`  ${cssVar}: ${resolved};`);
  }

  // ============================================
  // AUTO-GENERATE COMPONENT TOKENS
  // All themes get navigation and glass tokens based on their surface color
  // ============================================
  const primaryColor = flattened['color-primary']?.value;
  const surfaceColor = flattened['color-surface-100']?.value;

  // Get the surface RGB for navigation tokens
  const resolvedSurface = surfaceColor
    ? resolveReference(surfaceColor, allTokens)
    : themeName === 'light'
      ? '#ffffff'
      : '#161616';
  const surfaceRgb =
    hexToRgb(resolvedSurface) ||
    (themeName === 'light' ? { r: 255, g: 255, b: 255 } : { r: 22, g: 22, b: 22 });

  // Navigation solid background tokens (fully opaque for non-glass mode)
  // These are generated for ALL themes so the footer/header work correctly
  lines.push('');
  lines.push('  /* Navigation solid background tokens (from design tokens) */');
  lines.push(`  --nxt1-nav-bgSolid: rgb(${surfaceRgb.r}, ${surfaceRgb.g}, ${surfaceRgb.b});`);
  if (themeName === 'light') {
    lines.push('  --nxt1-nav-borderSolid: rgba(0, 0, 0, 0.12);');
    lines.push(
      '  --nxt1-nav-shadowSolid: 0 1px 3px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.04);'
    );
  } else {
    lines.push('  --nxt1-nav-borderSolid: rgba(255, 255, 255, 0.12);');
    lines.push(
      '  --nxt1-nav-shadowSolid: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.08);'
    );
  }

  // Sport/Team themes get additional component tokens with primary color variations
  if (isSportOrTeamTheme) {
    if (primaryColor) {
      const resolvedPrimary = resolveReference(primaryColor, allTokens);
      const primaryRgb = hexToRgb(resolvedPrimary);

      if (primaryRgb) {
        const { r, g, b } = primaryRgb;

        lines.push('');
        lines.push('  /* Auto-generated component tokens (based on primary color) */');

        // Glass tokens (use the already-computed surfaceRgb)
        lines.push(
          `  --nxt1-glass-bg: rgba(${surfaceRgb.r}, ${surfaceRgb.g}, ${surfaceRgb.b}, 0.88);`
        );
        lines.push(
          `  --nxt1-glass-bgSolid: rgba(${surfaceRgb.r}, ${surfaceRgb.g}, ${surfaceRgb.b}, 0.95);`
        );
        lines.push('  --nxt1-glass-border: rgba(255, 255, 255, 0.12);');
        lines.push('  --nxt1-glass-borderSubtle: rgba(255, 255, 255, 0.08);');
        lines.push(
          '  --nxt1-glass-shadow: 0 8px 32px rgba(0, 0, 0, 0.45), 0 2px 8px rgba(0, 0, 0, 0.25);'
        );
        lines.push('  --nxt1-glass-shadowInner: inset 0 1px 0 rgba(255, 255, 255, 0.06);');
        lines.push('  --nxt1-glass-backdrop: saturate(180%) blur(20px);');
        lines.push('  --nxt1-glass-backdropStrong: saturate(200%) blur(30px);');

        // FAB tokens
        lines.push('  --nxt1-fab-size: 48px;');
        lines.push('  --nxt1-fab-radius: 50%;');
        lines.push(
          `  --nxt1-fab-shadow: 0 4px 16px rgba(${r}, ${g}, ${b}, 0.4), 0 2px 6px rgba(0, 0, 0, 0.2);`
        );
        lines.push(
          `  --nxt1-fab-shadowActive: 0 0 30px rgba(${r}, ${g}, ${b}, 0.5), 0 0 60px rgba(${r}, ${g}, ${b}, 0.3), 0 4px 20px rgba(0, 0, 0, 0.4);`
        );
        lines.push(
          `  --nxt1-fab-gradientActive: linear-gradient(135deg, rgba(${r}, ${g}, ${b}, 0.8) 0%, rgba(${Math.min(r + 50, 255)}, ${Math.min(g + 50, 255)}, ${Math.min(b + 50, 255)}, 0.6) 100%);`
        );
        lines.push(
          `  --nxt1-fab-glowActive: linear-gradient(135deg, rgba(${r}, ${g}, ${b}, 0.4) 0%, rgba(${r}, ${g}, ${b}, 0.2) 100%);`
        );

        // Navigation tokens
        lines.push(
          '  --nxt1-navigation-dropdown: 0 8px 32px rgba(0, 0, 0, 0.32), 0 2px 8px rgba(0, 0, 0, 0.24);'
        );
        lines.push(
          '  --nxt1-navigation-elevated: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.08);'
        );

        // Tab tokens
        lines.push(`  --nxt1-tab-activeBg: rgba(${r}, ${g}, ${b}, 0.15);`);
        lines.push('  --nxt1-tab-iconSize: 26px;');
        lines.push('  --nxt1-tab-labelSize: 10px;');
        lines.push('  --nxt1-tab-labelGap: 4px;');
        lines.push('  --nxt1-tab-paddingY: 6px;');
        lines.push('  --nxt1-tab-radius: 24px;');

        // Icon tokens (active uses primary color)
        lines.push(`  --nxt1-icon-active: ${resolvedPrimary};`);
        lines.push('  --nxt1-icon-inactive: #666666;');

        // Pill tokens
        lines.push('  --nxt1-pill-height: 48px;');
        lines.push('  --nxt1-pill-radius: 28px;');
        lines.push('  --nxt1-pill-padding: 2px;');
        lines.push('  --nxt1-pill-gap: 4px;');

        // Ripple token
        lines.push(`  --nxt1-ripple-color: rgba(${r}, ${g}, ${b}, 0.12);`);
      }
    }
  }

  // Team theme needs surface convenience tokens since its primary/secondary use
  // runtime CSS vars (not literal hex), so the primary-color block above is skipped.
  if (themeName === 'team') {
    lines.push('');
    lines.push('  /* Surface convenience tokens (team theme card/panel backgrounds) */');
    lines.push('  --nxt1-color-surface-primary: var(--nxt1-color-surface-100);');
    lines.push('  --nxt1-color-surface-secondary: var(--nxt1-color-surface-200);');
    lines.push('  --nxt1-color-surface-hover: rgba(255, 255, 255, 0.04);');
    lines.push('  --nxt1-color-surface-active: rgba(255, 255, 255, 0.06);');
  }

  lines.push('}');
  return lines.join('\n');
}

function generateCombinedCss(primitiveTokens, semanticTokens, allTokens) {
  const lines = [
    '/**',
    ' * @fileoverview NXT1 Design Tokens - Complete CSS',
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' * @source tokens.json/',
    ' *',
    ' * This file contains all design tokens as CSS custom properties.',
    ' * Import this single file to get all tokens with dark theme as default.',
    ' *',
    ' * Usage:',
    ' *   @import "@nxt1/design-tokens/dist/css/tokens.css";',
    ' *',
    ' * Theme switching:',
    ' *   <html data-theme="light"> for light theme',
    ' *   <html data-theme="dark"> or default for dark theme',
    ' */',
    '',
    '/* ============================================',
    '   PRIMITIVE TOKENS',
    '   Raw values - colors, spacing, typography',
    '   ============================================ */',
    '',
  ];

  // Primitive tokens
  const primitiveFlat = flattenTokens(primitiveTokens);
  lines.push(':root {');

  // Group by category for readability
  const categories = {};
  for (const [key, token] of Object.entries(primitiveFlat)) {
    const category = key.split('-')[0];
    if (!categories[category]) categories[category] = [];
    categories[category].push({ key, token });
  }

  for (const [category, tokens] of Object.entries(categories)) {
    lines.push(`  /* ${category.toUpperCase()} */`);
    for (const { key, token } of tokens) {
      const cssKey = sanitizeCssKey(key);
      const resolved = resolveReference(token.value, allTokens);
      lines.push(`  --nxt1-${cssKey}: ${resolved};`);
    }
    lines.push('');
  }

  lines.push('}');
  lines.push('');

  // Dark theme (default)
  lines.push('/* ============================================');
  lines.push('   DARK THEME (DEFAULT)');
  lines.push('   ============================================ */');
  lines.push('');

  const darkTokens = semanticTokens.theme?.dark;
  if (darkTokens) {
    lines.push(':root,');
    lines.push('[data-theme="dark"],');
    lines.push('.dark-theme {');
    lines.push('  color-scheme: dark;');
    lines.push('');

    const darkFlat = flattenTokens(darkTokens);
    for (const [key, token] of Object.entries(darkFlat)) {
      let cssKey = sanitizeCssKey(
        key.replace(/^color-background-/, 'color-bg-').replace(/^color-feedback-/, 'color-')
      );
      const resolved = resolveReference(token.value, allTokens);
      lines.push(`  --nxt1-${cssKey}: ${resolved};`);
    }

    // Navigation solid background tokens for dark theme
    lines.push('');
    lines.push('  /* Navigation solid background tokens (from design tokens) */');
    lines.push('  --nxt1-nav-bgSolid: rgb(22, 22, 22);');
    lines.push('  --nxt1-nav-borderSolid: rgba(255, 255, 255, 0.12);');
    lines.push(
      '  --nxt1-nav-shadowSolid: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.08);'
    );

    lines.push('}');
  }

  lines.push('');

  // Light theme
  lines.push('/* ============================================');
  lines.push('   LIGHT THEME');
  lines.push('   ============================================ */');
  lines.push('');

  const lightTokens = semanticTokens.theme?.light;
  if (lightTokens) {
    lines.push('[data-theme="light"],');
    lines.push('.light-theme {');
    lines.push('  color-scheme: light;');
    lines.push('');

    const lightFlat = flattenTokens(lightTokens);
    for (const [key, token] of Object.entries(lightFlat)) {
      let cssKey = sanitizeCssKey(
        key.replace(/^color-background-/, 'color-bg-').replace(/^color-feedback-/, 'color-')
      );
      const resolved = resolveReference(token.value, allTokens);
      lines.push(`  --nxt1-${cssKey}: ${resolved};`);
    }

    // Navigation solid background tokens for light theme
    lines.push('');
    lines.push('  /* Navigation solid background tokens (from design tokens) */');
    lines.push('  --nxt1-nav-bgSolid: rgb(250, 250, 250);');
    lines.push('  --nxt1-nav-borderSolid: rgba(0, 0, 0, 0.12);');
    lines.push(
      '  --nxt1-nav-shadowSolid: 0 1px 3px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.04);'
    );

    lines.push('}');
  }

  // Additional themes (sport themes, custom themes, etc.)
  const additionalThemes = Object.entries(semanticTokens.theme || {}).filter(
    ([name]) => !name.startsWith('$') && name !== 'dark' && name !== 'light'
  );

  for (const [themeName, themeTokens] of additionalThemes) {
    lines.push('');
    lines.push('/* ============================================');
    lines.push(`   ${themeName.toUpperCase().replace(/-/g, ' ')} THEME`);
    lines.push('   ============================================ */');
    lines.push('');

    lines.push(`[data-theme="${themeName}"],`);
    lines.push(`.${themeName}-theme {`);
    lines.push('  color-scheme: dark;'); // Sport themes are dark-based
    lines.push('');

    const themeFlat = flattenTokens(themeTokens);
    for (const [key, token] of Object.entries(themeFlat)) {
      let cssKey = sanitizeCssKey(
        key.replace(/^color-background-/, 'color-bg-').replace(/^color-feedback-/, 'color-')
      );
      const resolved = resolveReference(token.value, allTokens);
      lines.push(`  --nxt1-${cssKey}: ${resolved};`);
    }

    // ============================================
    // AUTO-GENERATE COMPONENT TOKENS FOR SPORT/TEAM THEMES
    // Sport themes inherit component tokens from dark theme,
    // but use their PRIMARY color for active states and glows.
    // This is 2026 best practice - DRY principle.
    // ============================================
    const primaryColor = themeFlat['color-primary']?.value;
    const surfaceColor = themeFlat['color-surface-100']?.value || 'rgba(22, 22, 22, 0.88)';

    if (primaryColor) {
      const resolvedPrimary = resolveReference(primaryColor, allTokens);
      const primaryRgb = hexToRgb(resolvedPrimary);

      if (primaryRgb) {
        const { r, g, b } = primaryRgb;

        lines.push('');
        lines.push('  /* Auto-generated component tokens (based on primary color) */');

        // Glass tokens (dark-based with theme surface color)
        const resolvedSurface = resolveReference(surfaceColor, allTokens);
        const surfaceRgb = hexToRgb(resolvedSurface) || { r: 22, g: 22, b: 22 };
        lines.push(
          `  --nxt1-glass-bg: rgba(${surfaceRgb.r}, ${surfaceRgb.g}, ${surfaceRgb.b}, 0.88);`
        );
        lines.push(
          `  --nxt1-glass-bgSolid: rgba(${surfaceRgb.r}, ${surfaceRgb.g}, ${surfaceRgb.b}, 0.95);`
        );
        lines.push('  --nxt1-glass-border: rgba(255, 255, 255, 0.12);');
        lines.push('  --nxt1-glass-borderSubtle: rgba(255, 255, 255, 0.08);');
        lines.push(
          '  --nxt1-glass-shadow: 0 8px 32px rgba(0, 0, 0, 0.45), 0 2px 8px rgba(0, 0, 0, 0.25);'
        );
        lines.push('  --nxt1-glass-shadowInner: inset 0 1px 0 rgba(255, 255, 255, 0.06);');
        lines.push('  --nxt1-glass-backdrop: saturate(180%) blur(20px);');
        lines.push('  --nxt1-glass-backdropStrong: saturate(200%) blur(30px);');

        // Navigation solid background tokens (fully opaque for non-glass mode)
        lines.push(`  --nxt1-nav-bgSolid: rgb(${surfaceRgb.r}, ${surfaceRgb.g}, ${surfaceRgb.b});`);
        lines.push('  --nxt1-nav-borderSolid: rgba(255, 255, 255, 0.12);');
        lines.push(
          '  --nxt1-nav-shadowSolid: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.08);'
        );

        // FAB tokens (use theme primary color for glow)
        lines.push('  --nxt1-fab-size: 48px;');
        lines.push('  --nxt1-fab-radius: 50%;');
        lines.push(
          `  --nxt1-fab-shadow: 0 4px 16px rgba(${r}, ${g}, ${b}, 0.4), 0 2px 6px rgba(0, 0, 0, 0.2);`
        );
        lines.push(
          `  --nxt1-fab-shadowActive: 0 0 30px rgba(${r}, ${g}, ${b}, 0.5), 0 0 60px rgba(${r}, ${g}, ${b}, 0.3), 0 4px 20px rgba(0, 0, 0, 0.4);`
        );
        lines.push(
          `  --nxt1-fab-gradientActive: linear-gradient(135deg, rgba(${r}, ${g}, ${b}, 0.8) 0%, rgba(${Math.min(r + 50, 255)}, ${Math.min(g + 50, 255)}, ${Math.min(b + 50, 255)}, 0.6) 100%);`
        );
        lines.push(
          `  --nxt1-fab-glowActive: linear-gradient(135deg, rgba(${r}, ${g}, ${b}, 0.4) 0%, rgba(${r}, ${g}, ${b}, 0.2) 100%);`
        );

        // Navigation tokens
        lines.push(
          '  --nxt1-navigation-dropdown: 0 8px 32px rgba(0, 0, 0, 0.32), 0 2px 8px rgba(0, 0, 0, 0.24);'
        );
        lines.push(
          '  --nxt1-navigation-elevated: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.08);'
        );

        // Tab tokens (use primary for active highlight)
        lines.push(`  --nxt1-tab-activeBg: rgba(${r}, ${g}, ${b}, 0.15);`);
        lines.push('  --nxt1-tab-iconSize: 26px;');
        lines.push('  --nxt1-tab-labelSize: 10px;');
        lines.push('  --nxt1-tab-labelGap: 4px;');
        lines.push('  --nxt1-tab-paddingY: 6px;');
        lines.push('  --nxt1-tab-radius: 24px;');

        // Icon tokens (active uses primary color)
        lines.push(`  --nxt1-icon-active: ${resolvedPrimary};`);
        lines.push('  --nxt1-icon-inactive: #666666;');

        // Pill tokens
        lines.push('  --nxt1-pill-height: 48px;');
        lines.push('  --nxt1-pill-radius: 28px;');
        lines.push('  --nxt1-pill-padding: 2px;');
        lines.push('  --nxt1-pill-gap: 4px;');

        // Ripple token
        lines.push(`  --nxt1-ripple-color: rgba(${r}, ${g}, ${b}, 0.12);`);
      }
    }

    // Surface convenience tokens — only for team theme, which uses runtime CSS vars
    // for primary/secondary colors so its surface tokens must also be explicitly defined.
    if (themeName === 'team') {
      lines.push('');
      lines.push('  /* Surface convenience tokens (team theme card/panel backgrounds) */');
      lines.push('  --nxt1-color-surface-primary: var(--nxt1-color-surface-100);');
      lines.push('  --nxt1-color-surface-secondary: var(--nxt1-color-surface-200);');
      lines.push('  --nxt1-color-surface-hover: rgba(255, 255, 255, 0.04);');
      lines.push('  --nxt1-color-surface-active: rgba(255, 255, 255, 0.06);');
    }

    lines.push('}');
  }

  return lines.join('\n');
}

/**
 * Convert hex color to RGB values
 * Supports #RGB, #RRGGBB formats
 */
function hexToRgb(hex) {
  if (!hex || typeof hex !== 'string') return null;

  // Remove # if present
  hex = hex.replace(/^#/, '');

  // Handle shorthand (#RGB)
  if (hex.length === 3) {
    hex = hex
      .split('')
      .map((c) => c + c)
      .join('');
  }

  if (hex.length !== 6) return null;

  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);

  if (isNaN(r) || isNaN(g) || isNaN(b)) return null;

  return { r, g, b };
}

// ============================================
// SCSS GENERATION
// ============================================

/**
 * Sanitize a key for SCSS variable names
 * SCSS variables can't start with numbers or contain dots
 */
function toScssVarName(key) {
  return key
    .replace(/\./g, '_') // Replace dots with underscores
    .replace(/^(\d)/, '_$1'); // Prefix leading numbers with underscore
}

function generateScssTokens(primitiveTokens, semanticTokens, allTokens) {
  const lines = [
    '// ============================================',
    '// NXT1 Design Tokens - SCSS Variables',
    '// @generated by build.mjs - DO NOT EDIT MANUALLY',
    '// @source tokens.json/',
    '// ============================================',
    '',
    '// Usage:',
    '//   @use "@nxt1/design-tokens/dist/scss/tokens" as tokens;',
    '//   color: tokens.$nxt1-color-primary;',
    '//   background: var(--nxt1-color-bg-primary);',
    '',
  ];

  // SCSS variables from primitives
  const primitiveFlat = flattenTokens(primitiveTokens);

  lines.push('// PRIMITIVE TOKENS');
  for (const [key, token] of Object.entries(primitiveFlat)) {
    const resolved = resolveReference(token.value, allTokens);
    const scssKey = toScssVarName(key);
    lines.push(`$nxt1-${scssKey}: ${resolved};`);
  }

  lines.push('');
  lines.push('// SEMANTIC TOKENS (CSS variable references for runtime theming)');

  // Generate SCSS vars that reference CSS custom properties
  const darkTokens = semanticTokens.theme?.dark;
  if (darkTokens) {
    const darkFlat = flattenTokens(darkTokens);
    for (const [key] of Object.entries(darkFlat)) {
      let cssKey = sanitizeCssKey(
        key.replace(/^color-background-/, 'color-bg-').replace(/^color-feedback-/, 'color-')
      );
      const scssKey = toScssVarName(cssKey);
      lines.push(`$nxt1-${scssKey}: var(--nxt1-${cssKey});`);
    }
  }

  lines.push('');
  lines.push('// TOKEN MAPS (for programmatic access)');
  lines.push('$nxt1-colors: (');

  // Color map
  const colorTokens = flattenTokens(primitiveTokens.color || {});
  for (const [key, token] of Object.entries(colorTokens)) {
    const resolved = resolveReference(token.value, allTokens);
    lines.push(`  "${key}": ${resolved},`);
  }
  lines.push(');');

  lines.push('');
  lines.push('$nxt1-spacing: (');
  const spacingTokens = flattenTokens(primitiveTokens.spacing || {});
  for (const [key, token] of Object.entries(spacingTokens)) {
    lines.push(`  "${key}": ${token.value},`);
  }
  lines.push(');');

  return lines.join('\n');
}

// ============================================
// JAVASCRIPT GENERATION
// ============================================

function generateJsTokens(primitiveTokens, semanticTokens, componentTokens, allTokens) {
  const primitiveFlat = flattenTokens(primitiveTokens);
  const componentFlat = flattenTokens(componentTokens);

  const lines = [
    '/**',
    ' * @fileoverview NXT1 Design Tokens - JavaScript Module',
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' * @source tokens.json/',
    ' *',
    ' * Usage:',
    ' *   import { colors, spacing, tokens } from "@nxt1/design-tokens";',
    ' *   import tokens from "@nxt1/design-tokens";',
    ' */',
    '',
    '// Primitive color palette',
    'export const colors = {',
  ];

  const colorTokens = flattenTokens(primitiveTokens.color || {});
  for (const [key, token] of Object.entries(colorTokens)) {
    const resolved = resolveReference(token.value, allTokens);
    const jsKey = key.replace(/-/g, '_').replace(/\./g, '_');
    lines.push(`  ${jsKey}: '${resolved}',`);
  }
  lines.push('};');
  lines.push('');

  // Spacing
  lines.push('// Spacing scale');
  lines.push('export const spacing = {');
  const spacingTokens = flattenTokens(primitiveTokens.spacing || {});
  for (const [key, token] of Object.entries(spacingTokens)) {
    const jsKey = key === 'px' ? 'px' : `_${key}`.replace('.', '_');
    lines.push(`  '${key}': '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  // Border radius
  lines.push('// Border radius');
  lines.push('export const borderRadius = {');
  const radiusTokens = flattenTokens(primitiveTokens.borderRadius || {});
  for (const [key, token] of Object.entries(radiusTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  // Typography
  lines.push('// Font families');
  lines.push('export const fontFamily = {');
  const fontFamilyTokens = flattenTokens(primitiveTokens.fontFamily || {});
  for (const [key, token] of Object.entries(fontFamilyTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  lines.push('// Font sizes');
  lines.push('export const fontSize = {');
  const fontSizeTokens = flattenTokens(primitiveTokens.fontSize || {});
  for (const [key, token] of Object.entries(fontSizeTokens)) {
    const jsKey = key.replace(/^(\d)/, '_$1');
    lines.push(`  '${key}': '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  lines.push('// Font weights');
  lines.push('export const fontWeight = {');
  const fontWeightTokens = flattenTokens(primitiveTokens.fontWeight || {});
  for (const [key, token] of Object.entries(fontWeightTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  // Animation
  lines.push('// Animation durations');
  lines.push('export const duration = {');
  const durationTokens = flattenTokens(primitiveTokens.duration || {});
  for (const [key, token] of Object.entries(durationTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  lines.push('// Animation easings');
  lines.push('export const easing = {');
  const easingTokens = flattenTokens(primitiveTokens.easing || {});
  for (const [key, token] of Object.entries(easingTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  // Z-index
  lines.push('// Z-index layers');
  lines.push('export const zIndex = {');
  const zIndexTokens = flattenTokens(primitiveTokens.zIndex || {});
  for (const [key, token] of Object.entries(zIndexTokens)) {
    lines.push(`  ${key}: ${token.value},`);
  }
  lines.push('};');
  lines.push('');

  // Breakpoints
  lines.push('// Breakpoints');
  lines.push('export const breakpoints = {');
  const breakpointTokens = flattenTokens(primitiveTokens.breakpoint || {});
  for (const [key, token] of Object.entries(breakpointTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  // Components
  lines.push('// Component tokens');
  lines.push('export const components = {');
  const compTokens = flattenTokens(componentTokens.component || {});
  for (const [key, token] of Object.entries(compTokens)) {
    const resolved = resolveReference(token.value, allTokens);
    lines.push(`  '${key}': '${resolved}',`);
  }
  lines.push('};');
  lines.push('');

  // Default export
  lines.push('// Combined default export');
  lines.push('const tokens = {');
  lines.push('  colors,');
  lines.push('  spacing,');
  lines.push('  borderRadius,');
  lines.push('  fontFamily,');
  lines.push('  fontSize,');
  lines.push('  fontWeight,');
  lines.push('  duration,');
  lines.push('  easing,');
  lines.push('  zIndex,');
  lines.push('  breakpoints,');
  lines.push('  components,');
  lines.push('};');
  lines.push('');
  lines.push('export default tokens;');

  return lines.join('\n');
}

function generateTypeDefinitions(primitiveTokens, componentTokens) {
  const lines = [
    '/**',
    ' * @fileoverview NXT1 Design Tokens - TypeScript Definitions',
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' */',
    '',
    'declare const colors: {',
  ];

  const colorTokens = flattenTokens(primitiveTokens.color || {});
  for (const key of Object.keys(colorTokens)) {
    const tsKey = key.replace(/-/g, '_').replace(/\./g, '_');
    lines.push(`  readonly ${tsKey}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const spacing: {');
  const spacingTokens = flattenTokens(primitiveTokens.spacing || {});
  for (const key of Object.keys(spacingTokens)) {
    lines.push(`  readonly '${key}': string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const borderRadius: {');
  const radiusTokens = flattenTokens(primitiveTokens.borderRadius || {});
  for (const key of Object.keys(radiusTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const fontFamily: {');
  const fontFamilyTokens = flattenTokens(primitiveTokens.fontFamily || {});
  for (const key of Object.keys(fontFamilyTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const fontSize: {');
  const fontSizeTokens = flattenTokens(primitiveTokens.fontSize || {});
  for (const key of Object.keys(fontSizeTokens)) {
    lines.push(`  readonly '${key}': string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const fontWeight: {');
  const fontWeightTokens = flattenTokens(primitiveTokens.fontWeight || {});
  for (const key of Object.keys(fontWeightTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const duration: {');
  const durationTokens = flattenTokens(primitiveTokens.duration || {});
  for (const key of Object.keys(durationTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const easing: {');
  const easingTokens = flattenTokens(primitiveTokens.easing || {});
  for (const key of Object.keys(easingTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const zIndex: {');
  const zIndexTokens = flattenTokens(primitiveTokens.zIndex || {});
  for (const key of Object.keys(zIndexTokens)) {
    lines.push(`  readonly ${key}: number;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const breakpoints: {');
  const breakpointTokens = flattenTokens(primitiveTokens.breakpoint || {});
  for (const key of Object.keys(breakpointTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const components: {');
  const compTokens = flattenTokens(componentTokens.component || {});
  for (const key of Object.keys(compTokens)) {
    lines.push(`  readonly '${key}': string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('interface NXT1Tokens {');
  lines.push('  colors: typeof colors;');
  lines.push('  spacing: typeof spacing;');
  lines.push('  borderRadius: typeof borderRadius;');
  lines.push('  fontFamily: typeof fontFamily;');
  lines.push('  fontSize: typeof fontSize;');
  lines.push('  fontWeight: typeof fontWeight;');
  lines.push('  duration: typeof duration;');
  lines.push('  easing: typeof easing;');
  lines.push('  zIndex: typeof zIndex;');
  lines.push('  breakpoints: typeof breakpoints;');
  lines.push('  components: typeof components;');
  lines.push('}');
  lines.push('');
  lines.push('declare const tokens: NXT1Tokens;');
  lines.push('');
  lines.push('export {');
  lines.push('  colors,');
  lines.push('  spacing,');
  lines.push('  borderRadius,');
  lines.push('  fontFamily,');
  lines.push('  fontSize,');
  lines.push('  fontWeight,');
  lines.push('  duration,');
  lines.push('  easing,');
  lines.push('  zIndex,');
  lines.push('  breakpoints,');
  lines.push('  components,');
  lines.push('};');
  lines.push('');
  lines.push('export default tokens;');

  return lines.join('\n');
}

// ============================================
// JSON GENERATION (Resolved)
// ============================================

function generateResolvedJson(primitiveTokens, semanticTokens, componentTokens, allTokens) {
  const resolved = {
    $schema: 'https://design-tokens.github.io/community-group/format/',
    $description: 'NXT1 Design Tokens - Resolved values (generated)',
    primitive: {},
    semantic: {},
    component: {},
  };

  // Resolve primitives
  const primitiveFlat = flattenTokens(primitiveTokens);
  for (const [key, token] of Object.entries(primitiveFlat)) {
    resolved.primitive[key] = {
      value: resolveReference(token.value, allTokens),
      type: token.type,
    };
  }

  // Resolve semantic (dark theme)
  if (semanticTokens.theme?.dark) {
    const darkFlat = flattenTokens(semanticTokens.theme.dark);
    resolved.semantic.dark = {};
    for (const [key, token] of Object.entries(darkFlat)) {
      resolved.semantic.dark[key] = {
        value: resolveReference(token.value, allTokens),
        type: token.type,
      };
    }
  }

  // Resolve semantic (light theme)
  if (semanticTokens.theme?.light) {
    const lightFlat = flattenTokens(semanticTokens.theme.light);
    resolved.semantic.light = {};
    for (const [key, token] of Object.entries(lightFlat)) {
      resolved.semantic.light[key] = {
        value: resolveReference(token.value, allTokens),
        type: token.type,
      };
    }
  }

  // Resolve components
  if (componentTokens.component) {
    const componentFlat = flattenTokens(componentTokens);
    for (const [key, token] of Object.entries(componentFlat)) {
      resolved.component[key] = {
        value: resolveReference(token.value, allTokens),
        type: token.type,
      };
    }
  }

  return JSON.stringify(resolved, null, 2);
}

// ============================================
// IONIC CSS GENERATION (Auto-mapped from tokens)
// ============================================

/**
 * Generate Ionic CSS from design tokens.
 * This eliminates the need for a separate hand-maintained ionic-theme.css
 *
 * Why Ionic needs special handling:
 * 1. Ionic uses --ion-* variable names (not --nxt1-*)
 * 2. Ionic requires separate RGB values for opacity calculations in Shadow DOM
 * 3. These mappings must be generated, not hand-maintained
 */
function generateIonicCss(semanticTokens, allTokens) {
  const lines = [
    '/**',
    ' * @fileoverview NXT1 Ionic Theme Integration',
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' * @source tokens.json/',
    ' *',
    ' * Auto-generated mappings from NXT1 design tokens to Ionic CSS variables.',
    ' * This ensures Ionic components stay in sync with the design system.',
    ' */',
    '',
  ];

  // Helper to extract RGB from hex
  function hexToRgb(hex) {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    if (result) {
      return `${parseInt(result[1], 16)}, ${parseInt(result[2], 16)}, ${parseInt(result[3], 16)}`;
    }
    return '0, 0, 0';
  }

  // Helper to resolve token value
  function resolve(value) {
    return resolveReference(value, allTokens);
  }

  // Dark theme base (applied to :root)
  const dark = semanticTokens.theme?.dark;
  if (dark) {
    const primary = resolve(dark.color?.primary?.$value) || '#ccff00';
    const bgPrimary = resolve(dark.color?.background?.primary?.$value) || '#0a0a0a';
    const bgSecondary = resolve(dark.color?.background?.secondary?.$value) || '#121212';
    const surface100 = resolve(dark.color?.surface?.['100']?.$value) || '#161616';

    lines.push('/* ============================================');
    lines.push('   DARK THEME BASE (Default)');
    lines.push('   ============================================ */');
    lines.push('');
    lines.push(':root,');
    lines.push('[data-theme="dark"] {');
    lines.push('  color-scheme: dark;');
    lines.push('');
    lines.push('  /* Primary Color */');
    lines.push(`  --ion-color-primary: ${primary};`);
    lines.push(`  --ion-color-primary-rgb: ${hexToRgb(primary)};`);
    lines.push('  --ion-color-primary-contrast: #0a0a0a;');
    lines.push('  --ion-color-primary-contrast-rgb: 10, 10, 10;');
    lines.push(
      `  --ion-color-primary-shade: ${resolve(dark.color?.primaryDark?.$value) || '#b8e600'};`
    );
    lines.push(
      `  --ion-color-primary-tint: ${resolve(dark.color?.primaryLight?.$value) || '#d4ff4d'};`
    );
    lines.push('');
    lines.push('  /* Background Colors */');
    lines.push(`  --ion-background-color: ${bgPrimary};`);
    lines.push(`  --ion-background-color-rgb: ${hexToRgb(bgPrimary)};`);
    lines.push('  --ion-text-color: #ffffff;');
    lines.push('  --ion-text-color-rgb: 255, 255, 255;');
    lines.push(`  --ion-item-background: ${surface100};`);
    lines.push(`  --ion-card-background: ${surface100};`);
    lines.push(`  --ion-toolbar-background: ${bgSecondary};`);
    lines.push('  --ion-toolbar-color: #ffffff;');
    lines.push('');
    lines.push('  /* Tab Bar (Glass Effect) */');
    lines.push('  --ion-tab-bar-background: rgba(22, 22, 22, 0.88);');
    lines.push('  --ion-tab-bar-color: rgba(255, 255, 255, 0.5);');
    lines.push('  --ion-tab-bar-color-selected: #ffffff;');
    lines.push('');
    lines.push('  /* Borders & Misc */');
    lines.push('  --ion-border-color: rgba(255, 255, 255, 0.08);');
    lines.push('  --ion-placeholder-color: rgba(255, 255, 255, 0.5);');
    lines.push('}');
    lines.push('');
  }

  // Light theme
  const light = semanticTokens.theme?.light;
  if (light) {
    const primary = resolve(light.color?.primary?.$value) || '#a3cc00';
    const bgPrimary = resolve(light.color?.background?.primary?.$value) || '#fafafa';

    lines.push('/* ============================================');
    lines.push('   LIGHT THEME');
    lines.push('   ============================================ */');
    lines.push('');
    lines.push('[data-theme="light"] {');
    lines.push('  color-scheme: light;');
    lines.push('');
    lines.push(`  --ion-color-primary: ${primary};`);
    lines.push(`  --ion-color-primary-rgb: ${hexToRgb(primary)};`);
    lines.push('  --ion-color-primary-contrast: #0a0a0a;');
    lines.push('  --ion-color-primary-contrast-rgb: 10, 10, 10;');
    lines.push('');
    lines.push(`  --ion-background-color: ${bgPrimary};`);
    lines.push(`  --ion-background-color-rgb: ${hexToRgb(bgPrimary)};`);
    lines.push(`  --ion-text-color: ${resolve(light.color?.text?.primary?.$value) || '#212121'};`);
    lines.push('  --ion-text-color-rgb: 33, 33, 33;');
    lines.push('  --ion-item-background: #ffffff;');
    lines.push('  --ion-card-background: #ffffff;');
    lines.push('  --ion-toolbar-background: #ffffff;');
    lines.push(
      `  --ion-toolbar-color: ${resolve(light.color?.text?.primary?.$value) || '#212121'};`
    );
    lines.push('');
    lines.push('  --ion-tab-bar-background: rgba(255, 255, 255, 0.88);');
    lines.push('  --ion-tab-bar-color: rgba(0, 0, 0, 0.5);');
    lines.push('  --ion-tab-bar-color-selected: #000000;');
    lines.push('');
    lines.push('  --ion-border-color: rgba(0, 0, 0, 0.08);');
    lines.push('  --ion-placeholder-color: rgba(0, 0, 0, 0.5);');
    lines.push('}');
    lines.push('');
  }

  // Sport themes - FULL Ionic variable override (not just primary)
  const sportThemes = Object.entries(semanticTokens.theme || {}).filter(([name]) =>
    name.startsWith('sport-')
  );

  if (sportThemes.length > 0) {
    lines.push('/* ============================================');
    lines.push('   SPORT THEMES');
    lines.push('   Full Ionic override - primary, backgrounds, tab bar');
    lines.push('   ============================================ */');
    lines.push('');

    for (const [themeName, themeTokens] of sportThemes) {
      const primary = resolve(themeTokens.color?.primary?.$value);
      const primaryLight = resolve(themeTokens.color?.primaryLight?.$value);
      const primaryDark = resolve(themeTokens.color?.primaryDark?.$value);
      const textOnPrimary = resolve(themeTokens.color?.text?.onPrimary?.$value) || '#000000';

      // Background colors from sport theme
      const bgPrimary = resolve(themeTokens.color?.background?.primary?.$value);
      const surface100 = resolve(themeTokens.color?.surface?.['100']?.$value);
      const surface200 = resolve(themeTokens.color?.surface?.['200']?.$value);
      const textPrimary = resolve(themeTokens.color?.text?.primary?.$value) || '#ffffff';

      if (primary) {
        const displayName = themeName.replace('sport-', '').replace(/-/g, ' ');
        lines.push(`/* ${displayName.charAt(0).toUpperCase() + displayName.slice(1)} */`);
        lines.push(`[data-theme="${themeName}"] {`);
        lines.push('  color-scheme: dark;');
        lines.push('');

        // Primary color
        lines.push(`  --ion-color-primary: ${primary};`);
        lines.push(`  --ion-color-primary-rgb: ${hexToRgb(primary)};`);
        lines.push(`  --ion-color-primary-contrast: ${textOnPrimary};`);
        lines.push(`  --ion-color-primary-contrast-rgb: ${hexToRgb(textOnPrimary)};`);
        if (primaryDark) lines.push(`  --ion-color-primary-shade: ${primaryDark};`);
        if (primaryLight) lines.push(`  --ion-color-primary-tint: ${primaryLight};`);
        lines.push('');

        // Background colors (sport-specific, not dark default)
        if (bgPrimary) {
          lines.push(`  --ion-background-color: ${bgPrimary};`);
          lines.push(`  --ion-background-color-rgb: ${hexToRgb(bgPrimary)};`);
        }
        lines.push(`  --ion-text-color: ${textPrimary};`);
        lines.push(`  --ion-text-color-rgb: ${hexToRgb(textPrimary)};`);

        if (surface100) {
          lines.push(`  --ion-item-background: ${surface100};`);
          lines.push(`  --ion-card-background: ${surface100};`);
        }
        if (surface200) {
          lines.push(`  --ion-toolbar-background: ${surface200};`);
        }
        lines.push(`  --ion-toolbar-color: ${textPrimary};`);
        lines.push('');

        // Tab bar with sport-themed glass effect
        if (surface100) {
          const surfaceRgb = hexToRgb(surface100);
          if (surfaceRgb) {
            const [r, g, b] = surfaceRgb.split(', ').map(Number);
            lines.push(`  --ion-tab-bar-background: rgba(${r}, ${g}, ${b}, 0.88);`);
          }
        }
        lines.push('  --ion-tab-bar-color: rgba(255, 255, 255, 0.5);');
        lines.push(`  --ion-tab-bar-color-selected: ${primary};`);
        lines.push('');

        // Border color
        lines.push('  --ion-border-color: rgba(255, 255, 255, 0.08);');
        lines.push('  --ion-placeholder-color: rgba(255, 255, 255, 0.5);');

        lines.push('}');
        lines.push('');
      }
    }
  }

  // Team theme (dynamic)
  if (semanticTokens.theme?.team) {
    lines.push('/* ============================================');
    lines.push('   TEAM THEME (Dynamic via CSS custom properties)');
    lines.push('   ============================================ */');
    lines.push('');
    lines.push('[data-theme="team"] {');
    lines.push('  --ion-color-primary: var(--team-primary, #ccff00);');
    lines.push('  --ion-color-primary-rgb: var(--team-primary-rgb, 204, 255, 0);');
    lines.push('  --ion-color-primary-contrast: var(--team-text-on-primary, #0a0a0a);');
    lines.push('  --ion-color-primary-contrast-rgb: var(--team-text-on-primary-rgb, 10, 10, 10);');
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

// ============================================
// MAIN BUILD FUNCTION
// ============================================

function ensureDir(dir) {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function cleanDist() {
  if (existsSync(DIST_DIR)) {
    rmSync(DIST_DIR, { recursive: true });
  }
}

function build() {
  console.log('🎨 NXT1 Design Token Build');
  console.log('==========================\n');

  // Clean previous build
  console.log('🧹 Cleaning dist/...');
  cleanDist();

  // Create directories
  ensureDir(join(DIST_DIR, 'css'));
  ensureDir(join(DIST_DIR, 'css/themes'));
  ensureDir(join(DIST_DIR, 'scss'));
  ensureDir(join(DIST_DIR, 'js'));
  ensureDir(join(DIST_DIR, 'json'));
  ensureDir(join(DIST_DIR, 'ionic'));

  // Load tokens
  console.log('📦 Loading tokens from tokens.json/...');
  const { primitiveTokens, semanticTokens, componentTokens } = loadTokens();

  // Merge all tokens for reference resolution
  const allTokens = { ...primitiveTokens, ...semanticTokens, ...componentTokens };

  // Generate CSS
  console.log('🎨 Generating CSS...');
  const combinedCss = generateCombinedCss(primitiveTokens, semanticTokens, allTokens);
  writeFileSync(join(DIST_DIR, 'css/tokens.css'), combinedCss);
  console.log('   ✓ dist/css/tokens.css');

  // Generate individual theme files for sport/team themes only (dark/light are in tokens.css)
  if (semanticTokens.theme) {
    for (const [themeName, themeTokens] of Object.entries(semanticTokens.theme)) {
      if (themeName.startsWith('$')) continue; // Skip metadata like $description
      if (themeName === 'dark' || themeName === 'light') continue; // Skip dark/light - they're in tokens.css
      const themeCss = generateThemeCss(themeTokens, themeName, allTokens);
      writeFileSync(join(DIST_DIR, `css/themes/${themeName}.css`), themeCss);
      console.log(`   ✓ dist/css/themes/${themeName}.css`);
    }
  }

  // Generate Ionic CSS (auto-mapped from tokens)
  console.log('📱 Generating Ionic CSS (auto-mapped)...');
  const ionicCss = generateIonicCss(semanticTokens, allTokens);
  writeFileSync(join(DIST_DIR, 'ionic/ionic-generated.css'), ionicCss);
  console.log('   ✓ dist/ionic/ionic-generated.css');

  // Generate SCSS
  console.log('📝 Generating SCSS...');
  const scssTokens = generateScssTokens(primitiveTokens, semanticTokens, allTokens);
  writeFileSync(join(DIST_DIR, 'scss/_tokens.scss'), scssTokens);
  console.log('   ✓ dist/scss/_tokens.scss');

  // Generate JS
  console.log('⚡ Generating JavaScript...');
  const jsTokens = generateJsTokens(primitiveTokens, semanticTokens, componentTokens, allTokens);
  writeFileSync(join(DIST_DIR, 'js/tokens.mjs'), jsTokens);
  console.log('   ✓ dist/js/tokens.mjs');

  // Generate TypeScript definitions
  const dtsTokens = generateTypeDefinitions(primitiveTokens, componentTokens);
  writeFileSync(join(DIST_DIR, 'js/tokens.d.ts'), dtsTokens);
  console.log('   ✓ dist/js/tokens.d.ts');

  // Generate resolved JSON
  console.log('📋 Generating resolved JSON...');
  const resolvedJson = generateResolvedJson(
    primitiveTokens,
    semanticTokens,
    componentTokens,
    allTokens
  );
  writeFileSync(join(DIST_DIR, 'json/resolved.json'), resolvedJson);
  console.log('   ✓ dist/json/resolved.json');

  console.log('\n✅ Build complete!\n');
  console.log('Generated files:');
  console.log('  CSS:   dist/css/tokens.css (combined NXT1 tokens)');
  console.log('         dist/css/themes/dark.css');
  console.log('         dist/css/themes/light.css');
  console.log('  IONIC: dist/ionic/ionic-generated.css (auto-mapped from tokens)');
  console.log('  SCSS:  dist/scss/_tokens.scss (legacy - deprecated)');
  console.log('  JS:    dist/js/tokens.mjs');
  console.log('         dist/js/tokens.d.ts');
  console.log('  JSON:  dist/json/resolved.json');
  console.log('\n📌 Ionic CSS is now auto-generated from tokens.json!');
  console.log('   The hand-maintained ionic/ionic-theme.css can be deprecated.\n');
}

// Run build
build();
