#!/usr/bin/env node
/**
 * @fileoverview NXT1 Design Token Build System
 * @module @nxt1/design-tokens
 *
 * Professional design token pipeline following industry best practices.
 * Similar to Style Dictionary, Figma Tokens, or Amazon Style Dictionary.
 *
 * Flow:
 *   tokens.json/ (DTCG source) → build.mjs → dist/ (generated outputs)
 *
 * Outputs:
 *   - dist/css/tokens.css      (CSS custom properties)
 *   - dist/css/themes/dark.css (Dark theme)
 *   - dist/css/themes/light.css (Light theme)
 *   - dist/scss/_tokens.scss   (SCSS variables)
 *   - dist/js/tokens.mjs       (ES Module)
 *   - dist/js/tokens.d.ts      (TypeScript definitions)
 *   - dist/json/resolved.json  (Resolved JSON for tools)
 *
 * Usage:
 *   npm run build
 *   node build.mjs
 *   node build.mjs --watch
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST_DIR = join(__dirname, 'dist');

// ============================================
// TOKEN FILE LOADING
// ============================================

function loadTokens() {
  const primitiveTokens = JSON.parse(
    readFileSync(join(__dirname, 'tokens.json/primitive.tokens.json'), 'utf-8')
  );
  const semanticTokens = JSON.parse(
    readFileSync(join(__dirname, 'tokens.json/semantic.tokens.json'), 'utf-8')
  );
  const componentTokens = JSON.parse(
    readFileSync(join(__dirname, 'tokens.json/component.tokens.json'), 'utf-8')
  );

  return { primitiveTokens, semanticTokens, componentTokens };
}

// ============================================
// TOKEN REFERENCE RESOLUTION
// ============================================

/**
 * Resolve token references like {color.brand.volt.400}
 */
function resolveReference(value, allTokens) {
  if (typeof value !== 'string') return value;

  const refPattern = /\{([^}]+)\}/g;

  return value.replace(refPattern, (match, path) => {
    const resolved = getValueByPath(allTokens, path);
    if (resolved !== undefined) {
      // Recursively resolve nested references
      return resolveReference(resolved, allTokens);
    }
    console.warn(`⚠️  Unresolved reference: ${match}`);
    return match;
  });
}

function getValueByPath(obj, path) {
  const parts = path.split('.');
  let current = obj;

  for (const part of parts) {
    if (current && typeof current === 'object') {
      // Check for $value at current level
      if (current[part] !== undefined) {
        current = current[part];
      } else {
        return undefined;
      }
    } else {
      return undefined;
    }
  }

  // Return $value if it exists, otherwise the object itself
  return current?.$value ?? current;
}

// ============================================
// CSS GENERATION
// ============================================

/**
 * Sanitize a token key for CSS custom property names
 * CSS vars shouldn't have dots (causes parsing issues in some tools)
 * @param {string} key - The token key (e.g., "spacing-0.5")
 * @returns {string} - Sanitized key (e.g., "spacing-0_5")
 */
function sanitizeCssKey(key) {
  return key.replace(/\./g, '_');
}

function toCssVarName(path) {
  return `--nxt1-${path.join('-').replace(/\./g, '_')}`;
}

function flattenTokens(obj, path = [], result = {}) {
  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith('$')) continue; // Skip metadata

    const newPath = [...path, key];

    if (value && typeof value === 'object' && value.$value !== undefined) {
      // This is a token
      result[newPath.join('-')] = {
        value: value.$value,
        type: value.$type,
        description: value.$description,
        path: newPath,
      };
    } else if (value && typeof value === 'object') {
      // Nested group
      flattenTokens(value, newPath, result);
    }
  }

  return result;
}

function generateCssTokens(primitiveTokens, allTokens) {
  const flattened = flattenTokens(primitiveTokens);
  const lines = [
    '/**',
    ' * @fileoverview NXT1 Design Tokens - CSS Custom Properties',
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' * @source tokens.json/',
    ' */',
    '',
    ':root {',
  ];

  for (const [key, token] of Object.entries(flattened)) {
    const cssKey = sanitizeCssKey(key);
    const cssVar = `--nxt1-${cssKey}`;
    const resolved = resolveReference(token.value, allTokens);

    if (token.description) {
      lines.push(`  /* ${token.description} */`);
    }
    lines.push(`  ${cssVar}: ${resolved};`);
  }

  lines.push('}');
  return lines.join('\n');
}

function generateThemeCss(themeTokens, themeName, allTokens) {
  const flattened = flattenTokens(themeTokens);
  const selector =
    themeName === 'dark'
      ? ':root,\n[data-theme="dark"],\n.dark-theme'
      : '[data-theme="light"],\n.light-theme';

  const colorScheme = themeName === 'dark' ? 'dark' : 'light';

  const lines = [
    '/**',
    ` * @fileoverview NXT1 ${themeName.charAt(0).toUpperCase() + themeName.slice(1)} Theme`,
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' */',
    '',
    `${selector} {`,
    `  color-scheme: ${colorScheme};`,
    '',
  ];

  for (const [key, token] of Object.entries(flattened)) {
    // Convert semantic paths like "background-primary" to "bg-primary"
    let cssKey = sanitizeCssKey(
      key
        .replace(/^color-background-/, 'color-bg-')
        .replace(/^color-text-on/, 'color-text-on-')
        .replace(/^color-feedback-/, 'color-')
    );

    const cssVar = `--nxt1-${cssKey}`;
    const resolved = resolveReference(token.value, allTokens);
    lines.push(`  ${cssVar}: ${resolved};`);
  }

  lines.push('}');
  return lines.join('\n');
}

function generateCombinedCss(primitiveTokens, semanticTokens, allTokens) {
  const lines = [
    '/**',
    ' * @fileoverview NXT1 Design Tokens - Complete CSS',
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' * @source tokens.json/',
    ' *',
    ' * This file contains all design tokens as CSS custom properties.',
    ' * Import this single file to get all tokens with dark theme as default.',
    ' *',
    ' * Usage:',
    ' *   @import "@nxt1/design-tokens/dist/css/tokens.css";',
    ' *',
    ' * Theme switching:',
    ' *   <html data-theme="light"> for light theme',
    ' *   <html data-theme="dark"> or default for dark theme',
    ' */',
    '',
    '/* ============================================',
    '   PRIMITIVE TOKENS',
    '   Raw values - colors, spacing, typography',
    '   ============================================ */',
    '',
  ];

  // Primitive tokens
  const primitiveFlat = flattenTokens(primitiveTokens);
  lines.push(':root {');

  // Group by category for readability
  const categories = {};
  for (const [key, token] of Object.entries(primitiveFlat)) {
    const category = key.split('-')[0];
    if (!categories[category]) categories[category] = [];
    categories[category].push({ key, token });
  }

  for (const [category, tokens] of Object.entries(categories)) {
    lines.push(`  /* ${category.toUpperCase()} */`);
    for (const { key, token } of tokens) {
      const cssKey = sanitizeCssKey(key);
      const resolved = resolveReference(token.value, allTokens);
      lines.push(`  --nxt1-${cssKey}: ${resolved};`);
    }
    lines.push('');
  }

  lines.push('}');
  lines.push('');

  // Dark theme (default)
  lines.push('/* ============================================');
  lines.push('   DARK THEME (DEFAULT)');
  lines.push('   ============================================ */');
  lines.push('');

  const darkTokens = semanticTokens.theme?.dark;
  if (darkTokens) {
    lines.push(':root,');
    lines.push('[data-theme="dark"],');
    lines.push('.dark-theme {');
    lines.push('  color-scheme: dark;');
    lines.push('');

    const darkFlat = flattenTokens(darkTokens);
    for (const [key, token] of Object.entries(darkFlat)) {
      let cssKey = sanitizeCssKey(
        key.replace(/^color-background-/, 'color-bg-').replace(/^color-feedback-/, 'color-')
      );
      const resolved = resolveReference(token.value, allTokens);
      lines.push(`  --nxt1-${cssKey}: ${resolved};`);
    }
    lines.push('}');
  }

  lines.push('');

  // Light theme
  lines.push('/* ============================================');
  lines.push('   LIGHT THEME');
  lines.push('   ============================================ */');
  lines.push('');

  const lightTokens = semanticTokens.theme?.light;
  if (lightTokens) {
    lines.push('[data-theme="light"],');
    lines.push('.light-theme {');
    lines.push('  color-scheme: light;');
    lines.push('');

    const lightFlat = flattenTokens(lightTokens);
    for (const [key, token] of Object.entries(lightFlat)) {
      let cssKey = sanitizeCssKey(
        key.replace(/^color-background-/, 'color-bg-').replace(/^color-feedback-/, 'color-')
      );
      const resolved = resolveReference(token.value, allTokens);
      lines.push(`  --nxt1-${cssKey}: ${resolved};`);
    }
    lines.push('}');
  }

  return lines.join('\n');
}

// ============================================
// SCSS GENERATION
// ============================================

/**
 * Sanitize a key for SCSS variable names
 * SCSS variables can't start with numbers or contain dots
 */
function toScssVarName(key) {
  return key
    .replace(/\./g, '_') // Replace dots with underscores
    .replace(/^(\d)/, '_$1'); // Prefix leading numbers with underscore
}

function generateScssTokens(primitiveTokens, semanticTokens, allTokens) {
  const lines = [
    '// ============================================',
    '// NXT1 Design Tokens - SCSS Variables',
    '// @generated by build.mjs - DO NOT EDIT MANUALLY',
    '// @source tokens.json/',
    '// ============================================',
    '',
    '// Usage:',
    '//   @use "@nxt1/design-tokens/dist/scss/tokens" as tokens;',
    '//   color: tokens.$nxt1-color-primary;',
    '//   background: var(--nxt1-color-bg-primary);',
    '',
  ];

  // SCSS variables from primitives
  const primitiveFlat = flattenTokens(primitiveTokens);

  lines.push('// PRIMITIVE TOKENS');
  for (const [key, token] of Object.entries(primitiveFlat)) {
    const resolved = resolveReference(token.value, allTokens);
    const scssKey = toScssVarName(key);
    lines.push(`$nxt1-${scssKey}: ${resolved};`);
  }

  lines.push('');
  lines.push('// SEMANTIC TOKENS (CSS variable references for runtime theming)');

  // Generate SCSS vars that reference CSS custom properties
  const darkTokens = semanticTokens.theme?.dark;
  if (darkTokens) {
    const darkFlat = flattenTokens(darkTokens);
    for (const [key] of Object.entries(darkFlat)) {
      let cssKey = sanitizeCssKey(
        key.replace(/^color-background-/, 'color-bg-').replace(/^color-feedback-/, 'color-')
      );
      const scssKey = toScssVarName(cssKey);
      lines.push(`$nxt1-${scssKey}: var(--nxt1-${cssKey});`);
    }
  }

  lines.push('');
  lines.push('// TOKEN MAPS (for programmatic access)');
  lines.push('$nxt1-colors: (');

  // Color map
  const colorTokens = flattenTokens(primitiveTokens.color || {});
  for (const [key, token] of Object.entries(colorTokens)) {
    const resolved = resolveReference(token.value, allTokens);
    lines.push(`  "${key}": ${resolved},`);
  }
  lines.push(');');

  lines.push('');
  lines.push('$nxt1-spacing: (');
  const spacingTokens = flattenTokens(primitiveTokens.spacing || {});
  for (const [key, token] of Object.entries(spacingTokens)) {
    lines.push(`  "${key}": ${token.value},`);
  }
  lines.push(');');

  return lines.join('\n');
}

// ============================================
// JAVASCRIPT GENERATION
// ============================================

function generateJsTokens(primitiveTokens, semanticTokens, componentTokens, allTokens) {
  const primitiveFlat = flattenTokens(primitiveTokens);
  const componentFlat = flattenTokens(componentTokens);

  const lines = [
    '/**',
    ' * @fileoverview NXT1 Design Tokens - JavaScript Module',
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' * @source tokens.json/',
    ' *',
    ' * Usage:',
    ' *   import { colors, spacing, tokens } from "@nxt1/design-tokens";',
    ' *   import tokens from "@nxt1/design-tokens";',
    ' */',
    '',
    '// Primitive color palette',
    'export const colors = {',
  ];

  const colorTokens = flattenTokens(primitiveTokens.color || {});
  for (const [key, token] of Object.entries(colorTokens)) {
    const resolved = resolveReference(token.value, allTokens);
    const jsKey = key.replace(/-/g, '_').replace(/\./g, '_');
    lines.push(`  ${jsKey}: '${resolved}',`);
  }
  lines.push('};');
  lines.push('');

  // Spacing
  lines.push('// Spacing scale');
  lines.push('export const spacing = {');
  const spacingTokens = flattenTokens(primitiveTokens.spacing || {});
  for (const [key, token] of Object.entries(spacingTokens)) {
    const jsKey = key === 'px' ? 'px' : `_${key}`.replace('.', '_');
    lines.push(`  '${key}': '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  // Border radius
  lines.push('// Border radius');
  lines.push('export const borderRadius = {');
  const radiusTokens = flattenTokens(primitiveTokens.borderRadius || {});
  for (const [key, token] of Object.entries(radiusTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  // Typography
  lines.push('// Font families');
  lines.push('export const fontFamily = {');
  const fontFamilyTokens = flattenTokens(primitiveTokens.fontFamily || {});
  for (const [key, token] of Object.entries(fontFamilyTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  lines.push('// Font sizes');
  lines.push('export const fontSize = {');
  const fontSizeTokens = flattenTokens(primitiveTokens.fontSize || {});
  for (const [key, token] of Object.entries(fontSizeTokens)) {
    const jsKey = key.replace(/^(\d)/, '_$1');
    lines.push(`  '${key}': '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  lines.push('// Font weights');
  lines.push('export const fontWeight = {');
  const fontWeightTokens = flattenTokens(primitiveTokens.fontWeight || {});
  for (const [key, token] of Object.entries(fontWeightTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  // Animation
  lines.push('// Animation durations');
  lines.push('export const duration = {');
  const durationTokens = flattenTokens(primitiveTokens.duration || {});
  for (const [key, token] of Object.entries(durationTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  lines.push('// Animation easings');
  lines.push('export const easing = {');
  const easingTokens = flattenTokens(primitiveTokens.easing || {});
  for (const [key, token] of Object.entries(easingTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  // Z-index
  lines.push('// Z-index layers');
  lines.push('export const zIndex = {');
  const zIndexTokens = flattenTokens(primitiveTokens.zIndex || {});
  for (const [key, token] of Object.entries(zIndexTokens)) {
    lines.push(`  ${key}: ${token.value},`);
  }
  lines.push('};');
  lines.push('');

  // Breakpoints
  lines.push('// Breakpoints');
  lines.push('export const breakpoints = {');
  const breakpointTokens = flattenTokens(primitiveTokens.breakpoint || {});
  for (const [key, token] of Object.entries(breakpointTokens)) {
    lines.push(`  ${key}: '${token.value}',`);
  }
  lines.push('};');
  lines.push('');

  // Components
  lines.push('// Component tokens');
  lines.push('export const components = {');
  const compTokens = flattenTokens(componentTokens.component || {});
  for (const [key, token] of Object.entries(compTokens)) {
    const resolved = resolveReference(token.value, allTokens);
    lines.push(`  '${key}': '${resolved}',`);
  }
  lines.push('};');
  lines.push('');

  // Default export
  lines.push('// Combined default export');
  lines.push('const tokens = {');
  lines.push('  colors,');
  lines.push('  spacing,');
  lines.push('  borderRadius,');
  lines.push('  fontFamily,');
  lines.push('  fontSize,');
  lines.push('  fontWeight,');
  lines.push('  duration,');
  lines.push('  easing,');
  lines.push('  zIndex,');
  lines.push('  breakpoints,');
  lines.push('  components,');
  lines.push('};');
  lines.push('');
  lines.push('export default tokens;');

  return lines.join('\n');
}

function generateTypeDefinitions(primitiveTokens, componentTokens) {
  const lines = [
    '/**',
    ' * @fileoverview NXT1 Design Tokens - TypeScript Definitions',
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' */',
    '',
    'declare const colors: {',
  ];

  const colorTokens = flattenTokens(primitiveTokens.color || {});
  for (const key of Object.keys(colorTokens)) {
    const tsKey = key.replace(/-/g, '_').replace(/\./g, '_');
    lines.push(`  readonly ${tsKey}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const spacing: {');
  const spacingTokens = flattenTokens(primitiveTokens.spacing || {});
  for (const key of Object.keys(spacingTokens)) {
    lines.push(`  readonly '${key}': string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const borderRadius: {');
  const radiusTokens = flattenTokens(primitiveTokens.borderRadius || {});
  for (const key of Object.keys(radiusTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const fontFamily: {');
  const fontFamilyTokens = flattenTokens(primitiveTokens.fontFamily || {});
  for (const key of Object.keys(fontFamilyTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const fontSize: {');
  const fontSizeTokens = flattenTokens(primitiveTokens.fontSize || {});
  for (const key of Object.keys(fontSizeTokens)) {
    lines.push(`  readonly '${key}': string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const fontWeight: {');
  const fontWeightTokens = flattenTokens(primitiveTokens.fontWeight || {});
  for (const key of Object.keys(fontWeightTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const duration: {');
  const durationTokens = flattenTokens(primitiveTokens.duration || {});
  for (const key of Object.keys(durationTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const easing: {');
  const easingTokens = flattenTokens(primitiveTokens.easing || {});
  for (const key of Object.keys(easingTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const zIndex: {');
  const zIndexTokens = flattenTokens(primitiveTokens.zIndex || {});
  for (const key of Object.keys(zIndexTokens)) {
    lines.push(`  readonly ${key}: number;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const breakpoints: {');
  const breakpointTokens = flattenTokens(primitiveTokens.breakpoint || {});
  for (const key of Object.keys(breakpointTokens)) {
    lines.push(`  readonly ${key}: string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('declare const components: {');
  const compTokens = flattenTokens(componentTokens.component || {});
  for (const key of Object.keys(compTokens)) {
    lines.push(`  readonly '${key}': string;`);
  }
  lines.push('};');
  lines.push('');

  lines.push('interface NXT1Tokens {');
  lines.push('  colors: typeof colors;');
  lines.push('  spacing: typeof spacing;');
  lines.push('  borderRadius: typeof borderRadius;');
  lines.push('  fontFamily: typeof fontFamily;');
  lines.push('  fontSize: typeof fontSize;');
  lines.push('  fontWeight: typeof fontWeight;');
  lines.push('  duration: typeof duration;');
  lines.push('  easing: typeof easing;');
  lines.push('  zIndex: typeof zIndex;');
  lines.push('  breakpoints: typeof breakpoints;');
  lines.push('  components: typeof components;');
  lines.push('}');
  lines.push('');
  lines.push('declare const tokens: NXT1Tokens;');
  lines.push('');
  lines.push('export {');
  lines.push('  colors,');
  lines.push('  spacing,');
  lines.push('  borderRadius,');
  lines.push('  fontFamily,');
  lines.push('  fontSize,');
  lines.push('  fontWeight,');
  lines.push('  duration,');
  lines.push('  easing,');
  lines.push('  zIndex,');
  lines.push('  breakpoints,');
  lines.push('  components,');
  lines.push('};');
  lines.push('');
  lines.push('export default tokens;');

  return lines.join('\n');
}

// ============================================
// JSON GENERATION (Resolved)
// ============================================

function generateResolvedJson(primitiveTokens, semanticTokens, componentTokens, allTokens) {
  const resolved = {
    $schema: 'https://design-tokens.github.io/community-group/format/',
    $description: 'NXT1 Design Tokens - Resolved values (generated)',
    primitive: {},
    semantic: {},
    component: {},
  };

  // Resolve primitives
  const primitiveFlat = flattenTokens(primitiveTokens);
  for (const [key, token] of Object.entries(primitiveFlat)) {
    resolved.primitive[key] = {
      value: resolveReference(token.value, allTokens),
      type: token.type,
    };
  }

  // Resolve semantic (dark theme)
  if (semanticTokens.theme?.dark) {
    const darkFlat = flattenTokens(semanticTokens.theme.dark);
    resolved.semantic.dark = {};
    for (const [key, token] of Object.entries(darkFlat)) {
      resolved.semantic.dark[key] = {
        value: resolveReference(token.value, allTokens),
        type: token.type,
      };
    }
  }

  // Resolve semantic (light theme)
  if (semanticTokens.theme?.light) {
    const lightFlat = flattenTokens(semanticTokens.theme.light);
    resolved.semantic.light = {};
    for (const [key, token] of Object.entries(lightFlat)) {
      resolved.semantic.light[key] = {
        value: resolveReference(token.value, allTokens),
        type: token.type,
      };
    }
  }

  // Resolve components
  if (componentTokens.component) {
    const componentFlat = flattenTokens(componentTokens);
    for (const [key, token] of Object.entries(componentFlat)) {
      resolved.component[key] = {
        value: resolveReference(token.value, allTokens),
        type: token.type,
      };
    }
  }

  return JSON.stringify(resolved, null, 2);
}

// ============================================
// IONIC SCSS GENERATION
// ============================================

const IONIC_DIR = join(__dirname, 'ionic');

/**
 * Generate _colors.scss for Ionic theme from tokens.json
 */
function generateIonicColors(primitiveTokens) {
  const lines = [
    '/**',
    ' * @fileoverview NXT1 Color Variables for Ionic Theme',
    ' * @module @nxt1/design-tokens/ionic',
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' *',
    ' * SCSS variables for Ionic theme integration.',
    ' * Source: tokens.json/primitive.tokens.json',
    ' */',
    '',
  ];

  const colorMappings = [
    { source: 'brand.volt', target: 'primary', label: 'PRIMARY COLORS - Neon Volt Green' },
    { source: 'brand.gold', target: 'secondary', label: 'SECONDARY COLORS - Gold' },
    { source: 'brand.lime', target: 'accent', label: 'ACCENT COLORS - Lime' },
    { source: 'neutral.dark', target: 'dark', label: 'NEUTRAL DARK (Dark Theme Base)' },
    { source: 'neutral.light', target: 'light', label: 'NEUTRAL LIGHT (Light Theme Base)' },
  ];

  for (const mapping of colorMappings) {
    lines.push('// ============================================');
    lines.push(`// ${mapping.label}`);
    lines.push('// ============================================');

    // Navigate to the source path in tokens
    const pathParts = mapping.source.split('.');
    let colorScale = primitiveTokens.color;
    for (const part of pathParts) {
      colorScale = colorScale?.[part];
    }

    if (colorScale) {
      // Sort keys numerically
      const sortedKeys = Object.keys(colorScale)
        .filter((k) => !k.startsWith('$'))
        .sort((a, b) => parseInt(a) - parseInt(b));

      for (const shade of sortedKeys) {
        const token = colorScale[shade];
        if (token?.$value) {
          lines.push(`$nxt1-${mapping.target}-${shade}: ${token.$value};`);
        }
      }
    }
    lines.push('');
  }

  // Add semantic colors
  lines.push('// ============================================');
  lines.push('// SEMANTIC COLORS');
  lines.push('// ============================================');

  const semanticColors = primitiveTokens.color?.semantic;
  if (semanticColors) {
    for (const [name, scale] of Object.entries(semanticColors)) {
      if (name.startsWith('$')) continue;
      // Use the 500 shade as the default semantic color
      const defaultValue = scale?.['500']?.$value || scale?.['400']?.$value;
      if (defaultValue) {
        lines.push(`$nxt1-${name}: ${defaultValue};`);
      }
    }
  }
  lines.push('');

  return lines.join('\n');
}

/**
 * Generate _typography.scss for Ionic theme from tokens.json
 */
function generateIonicTypography(primitiveTokens) {
  const lines = [
    '/**',
    ' * @fileoverview NXT1 Typography Variables for Ionic Theme',
    ' * @module @nxt1/design-tokens/ionic',
    ' * @generated by build.mjs - DO NOT EDIT MANUALLY',
    ' *',
    ' * SCSS typography variables for Ionic theme integration.',
    ' * Source: tokens.json/primitive.tokens.json',
    ' */',
    '',
  ];

  // Font families
  lines.push('// ============================================');
  lines.push('// FONT FAMILIES');
  lines.push('// ============================================');
  const fontFamilies = primitiveTokens.fontFamily;
  if (fontFamilies) {
    for (const [name, token] of Object.entries(fontFamilies)) {
      if (name.startsWith('$')) continue;
      if (token?.$value) {
        lines.push(`$nxt1-font-family-${name}: ${token.$value};`);
      }
    }
  }
  lines.push('');

  // Font sizes
  lines.push('// ============================================');
  lines.push('// FONT SIZES');
  lines.push('// ============================================');
  const fontSizes = primitiveTokens.fontSize;
  if (fontSizes) {
    const sizeOrder = [
      '2xs',
      'xs',
      'sm',
      'base',
      'md',
      'lg',
      'xl',
      '2xl',
      '3xl',
      '4xl',
      '5xl',
      '6xl',
    ];
    for (const size of sizeOrder) {
      const token = fontSizes[size];
      if (token?.$value) {
        lines.push(`$nxt1-font-size-${size}: ${token.$value};`);
      }
    }
  }
  lines.push('');

  // Font weights
  lines.push('// ============================================');
  lines.push('// FONT WEIGHTS');
  lines.push('// ============================================');
  const fontWeights = primitiveTokens.fontWeight;
  if (fontWeights) {
    const weightOrder = ['light', 'regular', 'medium', 'semibold', 'bold'];
    for (const weight of weightOrder) {
      const token = fontWeights[weight];
      if (token?.$value) {
        lines.push(`$nxt1-font-weight-${weight}: ${token.$value};`);
      }
    }
  }
  lines.push('');

  // Line heights
  lines.push('// ============================================');
  lines.push('// LINE HEIGHTS');
  lines.push('// ============================================');
  const lineHeights = primitiveTokens.lineHeight;
  if (lineHeights) {
    const lhOrder = ['none', 'tight', 'snug', 'normal', 'relaxed', 'loose'];
    for (const lh of lhOrder) {
      const token = lineHeights[lh];
      if (token?.$value) {
        lines.push(`$nxt1-line-height-${lh}: ${token.$value};`);
      }
    }
  }
  lines.push('');

  // Letter spacing
  lines.push('// ============================================');
  lines.push('// LETTER SPACING');
  lines.push('// ============================================');
  const letterSpacing = primitiveTokens.letterSpacing;
  if (letterSpacing) {
    const lsOrder = ['tighter', 'tight', 'normal', 'wide', 'wider', 'widest'];
    for (const ls of lsOrder) {
      const token = letterSpacing[ls];
      if (token?.$value) {
        lines.push(`$nxt1-letter-spacing-${ls}: ${token.$value};`);
      }
    }
  }
  lines.push('');

  return lines.join('\n');
}

// ============================================
// MAIN BUILD FUNCTION
// ============================================

function ensureDir(dir) {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function cleanDist() {
  if (existsSync(DIST_DIR)) {
    rmSync(DIST_DIR, { recursive: true });
  }
}

function build() {
  console.log('🎨 NXT1 Design Token Build');
  console.log('==========================\n');

  // Clean previous build
  console.log('🧹 Cleaning dist/...');
  cleanDist();

  // Create directories
  ensureDir(join(DIST_DIR, 'css'));
  ensureDir(join(DIST_DIR, 'css/themes'));
  ensureDir(join(DIST_DIR, 'scss'));
  ensureDir(join(DIST_DIR, 'js'));
  ensureDir(join(DIST_DIR, 'json'));

  // Load tokens
  console.log('📦 Loading tokens from tokens.json/...');
  const { primitiveTokens, semanticTokens, componentTokens } = loadTokens();

  // Merge all tokens for reference resolution
  const allTokens = { ...primitiveTokens, ...semanticTokens, ...componentTokens };

  // Generate CSS
  console.log('🎨 Generating CSS...');
  const combinedCss = generateCombinedCss(primitiveTokens, semanticTokens, allTokens);
  writeFileSync(join(DIST_DIR, 'css/tokens.css'), combinedCss);
  console.log('   ✓ dist/css/tokens.css');

  // Generate individual theme files
  if (semanticTokens.theme?.dark) {
    const darkCss = generateThemeCss(semanticTokens.theme.dark, 'dark', allTokens);
    writeFileSync(join(DIST_DIR, 'css/themes/dark.css'), darkCss);
    console.log('   ✓ dist/css/themes/dark.css');
  }

  if (semanticTokens.theme?.light) {
    const lightCss = generateThemeCss(semanticTokens.theme.light, 'light', allTokens);
    writeFileSync(join(DIST_DIR, 'css/themes/light.css'), lightCss);
    console.log('   ✓ dist/css/themes/light.css');
  }

  // Generate SCSS
  console.log('📝 Generating SCSS...');
  const scssTokens = generateScssTokens(primitiveTokens, semanticTokens, allTokens);
  writeFileSync(join(DIST_DIR, 'scss/_tokens.scss'), scssTokens);
  console.log('   ✓ dist/scss/_tokens.scss');

  // Generate JS
  console.log('⚡ Generating JavaScript...');
  const jsTokens = generateJsTokens(primitiveTokens, semanticTokens, componentTokens, allTokens);
  writeFileSync(join(DIST_DIR, 'js/tokens.mjs'), jsTokens);
  console.log('   ✓ dist/js/tokens.mjs');

  // Generate TypeScript definitions
  const dtsTokens = generateTypeDefinitions(primitiveTokens, componentTokens);
  writeFileSync(join(DIST_DIR, 'js/tokens.d.ts'), dtsTokens);
  console.log('   ✓ dist/js/tokens.d.ts');

  // Generate resolved JSON
  console.log('📋 Generating resolved JSON...');
  const resolvedJson = generateResolvedJson(
    primitiveTokens,
    semanticTokens,
    componentTokens,
    allTokens
  );
  writeFileSync(join(DIST_DIR, 'json/resolved.json'), resolvedJson);
  console.log('   ✓ dist/json/resolved.json');

  // Generate Ionic SCSS files
  console.log('🎨 Generating Ionic SCSS...');
  ensureDir(IONIC_DIR);

  const ionicColors = generateIonicColors(primitiveTokens);
  writeFileSync(join(IONIC_DIR, '_colors.scss'), ionicColors);
  console.log('   ✓ ionic/_colors.scss');

  const ionicTypography = generateIonicTypography(primitiveTokens);
  writeFileSync(join(IONIC_DIR, '_typography.scss'), ionicTypography);
  console.log('   ✓ ionic/_typography.scss');

  console.log('\n✅ Build complete!\n');
  console.log('Generated files:');
  console.log('  CSS:   dist/css/tokens.css (combined)');
  console.log('         dist/css/themes/dark.css');
  console.log('         dist/css/themes/light.css');
  console.log('  SCSS:  dist/scss/_tokens.scss');
  console.log('  Ionic: ionic/_colors.scss');
  console.log('         ionic/_typography.scss');
  console.log('  JS:    dist/js/tokens.mjs');
  console.log('         dist/js/tokens.d.ts');
  console.log('  JSON:  dist/json/resolved.json\n');
}

// Run build
build();
