/**
 * @fileoverview Export Service — PDF & CSV Document Generation
 * @module @nxt1/backend/modules/agent/services
 *
 * Centralised service for generating PDF and CSV documents from structured data.
 * Used by both the Agent X DynamicExportTool and the REST analytics/export endpoint.
 *
 * Design decisions:
 * - Uses `pdfmake` for PDF generation (declarative JSON → PDF, no coordinate math).
 * - Uses `csv-stringify/sync` for CSV generation (fast, synchronous, Buffer-native).
 * - All output is returned as a `Buffer` — callers handle storage/upload.
 * - CSVs include a UTF-8 BOM so they open correctly in Excel/Sheets/Numbers.
 * - PDFs include NXT1 branding header, page numbers, and professional formatting.
 *
 * Architecture:
 *   Caller (Tool / Route)
 *        ↓
 *   ExportService.generatePdf(opts)  → Buffer (PDF)
 *   ExportService.generateCsv(opts)  → Buffer (CSV)
 *        ↓
 *   Caller uploads Buffer → Firebase Storage → signed URL
 */

import pdfmakeModule from 'pdfmake';
import { stringify } from 'csv-stringify/sync';
import type { Content, TableCell } from 'pdfmake';
import { resolve, dirname } from 'node:path';
import { createRequire } from 'node:module';

// pdfmake 0.3.x is CJS — handle ESM interop (singleton API)
const pdfmake =
  (pdfmakeModule as unknown as { default?: typeof pdfmakeModule }).default ?? pdfmakeModule;

// Extract TDocumentDefinitions from createPdf signature (not re-exported by @types/pdfmake root)
type TDocumentDefinitions = Parameters<typeof pdfmakeModule.createPdf>[0];

// Resolve font paths relative to the pdfmake package (works from any cwd)
const _require = createRequire(import.meta.url);
const pdfmakePkgDir = dirname(_require.resolve('pdfmake/package.json'));
const fontsDir = resolve(pdfmakePkgDir, 'build/fonts/Roboto');

// Register fonts once at module load
pdfmake.addFonts({
  Roboto: {
    normal: resolve(fontsDir, 'Roboto-Regular.ttf'),
    bold: resolve(fontsDir, 'Roboto-Medium.ttf'),
    italics: resolve(fontsDir, 'Roboto-Italic.ttf'),
    bolditalics: resolve(fontsDir, 'Roboto-MediumItalic.ttf'),
  },
});

// Restrict external URL access (security best practice — deny all external URLs)
// setUrlAccessPolicy exists in pdfmake 0.3.x but is missing from @types/pdfmake
(
  pdfmake as unknown as { setUrlAccessPolicy: (fn: (url: string) => boolean) => void }
).setUrlAccessPolicy(() => false);

// ─── Public Types ──────────────────────────────────────────────────────────

/** A single column definition for tabular exports. */
export interface ExportColumn {
  /** Machine key (used for CSV header row and data lookup). */
  readonly key: string;
  /** Human-readable label (used for PDF table headers and CSV header row). */
  readonly label: string;
  /** Optional column width for PDF ('auto' | '*' | number). Defaults to '*'. */
  readonly width?: string | number;
}

/** Row data — each row is an array of cell values matching column order. */
export type ExportRow = readonly (string | number | boolean | null | undefined)[];

/** Options for CSV generation. */
export interface CsvExportOptions {
  /** Column definitions (order determines output column order). */
  readonly columns: readonly ExportColumn[];
  /** Row data — each inner array matches column order. */
  readonly rows: readonly ExportRow[];
}

/** Options for PDF generation. */
export interface PdfExportOptions {
  /** Document title (rendered as the main heading). */
  readonly title: string;
  /** Optional subtitle or description below the title. */
  readonly description?: string;
  /** When true, render a data table. Requires columns + rows. */
  readonly includeTable?: boolean;
  /** Column definitions for the table. */
  readonly columns?: readonly ExportColumn[];
  /** Row data for the table. */
  readonly rows?: readonly ExportRow[];
  /** Optional free-form body paragraphs rendered before the table. */
  readonly bodyParagraphs?: readonly string[];
  /** Optional list of bullet points. */
  readonly bulletPoints?: readonly string[];
  /** Footer text (defaults to 'Generated by NXT1 — nxt1sports.com'). */
  readonly footerText?: string;
  /**
   * Visual theme for the PDF.
   * - `'dark'` (default) — near-black page with white text and Volt green accent.
   * - `'light'` — white page with dark text and Volt green accent.
   */
  readonly theme?: 'dark' | 'light';
}

// ─── NXT1 Brand Colours ────────────────────────────────────────────────────

/** NXT1 Volt neon green — the primary accent in every theme */
const VOLT = '#CCFF00';
/** Text printed ON a volt background — always black (design token: text-onPrimary) */
const VOLT_TEXT = '#000000';

/** Internal palette type — used by generatePdf and buildPdfContent. */
interface PdfPalette {
  readonly background: string;
  readonly surface: string;
  readonly surfaceAlt: string;
  readonly border: string;
  readonly text: string;
  readonly textMuted: string;
  readonly primary: string;
  readonly onPrimary: string;
}

/** Dark theme (default) — near-black page, white text */
const DARK_PALETTE = {
  background: '#0A0A0A', // bg-primary
  surface: '#161616', // surface-100 (odd rows)
  surfaceAlt: '#1A1A1A', // surface-200 (even rows)
  border: '#2A2A2A', // surface-400
  text: '#FFFFFF', // text-primary
  textMuted: '#B3B3B3', // ≈ rgba(255,255,255,0.7)
  primary: VOLT,
  onPrimary: VOLT_TEXT,
} as const;

/** Light theme — white page, dark text, same Volt green accent */
const LIGHT_PALETTE = {
  background: '#FFFFFF', // white page
  surface: '#F8F8F8', // near-white card surface (odd rows)
  surfaceAlt: '#F0F0F0', // light grey alternate (even rows)
  border: '#DADADA', // subtle grey border
  text: '#0A0A0A', // near-black body text (text-inverse)
  textMuted: '#555555', // mid-grey muted text
  primary: VOLT,
  onPrimary: VOLT_TEXT,
} as const;

// ─── Service ───────────────────────────────────────────────────────────────

export class ExportService {
  // ── CSV ────────────────────────────────────────────────────────────────

  /**
   * Generate a CSV buffer from structured column/row data.
   * Includes a UTF-8 BOM for Excel/Numbers/Sheets compatibility.
   */
  generateCsv(opts: CsvExportOptions): Buffer {
    const { columns, rows } = opts;

    // Build header row from column labels
    const header = columns.map((c) => c.label);

    // Stringify rows (csv-stringify expects array-of-arrays)
    const csvString = stringify([header, ...rows], {
      quoted: true,
      quoted_empty: true,
    });

    // Prepend UTF-8 BOM so Excel auto-detects encoding
    const bom = '\uFEFF';
    return Buffer.from(bom + csvString, 'utf-8');
  }

  // ── PDF ────────────────────────────────────────────────────────────────

  /**
   * Generate a PDF buffer from structured options.
   * Returns a Promise because pdfmake streams the document.
   */
  async generatePdf(opts: PdfExportOptions): Promise<Buffer> {
    const palette: PdfPalette = opts.theme === 'light' ? LIGHT_PALETTE : DARK_PALETTE;
    const content = this.buildPdfContent(opts, palette);

    const docDefinition: TDocumentDefinitions = {
      pageSize: 'LETTER',
      pageMargins: [40, 80, 40, 60],
      background: {
        canvas: [{ type: 'rect', x: 0, y: 0, w: 612, h: 792, color: palette.background }],
      },

      // ── Header ──
      header: {
        columns: [
          {
            text: 'NXT1',
            fontSize: 14,
            bold: true,
            color: palette.primary,
            margin: [40, 20, 0, 0],
          },
          {
            text: new Date().toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            }),
            fontSize: 9,
            color: palette.textMuted,
            alignment: 'right',
            margin: [0, 24, 40, 0],
          },
        ],
      },

      // ── Footer with page numbers ──
      footer: (currentPage: number, pageCount: number) => ({
        columns: [
          {
            text: opts.footerText ?? 'Generated by NXT1 — nxt1sports.com',
            fontSize: 8,
            color: palette.textMuted,
            margin: [40, 20, 0, 0],
          },
          {
            text: `Page ${currentPage} of ${pageCount}`,
            fontSize: 8,
            color: palette.textMuted,
            alignment: 'right',
            margin: [0, 20, 40, 0],
          },
        ],
      }),

      content,

      defaultStyle: {
        font: 'Roboto',
        fontSize: 10,
        color: palette.text,
      },

      styles: {
        title: { fontSize: 20, bold: true, color: palette.text, margin: [0, 0, 0, 4] },
        description: { fontSize: 11, color: palette.textMuted, margin: [0, 0, 0, 16] },
        sectionBody: { fontSize: 10, color: palette.text, lineHeight: 1.4, margin: [0, 0, 0, 8] },
        tableHeader: {
          fontSize: 9,
          bold: true,
          color: palette.onPrimary,
          fillColor: palette.primary,
          margin: [4, 6, 4, 6],
        },
        tableCell: { fontSize: 9, color: palette.text, margin: [4, 4, 4, 4] },
      },
    };

    return this.renderPdfToBuffer(docDefinition);
  }

  // ── Private Helpers ────────────────────────────────────────────────────

  private buildPdfContent(opts: PdfExportOptions, palette: PdfPalette): Content[] {
    const content: Content[] = [];

    // Title
    content.push({ text: opts.title, style: 'title' });

    // Description
    if (opts.description) {
      content.push({ text: opts.description, style: 'description' });
    }

    // Horizontal rule
    content.push({
      canvas: [
        { type: 'line', x1: 0, y1: 0, x2: 535, y2: 0, lineWidth: 1, lineColor: palette.border },
      ],
      margin: [0, 0, 0, 12] as [number, number, number, number],
    });

    // Body paragraphs
    if (opts.bodyParagraphs?.length) {
      for (const para of opts.bodyParagraphs) {
        content.push({ text: para, style: 'sectionBody' });
      }
    }

    // Bullet points
    if (opts.bulletPoints?.length) {
      content.push({
        ul: opts.bulletPoints.map((bp) => ({
          text: bp,
          margin: [0, 2, 0, 2] as [number, number, number, number],
        })),
        margin: [0, 0, 0, 12] as [number, number, number, number],
      });
    }

    // Data table
    if (opts.includeTable && opts.columns?.length && opts.rows?.length) {
      const widths = opts.columns.map((c) => c.width ?? '*');
      const headerRow: TableCell[] = opts.columns.map((c) => ({
        text: c.label,
        style: 'tableHeader',
      }));
      const bodyRows: TableCell[][] = opts.rows.map((row) =>
        row.map((cell) => ({
          text: cell == null ? '' : String(cell),
          style: 'tableCell',
        }))
      );

      content.push({
        table: {
          headerRows: 1,
          widths,
          body: [headerRow, ...bodyRows],
        },
        layout: {
          hLineWidth: () => 0.5,
          vLineWidth: () => 0.5,
          hLineColor: () => palette.border,
          vLineColor: () => palette.border,
          fillColor: (rowIndex: number) =>
            rowIndex === 0
              ? palette.primary
              : rowIndex % 2 === 0
                ? palette.surfaceAlt
                : palette.surface,
        },
      });
    }

    return content;
  }

  private async renderPdfToBuffer(docDefinition: TDocumentDefinitions): Promise<Buffer> {
    const pdf = pdfmake.createPdf(docDefinition);
    return pdf.getBuffer();
  }
}
