/**
 * @fileoverview Gamma API Client
 * @module @nxt1/backend/modules/agent/services
 *
 * Generates branded PPTX and PDF exports directly through Gamma's public API.
 * NXT1 remains the artifact owner: callers upload returned buffers to
 * thread-scoped Firebase Storage and retain all Files linkage.
 */

import { AgentEngineError } from '../exceptions/agent-engine.error.js';
import { getRuntimeEnvironment } from '../../../config/runtime-environment.js';
import { logger } from '../../../utils/logger.js';

const DEFAULT_BASE_URL = 'https://public-api.gamma.app/v1.0/';
const DEFAULT_TIMEOUT_MS = 180_000;
const DEFAULT_MAX_RESPONSE_BYTES = 100 * 1024 * 1024;
const POLL_DELAYS_MS = [1_500, 2_500, 4_000, 5_000] as const;
const DEFAULT_PROFESSIONAL_THEME_ID = 'ash';
const DEFAULT_EXPORT_FOOTER_TEXT = 'Generated by NXT1 - nxt1sports.com';

interface GammaColumn {
  readonly label: string;
}

type GammaRow = readonly (string | number | boolean | null | undefined)[];

export interface GammaStructuredSection {
  readonly title?: string;
  readonly description?: string;
  readonly bodyParagraphs?: readonly string[];
  readonly bulletPoints?: readonly string[];
  readonly columns?: readonly GammaColumn[];
  readonly rows?: readonly GammaRow[];
  readonly imageUrls?: readonly string[];
}

interface GammaExportInputBase {
  readonly title: string;
  readonly description?: string;
  readonly footerText?: string;
  readonly templateGammaId?: string;
  readonly themeId?: string;
  readonly additionalInstructions?: string;
  readonly columns?: readonly GammaColumn[];
  readonly rows?: readonly GammaRow[];
  readonly sections?: readonly GammaStructuredSection[];
  readonly bodyParagraphs?: readonly string[];
  readonly bulletPoints?: readonly string[];
  readonly imageUrls?: readonly string[];
  readonly organizationName?: string;
  readonly brandPrimaryColor?: string;
  readonly brandSecondaryColor?: string;
  readonly brandBackgroundMode?: 'auto' | 'neutral' | 'balanced' | 'alternating' | 'bold';
  readonly logoUrl?: string;
  readonly pageOrientation?: 'portrait' | 'landscape';
  readonly pageSize?: 'LETTER' | 'LEGAL' | 'TABLOID';
}

export type GammaPptxInput = GammaExportInputBase;

export interface GammaPdfInput extends GammaExportInputBase {
  readonly format?: 'presentation' | 'document';
}

export interface GammaClientConfig {
  readonly enabled?: boolean;
  readonly apiKey?: string;
  readonly baseUrl?: string;
  readonly defaultThemeId?: string;
  readonly timeoutMs?: number;
  readonly maxResponseBytes?: number;
  readonly fetchImpl?: typeof fetch;
}

export interface GammaPresentationGenerator {
  readonly isEnabled: boolean;
  generatePptx(input: GammaPptxInput): Promise<Buffer>;
  generatePdf(input: GammaPdfInput): Promise<Buffer>;
}

interface GammaCreateResponse {
  readonly generationId?: unknown;
}

interface GammaStatusResponse {
  readonly status?: unknown;
  readonly exportUrl?: unknown;
  readonly error?: unknown;
}

export class GammaClient implements GammaPresentationGenerator {
  private readonly enabled: boolean;
  private readonly apiKey: string | null;
  private readonly baseUrl: URL;
  private readonly defaultThemeId: string | null;
  private readonly timeoutMs: number;
  private readonly maxResponseBytes: number;
  private readonly fetchImpl: typeof fetch;

  constructor(config: GammaClientConfig = {}) {
    const environment = getRuntimeEnvironment();
    this.enabled =
      config.enabled ?? parseBoolean(resolveEnvironmentValue(environment, 'GAMMA_ENABLED'));
    this.apiKey = normalizeOptionalString(
      config.apiKey ?? resolveEnvironmentValue(environment, 'GAMMA_API_KEY')
    );
    this.baseUrl = normalizeBaseUrl(
      config.baseUrl ?? resolveEnvironmentValue(environment, 'GAMMA_BASE_URL') ?? DEFAULT_BASE_URL
    );
    this.defaultThemeId = normalizeOptionalString(
      config.defaultThemeId ?? resolveEnvironmentValue(environment, 'GAMMA_DEFAULT_THEME_ID')
    );
    this.timeoutMs = normalizePositiveInteger(
      config.timeoutMs ?? resolveEnvironmentValue(environment, 'GAMMA_TIMEOUT_MS'),
      DEFAULT_TIMEOUT_MS
    );
    this.maxResponseBytes = normalizePositiveInteger(
      config.maxResponseBytes ?? resolveEnvironmentValue(environment, 'GAMMA_MAX_RESPONSE_BYTES'),
      DEFAULT_MAX_RESPONSE_BYTES
    );
    this.fetchImpl = config.fetchImpl ?? fetch;
  }

  get isEnabled(): boolean {
    return this.enabled;
  }

  async generatePptx(input: GammaPptxInput): Promise<Buffer> {
    return this.generateExport({
      exportAs: 'pptx',
      format: 'presentation',
      input,
    });
  }

  async generatePdf(input: GammaPdfInput): Promise<Buffer> {
    return this.generateExport({
      exportAs: 'pdf',
      format: input.format ?? 'document',
      input: {
        ...input,
        footerText: input.footerText ?? DEFAULT_EXPORT_FOOTER_TEXT,
      },
    });
  }

  private async generateExport(options: {
    readonly exportAs: 'pptx' | 'pdf';
    readonly format: 'presentation' | 'document';
    readonly input: GammaExportInputBase;
  }): Promise<Buffer> {
    this.assertConfigured();

    const startedAt = Date.now();
    const generationId = await this.startGeneration(options);
    const exportUrl = await this.pollForExportUrl(generationId, startedAt);
    const artifact = await this.downloadArtifact(exportUrl, options.exportAs);

    logger.info('[Gamma] export generated', {
      exportAs: options.exportAs,
      durationMs: Date.now() - startedAt,
      sizeBytes: artifact.length,
      title: options.input.title,
    });

    return artifact;
  }

  private assertConfigured(): void {
    if (!this.enabled) {
      throw new AgentEngineError(
        'GAMMA_CONFIG_MISSING_API_KEY',
        'Gamma generation is disabled. Set GAMMA_ENABLED=true to enable it.'
      );
    }

    if (!this.apiKey) {
      throw new AgentEngineError(
        'GAMMA_CONFIG_MISSING_API_KEY',
        'GAMMA_API_KEY is required when Gamma generation is enabled.'
      );
    }
  }

  private async startGeneration(options: {
    readonly exportAs: 'pptx' | 'pdf';
    readonly format: 'presentation' | 'document';
    readonly input: GammaExportInputBase;
  }): Promise<string> {
    const url = options.input.templateGammaId
      ? new URL('generations/from-template', this.baseUrl)
      : new URL('generations', this.baseUrl);
    const body = options.input.templateGammaId
      ? this.buildTemplateRequestBody(options)
      : this.buildGenerationRequestBody(options);

    let response: Response;
    try {
      response = await this.fetchImpl(url, {
        method: 'POST',
        headers: this.buildApiHeaders(),
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(this.timeoutMs),
      });
    } catch (error) {
      throw new AgentEngineError('GAMMA_REQUEST_FAILED', 'Gamma generation request failed.', {
        cause: error,
      });
    }

    if (!response.ok) {
      throw new AgentEngineError(
        'GAMMA_REQUEST_FAILED',
        `Gamma generation request failed with HTTP ${response.status}.`,
        { metadata: { status: response.status } }
      );
    }

    const payload = await this.parseJson<GammaCreateResponse>(response, 'GAMMA_INVALID_RESPONSE');
    if (typeof payload.generationId !== 'string' || payload.generationId.trim().length === 0) {
      throw new AgentEngineError(
        'GAMMA_INVALID_RESPONSE',
        'Gamma generation response did not include a generationId.'
      );
    }

    return payload.generationId;
  }

  private async pollForExportUrl(generationId: string, startedAt: number): Promise<string> {
    let attempt = 0;

    while (Date.now() - startedAt < this.timeoutMs) {
      let response: Response;
      try {
        response = await this.fetchImpl(new URL(`generations/${generationId}`, this.baseUrl), {
          headers: this.buildApiHeaders(),
          signal: AbortSignal.timeout(this.timeoutMs),
        });
      } catch (error) {
        throw new AgentEngineError('GAMMA_REQUEST_FAILED', 'Gamma status request failed.', {
          cause: error,
        });
      }

      if (!response.ok) {
        throw new AgentEngineError(
          'GAMMA_REQUEST_FAILED',
          `Gamma status request failed with HTTP ${response.status}.`,
          { metadata: { status: response.status } }
        );
      }

      const payload = await this.parseJson<GammaStatusResponse>(response, 'GAMMA_INVALID_RESPONSE');
      const status = typeof payload.status === 'string' ? payload.status.toLowerCase() : undefined;

      if (status === 'completed') {
        if (typeof payload.exportUrl !== 'string' || payload.exportUrl.trim().length === 0) {
          throw new AgentEngineError(
            'GAMMA_INVALID_RESPONSE',
            'Gamma completed the generation but did not return an exportUrl.'
          );
        }
        return payload.exportUrl;
      }

      if (status === 'failed') {
        throw new AgentEngineError(
          'GAMMA_GENERATION_FAILED',
          typeof payload.error === 'string' && payload.error.trim().length > 0
            ? payload.error
            : 'Gamma reported a failed generation.'
        );
      }

      const delayMs = POLL_DELAYS_MS[Math.min(attempt, POLL_DELAYS_MS.length - 1)] ?? 5_000;
      await wait(delayMs);
      attempt += 1;
    }

    throw new AgentEngineError(
      'GAMMA_GENERATION_FAILED',
      'Gamma generation timed out before an export URL became available.'
    );
  }

  private async downloadArtifact(exportUrl: string, exportAs: 'pptx' | 'pdf'): Promise<Buffer> {
    let url: URL;
    try {
      url = new URL(exportUrl);
    } catch (error) {
      throw new AgentEngineError('GAMMA_INVALID_RESPONSE', 'Gamma returned an invalid exportUrl.', {
        cause: error,
      });
    }

    let response: Response;
    try {
      response = await this.fetchImpl(url, {
        headers: {
          accept:
            exportAs === 'pptx'
              ? 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
              : 'application/pdf',
        },
        signal: AbortSignal.timeout(this.timeoutMs),
      });
    } catch (error) {
      throw new AgentEngineError('GAMMA_DOWNLOAD_FAILED', 'Failed to download the Gamma export.', {
        cause: error,
      });
    }

    if (!response.ok) {
      throw new AgentEngineError(
        'GAMMA_DOWNLOAD_FAILED',
        `Gamma export download failed with HTTP ${response.status}.`,
        { metadata: { status: response.status } }
      );
    }

    const contentLength = Number(response.headers.get('content-length'));
    if (Number.isFinite(contentLength) && contentLength > this.maxResponseBytes) {
      throw new AgentEngineError(
        'GAMMA_DOWNLOAD_FAILED',
        'Gamma returned an export larger than the configured size limit.',
        { metadata: { contentLength, maxResponseBytes: this.maxResponseBytes } }
      );
    }

    const buffer = await this.readResponseBuffer(response);
    if (exportAs === 'pptx') {
      if (buffer.length < 4 || buffer.subarray(0, 2).toString('utf8') !== 'PK') {
        throw new AgentEngineError(
          'GAMMA_DOWNLOAD_FAILED',
          'Gamma returned an invalid PPTX artifact.'
        );
      }
    } else if (buffer.length < 5 || buffer.subarray(0, 5).toString('ascii') !== '%PDF-') {
      throw new AgentEngineError(
        'GAMMA_DOWNLOAD_FAILED',
        'Gamma returned an invalid PDF artifact.'
      );
    }

    return buffer;
  }

  private buildGenerationRequestBody(options: {
    readonly exportAs: 'pptx' | 'pdf';
    readonly format: 'presentation' | 'document';
    readonly input: GammaExportInputBase;
  }): Record<string, unknown> {
    const themeId = this.resolveThemeId(options);
    const inputText = this.buildInputText(options.input);

    return {
      title: options.input.title,
      inputText,
      textMode: 'preserve',
      format: options.format,
      exportAs: options.exportAs,
      cardSplit: options.format === 'presentation' ? 'inputTextBreaks' : undefined,
      themeId,
      additionalInstructions: this.buildAdditionalInstructions(options.input, options.format),
      cardOptions:
        options.format === 'presentation'
          ? {
              dimensions: this.resolvePresentationDimensions(options.input.pageOrientation),
              headerFooter: this.buildHeaderFooter(options.input, options.format),
            }
          : {
              dimensions: this.resolveDocumentDimensions(options.input.pageSize),
              headerFooter: this.buildHeaderFooter(options.input, options.format),
            },
      imageOptions: this.buildImageOptions(options.input),
    };
  }

  private buildTemplateRequestBody(options: {
    readonly exportAs: 'pptx' | 'pdf';
    readonly format: 'presentation' | 'document';
    readonly input: GammaExportInputBase;
  }): Record<string, unknown> {
    const themeId = this.resolveThemeId(options);
    return {
      gammaId: options.input.templateGammaId,
      prompt: this.buildTemplatePrompt(options.input, options.format),
      title: options.input.title,
      exportAs: options.exportAs,
      themeId,
    };
  }

  private buildTemplatePrompt(
    input: GammaExportInputBase,
    format: 'presentation' | 'document'
  ): string {
    const promptSections = [
      'Preserve the template structure and replace the content with the following material.',
      this.buildInputText(input),
      this.buildAdditionalInstructions(input, format),
    ].filter((value): value is string => typeof value === 'string' && value.trim().length > 0);

    return promptSections.join('\n\n');
  }

  private buildAdditionalInstructions(
    input: GammaExportInputBase,
    format: 'presentation' | 'document'
  ): string | undefined {
    const instructions: string[] = [];

    instructions.push(
      'Make the design feel premium, polished, and professional. Use refined typography, disciplined spacing, strong visual hierarchy, and clean modern composition.'
    );

    if (input.organizationName?.trim()) {
      instructions.push(
        `Use ${input.organizationName.trim()} as the organization identity throughout the ${format}.`
      );
    }

    if (input.brandPrimaryColor?.trim()) {
      instructions.push(
        `Use ${input.brandPrimaryColor.trim()} as the only accent color family. Build the design around black, white, soft gray neutrals, and this brand color. Do not introduce unrelated purple, pink, or lavender accent colors.`
      );
    } else {
      instructions.push(
        'Use a restrained black, white, and gray palette. Avoid playful or colorful accent palettes.'
      );
    }

    if (input.brandSecondaryColor?.trim()) {
      instructions.push(
        `Use ${input.brandSecondaryColor.trim()} as the secondary brand color for background blocks, section bands, stat cards, dividers, or alternating surfaces. Vary the page backgrounds and section treatments tastefully using the primary and secondary brand colors while keeping typography highly readable and professional.`
      );
    }

    if (input.logoUrl?.trim()) {
      instructions.push(
        'Use the uploaded logo in a subtle professional header/footer treatment. Preserve the logo aspect ratio and do not overpower the page.'
      );
    }

    if (format === 'presentation') {
      const backgroundMode = this.resolveBrandBackgroundMode(input);
      instructions.push(
        'Design this as an executive-quality presentation deck. Favor strong title slides, summary callouts, side-by-side chart/text compositions, premium stat cards, and consistent spacing. Avoid generic or simplistic slide layouts.'
      );
      instructions.push(
        'If images are provided, use clean gallery or side-by-side layouts and preserve aspect ratio. Use one main idea per slide and make headlines sharp, serious, and staff-ready.'
      );
      if (backgroundMode === 'neutral') {
        instructions.push(
          'Keep the deck clean and professional with mostly white or light-neutral slides, using brand colors for accents, dividers, title bands, and callouts rather than full-background treatments.'
        );
      } else if (backgroundMode === 'balanced') {
        instructions.push(
          'Do not default every slide to white. Alternate between neutral slides and brand-colored section bands, title slides, stat cards, and key summary backgrounds using the primary and secondary brand colors in a tasteful, high-contrast way.'
        );
      } else if (backgroundMode === 'alternating') {
        instructions.push(
          'Alternate slide surfaces across the deck using white/light-neutral backgrounds and branded backgrounds from the primary and secondary colors. Use those colors for section transitions, feature slides, and key-metric backgrounds while preserving readability.'
        );
      } else if (backgroundMode === 'bold') {
        instructions.push(
          'Use a strong premium team-branded look with more assertive primary/secondary color backgrounds, including full-bleed or large-block background treatments on title and divider slides, while keeping typography crisp and highly readable.'
        );
      }
    } else {
      instructions.push(
        'Design this as a print-friendly professional document, not a slide deck. Use letter-style report pages, subtle section labels, clean page hierarchy, and wide readable tables with minimal awkward wrapping.'
      );
      instructions.push(
        'Keep the layout elegant and document-oriented with strong section dividers, balanced margins, and professional staff-report formatting.'
      );
    }

    if (input.additionalInstructions?.trim()) {
      instructions.push(input.additionalInstructions.trim());
    }

    return instructions.length > 0 ? instructions.join(' ') : undefined;
  }

  private buildHeaderFooter(
    input: GammaExportInputBase,
    format: 'presentation' | 'document'
  ): Record<string, unknown> | undefined {
    const logoUrl = normalizeOptionalString(input.logoUrl);
    const organizationName = normalizeOptionalString(input.organizationName);
    const title = normalizeOptionalString(input.title);
    const footerText = normalizeOptionalString(input.footerText);

    if (!logoUrl && !organizationName && !footerText && format !== 'presentation') return undefined;

    if (format === 'presentation') {
      return {
        ...(logoUrl
          ? {
              topRight: {
                type: 'image',
                source: 'custom',
                src: logoUrl,
                size: 'sm',
              },
            }
          : {}),
        ...(organizationName
          ? {
              bottomLeft: {
                type: 'text',
                value: organizationName,
              },
            }
          : {}),
        ...(footerText
          ? {
              bottomCenter: {
                type: 'text',
                value: footerText,
              },
            }
          : {}),
        bottomRight: {
          type: 'cardNumber',
        },
        hideFromFirstCard: true,
        hideFromLastCard: true,
      };
    }

    return {
      ...(logoUrl
        ? {
            topLeft: {
              type: 'image',
              source: 'custom',
              src: logoUrl,
              size: 'md',
            },
          }
        : {}),
      ...(organizationName || title
        ? {
            topRight: {
              type: 'text',
              value: organizationName ?? title,
            },
          }
        : {}),
      ...(footerText
        ? {
            bottomLeft: {
              type: 'text',
              value: footerText,
            },
          }
        : {}),
      bottomRight: {
        type: 'cardNumber',
      },
    };
  }

  private buildImageOptions(_input: GammaExportInputBase): Record<string, unknown> {
    return {
      source: 'noImages',
    };
  }

  private buildInputText(input: GammaExportInputBase): string {
    const sections = input.sections?.length
      ? input.sections.map((section) => this.buildSectionText(section))
      : [
          this.buildSectionText({
            title: input.title,
            description: input.description,
            bodyParagraphs: input.bodyParagraphs,
            bulletPoints: input.bulletPoints,
            columns: input.columns,
            rows: input.rows,
            imageUrls: input.imageUrls,
          }),
        ];

    return sections.filter(Boolean).join('\n\n---\n\n');
  }

  private buildSectionText(section: GammaStructuredSection): string {
    const lines: string[] = [];
    if (section.title?.trim()) lines.push(`# ${section.title.trim()}`);
    if (section.description?.trim()) lines.push(section.description.trim());

    for (const paragraph of section.bodyParagraphs ?? []) {
      if (paragraph.trim()) lines.push(paragraph.trim());
    }

    for (const bullet of section.bulletPoints ?? []) {
      if (bullet.trim()) lines.push(`- ${bullet.trim()}`);
    }

    if (section.columns?.length && section.rows?.length) {
      lines.push(
        `| ${section.columns.map((column) => escapeMarkdownTableCell(column.label)).join(' | ')} |`,
        `| ${section.columns.map(() => '---').join(' | ')} |`,
        ...section.rows.map(
          (row) => `| ${row.map((cell) => escapeMarkdownTableCell(formatCell(cell))).join(' | ')} |`
        )
      );
    }

    for (const imageUrl of section.imageUrls ?? []) {
      if (imageUrl.trim()) lines.push(imageUrl.trim());
    }

    return lines.join('\n\n');
  }

  private resolvePresentationDimensions(
    pageOrientation?: 'portrait' | 'landscape'
  ): '16x9' | '4x3' {
    return pageOrientation === 'portrait' ? '4x3' : '16x9';
  }

  private resolveDocumentDimensions(
    pageSize?: 'LETTER' | 'LEGAL' | 'TABLOID'
  ): 'fluid' | 'letter' | undefined {
    if (pageSize === 'LETTER') return 'letter';
    return 'fluid';
  }

  private resolveThemeId(options: {
    readonly format: 'presentation' | 'document';
    readonly input: GammaExportInputBase;
  }): string | undefined {
    return (
      normalizeOptionalString(options.input.themeId) ??
      this.defaultThemeId ??
      DEFAULT_PROFESSIONAL_THEME_ID
    );
  }

  private resolveBrandBackgroundMode(
    input: GammaExportInputBase
  ): 'neutral' | 'balanced' | 'alternating' | 'bold' {
    if (input.brandBackgroundMode && input.brandBackgroundMode !== 'auto') {
      return input.brandBackgroundMode;
    }

    return input.brandPrimaryColor && input.brandSecondaryColor ? 'balanced' : 'neutral';
  }

  private buildApiHeaders(): HeadersInit {
    return {
      'content-type': 'application/json',
      'x-api-key': this.apiKey ?? '',
    };
  }

  private async parseJson<T>(response: Response, code: 'GAMMA_INVALID_RESPONSE'): Promise<T> {
    try {
      const payload: unknown = await response.json();
      if (!payload || typeof payload !== 'object' || Array.isArray(payload)) {
        throw new Error('Response body is not an object.');
      }
      return payload as T;
    } catch (error) {
      throw new AgentEngineError(code, 'Gamma returned an invalid JSON response.', {
        cause: error,
      });
    }
  }

  private async readResponseBuffer(response: Response): Promise<Buffer> {
    const reader = response.body?.getReader();
    if (!reader) return Buffer.alloc(0);

    const chunks: Buffer[] = [];
    let sizeBytes = 0;

    while (true) {
      const { done, value } = await reader.read();
      if (done) return Buffer.concat(chunks, sizeBytes);

      const chunk = Buffer.from(value);
      sizeBytes += chunk.length;
      if (sizeBytes > this.maxResponseBytes) {
        await reader.cancel().catch(() => undefined);
        throw new AgentEngineError(
          'GAMMA_DOWNLOAD_FAILED',
          'Gamma returned an export larger than the configured size limit.',
          { metadata: { sizeBytes, maxResponseBytes: this.maxResponseBytes } }
        );
      }
      chunks.push(chunk);
    }
  }
}

function escapeMarkdownTableCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function formatCell(value: string | number | boolean | null | undefined): string {
  return value == null ? '' : String(value);
}

function parseBoolean(value: string | undefined): boolean {
  return value?.trim().toLowerCase() === 'true';
}

function resolveEnvironmentValue(
  environment: ReturnType<typeof getRuntimeEnvironment>,
  key: string
): string | undefined {
  const scopedKey = environment === 'production' ? `PRODUCTION_${key}` : `STAGING_${key}`;
  return process.env[scopedKey] ?? process.env[key];
}

function normalizeBaseUrl(value: string): URL {
  const normalized = value.trim();
  const withTrailingSlash = normalized.endsWith('/') ? normalized : `${normalized}/`;
  return new URL(withTrailingSlash);
}

function normalizeOptionalString(value: string | undefined): string | null {
  const normalized = value?.trim();
  return normalized ? normalized : null;
}

function normalizePositiveInteger(value: number | string | undefined, fallback: number): number {
  const parsed = typeof value === 'number' ? value : Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback;
}

async function wait(milliseconds: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, milliseconds));
}
