/**
 * @fileoverview Schedule Event — Firestore `Schedule` collection document type
 *
 * Stores COMPETITIVE schedule events (games, scrimmages, practices, playoffs).
 * Document ID: auto-generated by write_schedule tool (deduped by date+opponent+sport+type).
 *
 * NOTE: Exposure events (camps, combines, showcases) live in the `Events` collection.
 */

import type { PortableTimestamp } from '../portable-timestamp.model';

export type ScheduleEventType = 'game' | 'scrimmage' | 'practice' | 'playoff' | 'other';
export type ScheduleEventOwnerType = 'user' | 'team';
export type ScheduleEventStatus = 'upcoming' | 'live' | 'completed' | 'cancelled' | 'postponed';
export type ScheduleEventOutcome = 'win' | 'loss' | 'draw' | 'cancelled' | 'postponed';

export interface ScheduleEventDoc {
  readonly id: string;

  /** Owner of this schedule entry — athlete userId OR teamId */
  readonly ownerId: string;
  readonly ownerType: ScheduleEventOwnerType;

  /** Sport key (lowercase, e.g. 'football', 'basketball') */
  readonly sport: string;

  /** Type of competitive event */
  readonly scheduleType: ScheduleEventType;

  /** ISO date string for event start */
  readonly date: string;

  /** ISO date string for event end (optional — multi-day or timed events) */
  readonly endDate?: string;

  /** Human-readable title / event name (optional) */
  readonly title?: string;

  /** Opponent team name (if applicable) */
  readonly opponent?: string;

  /** Whether this is a home game (optional) */
  readonly isHome?: boolean;

  /** Score result string e.g. "W 14-7", "L 21-24" */
  readonly result?: string;

  /** Structured outcome */
  readonly outcome?: ScheduleEventOutcome;

  /** Current status of the event */
  readonly status?: ScheduleEventStatus;

  /** Venue / location */
  readonly location?: string;

  // ── Backwards-compat fields ─────────────────────────────────────────────
  /** Populated when ownerType === 'user' */
  readonly userId?: string;
  /** Populated when ownerType === 'team' */
  readonly teamId?: string;

  // ── Provenance ─────────────────────────────────────────────────────────
  readonly source: string;
  readonly verified: boolean;
  readonly provider: string;
  readonly extractedAt: string;
  readonly sourceUrl?: string;

  // ── Timestamps ─────────────────────────────────────────────────────────
  readonly createdAt: PortableTimestamp;
  readonly updatedAt: PortableTimestamp;
}
