/**
 * @fileoverview Mock Edit Profile Data for Development
 * @module @nxt1/ui/edit-profile/mock-data
 *
 * ⚠️ TEMPORARY FILE - Delete when backend is ready
 *
 * Contains comprehensive dummy data for Edit Profile feature during development.
 * All data here is fabricated for UI testing purposes only.
 */

import type {
  EditProfileFormData,
  ProfileCompletionData,
  ProfileAchievement,
  EditProfileSection,
} from '@nxt1/core';

const now = Date.now();

// ============================================
// MOCK FORM DATA
// ============================================

export const MOCK_EDIT_PROFILE_FORM_DATA: EditProfileFormData = {
  basicInfo: {
    firstName: 'Marcus',
    lastName: 'Johnson',
    displayName: 'Marcus Johnson',
    bio: 'Dedicated student-athlete with a passion for football. Team captain and honor roll student. Working hard every day to achieve my dreams of playing at the next level. 🏈 #GrindNeverStops',
    location: 'Austin, TX',
    classYear: '2026',
  },
  photos: {
    profileImg: 'https://i.pravatar.cc/300?img=68',
    bannerImg: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&h=400&fit=crop',
    profileImages: [],
  },
  sportsInfo: {
    primarySport: 'Football',
    primaryPosition: 'Quarterback',
    secondaryPositions: ['Wide Receiver'],
    jerseyNumber: '12',
    yearsExperience: 8,
  },
  academics: {
    school: 'Riverside High School',
    gpa: '3.8',
    sat: '1280',
    act: '28',
    intendedMajor: 'Business Administration',
    graduationDate: '2026-05-15',
  },
  physical: {
    height: '6\'2"',
    weight: '195',
    wingspan: '6\'5"',
    fortyYardDash: '4.58',
    verticalJump: '34.5"',
  },
  socialLinks: {
    links: [
      {
        platform: 'twitter',
        url: 'https://x.com/marcusj12',
        username: '@marcusj12',
        displayOrder: 0,
      },
      {
        platform: 'instagram',
        url: 'https://instagram.com/marcus.johnson12',
        username: '@marcus.johnson12',
        displayOrder: 1,
      },
      { platform: 'hudl', url: 'https://hudl.com/marcus-johnson', displayOrder: 2 },
    ],
  },
  contact: {
    email: 'marcus.johnson@email.com',
    phone: '(555) 123-4567',
    parentEmail: 'parent.johnson@email.com',
    parentPhone: '(555) 987-6543',
    coachEmail: 'coach.thompson@riverside.edu',
    preferredContactMethod: 'email',
  },
};

// ============================================
// MOCK COMPLETION DATA
// ============================================

export const MOCK_PROFILE_COMPLETION: ProfileCompletionData = {
  percentage: 78,
  tier: 'mvp',
  xpEarned: 625,
  xpTotal: 800,
  progressToNextTier: 78,
  nextTier: 'legend',
  fieldsCompleted: 28,
  fieldsTotal: 36,
  sections: [
    {
      sectionId: 'basic-info',
      percentage: 100,
      fieldsCompleted: 6,
      fieldsTotal: 6,
      xpEarned: 100,
      isComplete: true,
    },
    {
      sectionId: 'photos',
      percentage: 100,
      fieldsCompleted: 2,
      fieldsTotal: 2,
      xpEarned: 75,
      isComplete: true,
    },
    {
      sectionId: 'sports-info',
      percentage: 100,
      fieldsCompleted: 5,
      fieldsTotal: 5,
      xpEarned: 100,
      isComplete: true,
    },
    {
      sectionId: 'academics',
      percentage: 100,
      fieldsCompleted: 5,
      fieldsTotal: 5,
      xpEarned: 100,
      isComplete: true,
    },
    {
      sectionId: 'physical',
      percentage: 100,
      fieldsCompleted: 5,
      fieldsTotal: 5,
      xpEarned: 100,
      isComplete: true,
    },
    {
      sectionId: 'social-links',
      percentage: 40,
      fieldsCompleted: 2,
      fieldsTotal: 5,
      xpEarned: 35,
      isComplete: false,
    },
    {
      sectionId: 'contact',
      percentage: 60,
      fieldsCompleted: 3,
      fieldsTotal: 5,
      xpEarned: 45,
      isComplete: false,
    },
  ],
  recentAchievements: [
    {
      id: 'ach-mvp-tier',
      title: 'MVP Status',
      description: 'Reached 75% profile completion',
      icon: 'trophy',
      xpReward: 300,
      unlockedAt: new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString(),
      tier: 'gold',
    },
    {
      id: 'ach-photo-pro',
      title: 'Photo Pro',
      description: 'Uploaded profile and banner photos',
      icon: 'camera',
      xpReward: 75,
      unlockedAt: new Date(now - 5 * 24 * 60 * 60 * 1000).toISOString(),
      tier: 'silver',
    },
  ],
};

// ============================================
// MOCK SECTION DATA (with completion status)
// ============================================

export const MOCK_EDIT_PROFILE_SECTIONS: EditProfileSection[] = [
  {
    id: 'basic-info',
    title: 'Basic Info',
    icon: 'person-outline',
    description: 'Your name, bio, and location',
    completionPercent: 100,
    xpReward: 100,
    isExpanded: false,
    fields: [
      {
        id: 'firstName',
        type: 'text',
        label: 'First Name',
        placeholder: 'Enter your first name',
        required: true,
        value: 'Marcus',
        xpReward: 10,
        countsTowardCompletion: true,
        order: 1,
      },
      {
        id: 'lastName',
        type: 'text',
        label: 'Last Name',
        placeholder: 'Enter your last name',
        required: true,
        value: 'Johnson',
        xpReward: 10,
        countsTowardCompletion: true,
        order: 2,
      },
      {
        id: 'displayName',
        type: 'text',
        label: 'Display Name',
        placeholder: 'How you want to appear',
        hint: 'Leave blank to use your full name',
        value: 'Marcus Johnson',
        xpReward: 5,
        countsTowardCompletion: false,
        order: 3,
      },
      {
        id: 'bio',
        type: 'textarea',
        label: 'Bio',
        placeholder: 'Tell coaches about yourself...',
        hint: 'Share your story, goals, and what makes you unique',
        value:
          'Dedicated student-athlete with a passion for football. Team captain and honor roll student. Working hard every day to achieve my dreams of playing at the next level. 🏈 #GrindNeverStops',
        validation: { maxLength: 500 },
        xpReward: 25,
        countsTowardCompletion: true,
        order: 4,
      },
      {
        id: 'location',
        type: 'location',
        label: 'Location',
        placeholder: 'City, State',
        hint: 'Helps coaches find local talent',
        value: 'Austin, TX',
        xpReward: 15,
        countsTowardCompletion: true,
        order: 5,
        icon: 'location-outline',
      },
      {
        id: 'classYear',
        type: 'select',
        label: 'Class Year',
        placeholder: 'Select graduation year',
        required: true,
        value: '2026',
        options: [
          { value: '2025', label: 'Class of 2025' },
          { value: '2026', label: 'Class of 2026' },
          { value: '2027', label: 'Class of 2027' },
          { value: '2028', label: 'Class of 2028' },
          { value: '2029', label: 'Class of 2029' },
        ],
        xpReward: 15,
        countsTowardCompletion: true,
        order: 6,
      },
    ],
  },
  {
    id: 'photos',
    title: 'Photos',
    icon: 'camera-outline',
    description: 'Profile picture and banner',
    completionPercent: 100,
    xpReward: 75,
    isExpanded: false,
    fields: [
      {
        id: 'profileImg',
        type: 'photo-upload',
        label: 'Profile Photo',
        hint: 'Professional headshot recommended',
        value: 'https://i.pravatar.cc/300?img=68',
        xpReward: 50,
        countsTowardCompletion: true,
        order: 1,
      },
      {
        id: 'bannerImg',
        type: 'photo-upload',
        label: 'Banner Image',
        hint: 'Action shot or team photo works great',
        value: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&h=400&fit=crop',
        xpReward: 25,
        countsTowardCompletion: true,
        order: 2,
      },
    ],
  },
  {
    id: 'sports-info',
    title: 'Sports Info',
    icon: 'football-outline',
    description: 'Your sport, position, and jersey',
    completionPercent: 100,
    xpReward: 100,
    isExpanded: false,
    fields: [
      {
        id: 'primarySport',
        type: 'select',
        label: 'Primary Sport',
        placeholder: 'Select your main sport',
        required: true,
        value: 'Football',
        xpReward: 20,
        countsTowardCompletion: true,
        order: 1,
      },
      {
        id: 'primaryPosition',
        type: 'select',
        label: 'Primary Position',
        placeholder: 'Select your position',
        required: true,
        value: 'Quarterback',
        xpReward: 20,
        countsTowardCompletion: true,
        order: 2,
      },
      {
        id: 'secondaryPositions',
        type: 'multi-select',
        label: 'Secondary Positions',
        placeholder: 'Select additional positions',
        hint: 'Coaches love versatile players',
        value: ['Wide Receiver'],
        xpReward: 15,
        countsTowardCompletion: false,
        order: 3,
      },
      {
        id: 'jerseyNumber',
        type: 'number',
        label: 'Jersey Number',
        placeholder: '#',
        value: '12',
        validation: { min: 0, max: 99 },
        xpReward: 10,
        countsTowardCompletion: true,
        order: 4,
      },
      {
        id: 'yearsExperience',
        type: 'number',
        label: 'Years of Experience',
        placeholder: 'e.g., 5',
        value: 8,
        xpReward: 10,
        countsTowardCompletion: false,
        order: 5,
      },
    ],
  },
  {
    id: 'academics',
    title: 'Academics',
    icon: 'school-outline',
    description: 'GPA, test scores, and school',
    completionPercent: 100,
    xpReward: 100,
    isExpanded: false,
    fields: [
      {
        id: 'school',
        type: 'text',
        label: 'Current School',
        placeholder: 'School name',
        required: true,
        value: 'Riverside High School',
        xpReward: 15,
        countsTowardCompletion: true,
        order: 1,
      },
      {
        id: 'gpa',
        type: 'text',
        label: 'GPA',
        placeholder: 'e.g., 3.8',
        hint: 'Weighted or unweighted',
        value: '3.8',
        xpReward: 20,
        countsTowardCompletion: true,
        order: 2,
      },
      {
        id: 'sat',
        type: 'number',
        label: 'SAT Score',
        placeholder: 'e.g., 1200',
        value: 1280,
        validation: { min: 400, max: 1600 },
        xpReward: 15,
        countsTowardCompletion: false,
        order: 3,
      },
      {
        id: 'act',
        type: 'number',
        label: 'ACT Score',
        placeholder: 'e.g., 28',
        value: 28,
        validation: { min: 1, max: 36 },
        xpReward: 15,
        countsTowardCompletion: false,
        order: 4,
      },
      {
        id: 'intendedMajor',
        type: 'text',
        label: 'Intended Major',
        placeholder: 'What do you want to study?',
        value: 'Business Administration',
        xpReward: 10,
        countsTowardCompletion: false,
        order: 5,
      },
    ],
  },
  {
    id: 'physical',
    title: 'Physical Stats',
    icon: 'fitness-outline',
    description: 'Height, weight, and measurables',
    completionPercent: 100,
    xpReward: 100,
    isExpanded: false,
    fields: [
      {
        id: 'height',
        type: 'height',
        label: 'Height',
        placeholder: 'e.g., 6\'2"',
        required: true,
        value: '6\'2"',
        xpReward: 20,
        countsTowardCompletion: true,
        order: 1,
      },
      {
        id: 'weight',
        type: 'weight',
        label: 'Weight',
        placeholder: 'e.g., 185 lbs',
        required: true,
        value: '195',
        xpReward: 20,
        countsTowardCompletion: true,
        order: 2,
      },
      {
        id: 'wingspan',
        type: 'text',
        label: 'Wingspan',
        placeholder: 'e.g., 6\'5"',
        value: '6\'5"',
        xpReward: 15,
        countsTowardCompletion: false,
        order: 3,
      },
      {
        id: 'fortyYardDash',
        type: 'text',
        label: '40-Yard Dash',
        placeholder: 'e.g., 4.5s',
        value: '4.58',
        xpReward: 15,
        countsTowardCompletion: false,
        order: 4,
      },
      {
        id: 'verticalJump',
        type: 'text',
        label: 'Vertical Jump',
        placeholder: 'e.g., 32"',
        value: '34.5"',
        xpReward: 15,
        countsTowardCompletion: false,
        order: 5,
      },
    ],
  },
  {
    id: 'social-links',
    title: 'Social Links',
    icon: 'share-social-outline',
    description: 'Connect your social profiles',
    completionPercent: 40,
    xpReward: 75,
    isExpanded: false,
    fields: [
      {
        id: 'twitter',
        type: 'url',
        label: 'Twitter / X',
        placeholder: '@username',
        icon: 'logo-twitter',
        value: '@marcusj12',
        xpReward: 10,
        countsTowardCompletion: false,
        order: 1,
      },
      {
        id: 'instagram',
        type: 'url',
        label: 'Instagram',
        placeholder: '@username',
        icon: 'logo-instagram',
        value: '@marcus.johnson12',
        xpReward: 10,
        countsTowardCompletion: false,
        order: 2,
      },
      {
        id: 'tiktok',
        type: 'url',
        label: 'TikTok',
        placeholder: '@username',
        icon: 'logo-tiktok',
        value: '',
        xpReward: 10,
        countsTowardCompletion: false,
        order: 3,
      },
      {
        id: 'youtube',
        type: 'url',
        label: 'YouTube',
        placeholder: 'Channel URL',
        icon: 'logo-youtube',
        value: '',
        xpReward: 10,
        countsTowardCompletion: false,
        order: 4,
      },
      {
        id: 'hudl',
        type: 'url',
        label: 'Hudl',
        placeholder: 'Profile URL',
        hint: 'Essential for recruiting',
        value: 'https://hudl.com/marcus-johnson',
        xpReward: 25,
        countsTowardCompletion: true,
        order: 5,
      },
    ],
  },
  {
    id: 'contact',
    title: 'Contact Info',
    icon: 'mail-outline',
    description: 'How coaches can reach you',
    completionPercent: 60,
    xpReward: 75,
    isExpanded: false,
    fields: [
      {
        id: 'email',
        type: 'email',
        label: 'Email',
        placeholder: 'your@email.com',
        required: true,
        value: 'marcus.johnson@email.com',
        xpReward: 15,
        countsTowardCompletion: true,
        order: 1,
      },
      {
        id: 'phone',
        type: 'phone',
        label: 'Phone Number',
        placeholder: '(555) 123-4567',
        value: '(555) 123-4567',
        xpReward: 15,
        countsTowardCompletion: true,
        order: 2,
      },
      {
        id: 'parentEmail',
        type: 'email',
        label: 'Parent/Guardian Email',
        placeholder: 'parent@email.com',
        hint: 'Required for NCAA compliance',
        value: 'parent.johnson@email.com',
        xpReward: 15,
        countsTowardCompletion: true,
        order: 3,
      },
      {
        id: 'parentPhone',
        type: 'phone',
        label: 'Parent/Guardian Phone',
        placeholder: '(555) 123-4567',
        value: '',
        xpReward: 10,
        countsTowardCompletion: false,
        order: 4,
      },
      {
        id: 'coachEmail',
        type: 'email',
        label: 'Coach Email',
        placeholder: 'coach@school.edu',
        hint: 'College coaches often contact your high school coach',
        value: '',
        xpReward: 15,
        countsTowardCompletion: true,
        order: 5,
      },
    ],
  },
];

// ============================================
// MOCK ACHIEVEMENTS (for celebration animations)
// ============================================

export const MOCK_PROFILE_ACHIEVEMENTS: ProfileAchievement[] = [
  {
    id: 'ach-first-photo',
    title: 'Picture Perfect',
    description: 'Uploaded your first profile photo',
    icon: 'camera',
    xpReward: 25,
    unlockedAt: new Date(now - 10 * 24 * 60 * 60 * 1000).toISOString(),
    tier: 'bronze',
  },
  {
    id: 'ach-starter-tier',
    title: 'Getting Started',
    description: 'Reached 25% profile completion',
    icon: 'star-half',
    xpReward: 100,
    unlockedAt: new Date(now - 8 * 24 * 60 * 60 * 1000).toISOString(),
    tier: 'bronze',
  },
  {
    id: 'ach-all-star-tier',
    title: 'All-Star Status',
    description: 'Reached 50% profile completion',
    icon: 'star',
    xpReward: 200,
    unlockedAt: new Date(now - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tier: 'silver',
  },
  {
    id: 'ach-photo-pro',
    title: 'Photo Pro',
    description: 'Uploaded profile and banner photos',
    icon: 'images',
    xpReward: 75,
    unlockedAt: new Date(now - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tier: 'silver',
  },
  {
    id: 'ach-mvp-tier',
    title: 'MVP Status',
    description: 'Reached 75% profile completion',
    icon: 'trophy',
    xpReward: 300,
    unlockedAt: new Date(now - 2 * 24 * 60 * 60 * 1000).toISOString(),
    tier: 'gold',
  },
];

// ============================================
// EMPTY STATE DATA (for new users)
// ============================================

export const MOCK_EMPTY_PROFILE_FORM_DATA: EditProfileFormData = {
  basicInfo: {
    firstName: '',
    lastName: '',
    displayName: '',
    bio: '',
    location: '',
    classYear: '',
  },
  photos: {
    profileImg: '',
    bannerImg: '',
    profileImages: [],
  },
  sportsInfo: {
    primarySport: '',
    primaryPosition: '',
    secondaryPositions: [],
    jerseyNumber: '',
  },
  academics: {
    school: '',
    gpa: '',
    sat: '',
    act: '',
    intendedMajor: '',
  },
  physical: {
    height: '',
    weight: '',
    wingspan: '',
    fortyYardDash: '',
    verticalJump: '',
  },
  socialLinks: {
    links: [],
  },
  contact: {
    email: '',
    phone: '',
    parentEmail: '',
    parentPhone: '',
    coachEmail: '',
    preferredContactMethod: 'email',
  },
};

export const MOCK_EMPTY_COMPLETION: ProfileCompletionData = {
  percentage: 0,
  tier: 'rookie',
  xpEarned: 0,
  xpTotal: 800,
  progressToNextTier: 0,
  nextTier: 'starter',
  fieldsCompleted: 0,
  fieldsTotal: 36,
  sections: [
    {
      sectionId: 'basic-info',
      percentage: 0,
      fieldsCompleted: 0,
      fieldsTotal: 6,
      xpEarned: 0,
      isComplete: false,
    },
    {
      sectionId: 'photos',
      percentage: 0,
      fieldsCompleted: 0,
      fieldsTotal: 2,
      xpEarned: 0,
      isComplete: false,
    },
    {
      sectionId: 'sports-info',
      percentage: 0,
      fieldsCompleted: 0,
      fieldsTotal: 5,
      xpEarned: 0,
      isComplete: false,
    },
    {
      sectionId: 'academics',
      percentage: 0,
      fieldsCompleted: 0,
      fieldsTotal: 5,
      xpEarned: 0,
      isComplete: false,
    },
    {
      sectionId: 'physical',
      percentage: 0,
      fieldsCompleted: 0,
      fieldsTotal: 5,
      xpEarned: 0,
      isComplete: false,
    },
    {
      sectionId: 'social-links',
      percentage: 0,
      fieldsCompleted: 0,
      fieldsTotal: 5,
      xpEarned: 0,
      isComplete: false,
    },
    {
      sectionId: 'contact',
      percentage: 0,
      fieldsCompleted: 0,
      fieldsTotal: 5,
      xpEarned: 0,
      isComplete: false,
    },
  ],
  recentAchievements: [],
};
