/**
 * @fileoverview Shared types, multer config, constants, and helper functions for upload routes.
 * @module @nxt1/backend/routes/upload/shared
 */

import type { Request } from 'express';
import multer from 'multer';
import sharp from 'sharp';
import { getStorage } from 'firebase-admin/storage';
import { fieldError, forbiddenError } from '@nxt1/core/errors';
import { logger } from '../../utils/logger.js';
import type { FileCategory } from '@nxt1/core';
import { FILE_UPLOAD_RULES, PostVisibility } from '@nxt1/core';
export { FILE_UPLOAD_RULES, PostVisibility };
import { THUMBNAIL_SIZES, IMAGE_FORMATS } from '@nxt1/core/constants';

// ============================================
// CONSTANTS
// ============================================

export const CLOUDFLARE_API_BASE_URL = 'https://api.cloudflare.com/client/v4';
export const DEFAULT_CF_VIDEO_MAX_DURATION_SECONDS = 10_800;
export const DEFAULT_CF_UPLOAD_EXPIRY_HOURS = 12;
export const POSTS_COLLECTION = 'Posts';

// ============================================
// INTERFACES
// ============================================

export interface CloudflareVideoFinalizeResponse {
  readonly cloudflareVideoId: string;
  readonly status: string;
  readonly readyToStream: boolean;
  readonly durationSeconds: number | null;
  readonly thumbnailUrl: string | null;
  readonly previewUrl: string | null;
  readonly uploadedAt: string | null;
  readonly name: string | null;
  readonly metadata: {
    readonly userId: string;
    readonly context: string;
    readonly environment: string;
    readonly originalFileName: string;
    readonly mimeType: string;
  };
  readonly playback: {
    readonly hlsUrl: string | null;
    readonly dashUrl: string | null;
    readonly iframeUrl: string | null;
  };
}

export interface PersistedHighlightVideoPostResponse {
  readonly postId: string;
  readonly cloudflareVideoId: string;
  readonly status: string;
  readonly readyToStream: boolean;
  readonly title: string | null;
  readonly content: string;
  readonly thumbnailUrl: string | null;
  readonly mediaUrl: string | null;
  readonly duration: number | null;
  readonly visibility: 'public' | 'team' | 'private';
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly playback: {
    readonly hlsUrl: string | null;
    readonly dashUrl: string | null;
    readonly iframeUrl: string | null;
  };
}

/**
 * Extended file upload result with extension-generated thumbnails
 */
export interface ExtendedFileUploadResult {
  url: string;
  storagePath: string;
  size: number;
  mimeType: string;
  thumbnailUrl?: string;
  dimensions?: { width: number; height: number };
  /** Thumbnails generated by Firebase Resize Images extension */
  thumbnails?: {
    small: string;
    medium: string;
    large: string;
  };
  /** Whether extension thumbnails are ready (async generation) */
  thumbnailsReady?: boolean;
}

// ============================================
// MULTER CONFIGURATION
// ============================================

const storage = multer.memoryStorage();

const fileFilter = (
  _req: Request,
  file: Express.Multer.File,
  cb: multer.FileFilterCallback
): void => {
  const category = (_req.body?.category || 'profile-photo') as FileCategory;
  const rules = FILE_UPLOAD_RULES[category];

  if (!rules) {
    cb(new Error(`Invalid file category: ${category}`));
    return;
  }

  const allowedTypes = rules.allowedTypes as readonly string[];
  if (allowedTypes.includes(file.mimetype)) {
    cb(null, true);
  } else {
    cb(new Error(`File type ${file.mimetype} not allowed for ${category}`));
  }
};

export const upload = multer({
  storage,
  fileFilter,
  limits: {
    fileSize: 25 * 1024 * 1024,
    files: 1,
  },
});

// ============================================
// IMAGE HELPERS
// ============================================

export async function optimizeImage(
  buffer: Buffer,
  category: FileCategory,
  mimeType: string
): Promise<{
  buffer: Buffer;
  mimeType: string;
  dimensions: { width: number; height: number };
}> {
  const rules = FILE_UPLOAD_RULES[category];
  const maxDimensions = rules?.maxDimensions;

  let sharpInstance = sharp(buffer).rotate();
  const metadata = await sharpInstance.metadata();

  if (
    maxDimensions &&
    metadata.width &&
    metadata.height &&
    (metadata.width > maxDimensions.width || metadata.height > maxDimensions.height)
  ) {
    sharpInstance = sharpInstance.resize(maxDimensions.width, maxDimensions.height, {
      fit: 'inside',
      withoutEnlargement: true,
    });
  }

  let outputMimeType: string;
  let optimizedBuffer: Buffer;

  if (mimeType === 'image/gif') {
    outputMimeType = 'image/gif';
    optimizedBuffer = await sharpInstance.gif().toBuffer();
  } else if (mimeType === 'image/png') {
    outputMimeType = 'image/png';
    optimizedBuffer = await sharpInstance.png({ quality: 85, compressionLevel: 9 }).toBuffer();
  } else {
    outputMimeType = 'image/webp';
    optimizedBuffer = await sharpInstance.webp({ quality: 85, effort: 6 }).toBuffer();
  }

  const optimizedMetadata = await sharp(optimizedBuffer).metadata();

  return {
    buffer: optimizedBuffer,
    mimeType: outputMimeType,
    dimensions: {
      width: optimizedMetadata.width || 0,
      height: optimizedMetadata.height || 0,
    },
  };
}

export async function uploadToStorage(
  buffer: Buffer,
  storagePath: string,
  contentType: string,
  bucket?: ReturnType<ReturnType<typeof getStorage>['bucket']>
): Promise<string> {
  const storageBucket = bucket || getStorage().bucket();
  const file = storageBucket.file(storagePath);

  await file.save(buffer, {
    metadata: {
      contentType,
      cacheControl: 'public, max-age=31536000',
    },
  });

  await file.makePublic();

  return `https://storage.googleapis.com/${storageBucket.name}/${storagePath}`;
}

export function buildExtensionCompatiblePath(userId: string, category: FileCategory): string {
  const timestamp = Date.now();
  const extension = 'jpg';

  switch (category) {
    case 'profile-photo':
      return `Users/${userId}/profile/avatar_${timestamp}.${extension}`;

    default:
      return `Users/${userId}/uploads/${timestamp}.${extension}`;
  }
}

export function getExtensionThumbnailPaths(originalPath: string): {
  small: { jpg: string; webp: string; png: string };
  medium: { jpg: string; webp: string; png: string };
  large: { jpg: string; webp: string; png: string };
} {
  const lastSlash = originalPath.lastIndexOf('/');
  const directory = originalPath.substring(0, lastSlash);
  const filename = originalPath.substring(lastSlash + 1);
  const dotIndex = filename.lastIndexOf('.');
  const name = filename.substring(0, dotIndex);

  return {
    small: {
      jpg: `${directory}/${name}_${THUMBNAIL_SIZES.SMALL.suffix}.${IMAGE_FORMATS.JPEG}`,
      webp: `${directory}/${name}_${THUMBNAIL_SIZES.SMALL.suffix}.${IMAGE_FORMATS.WEBP}`,
      png: `${directory}/${name}_${THUMBNAIL_SIZES.SMALL.suffix}.${IMAGE_FORMATS.PNG}`,
    },
    medium: {
      jpg: `${directory}/${name}_${THUMBNAIL_SIZES.MEDIUM.suffix}.${IMAGE_FORMATS.JPEG}`,
      webp: `${directory}/${name}_${THUMBNAIL_SIZES.MEDIUM.suffix}.${IMAGE_FORMATS.WEBP}`,
      png: `${directory}/${name}_${THUMBNAIL_SIZES.MEDIUM.suffix}.${IMAGE_FORMATS.PNG}`,
    },
    large: {
      jpg: `${directory}/${name}_${THUMBNAIL_SIZES.LARGE.suffix}.${IMAGE_FORMATS.JPEG}`,
      webp: `${directory}/${name}_${THUMBNAIL_SIZES.LARGE.suffix}.${IMAGE_FORMATS.WEBP}`,
      png: `${directory}/${name}_${THUMBNAIL_SIZES.LARGE.suffix}.${IMAGE_FORMATS.PNG}`,
    },
  };
}

export async function waitForExtensionThumbnails(
  bucket: ReturnType<ReturnType<typeof getStorage>['bucket']>,
  thumbnailPath: string,
  maxAttempts: number = 10,
  delayMs: number = 300
): Promise<boolean> {
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      const [exists] = await bucket.file(thumbnailPath).exists();
      if (exists) {
        logger.debug('Extension thumbnail ready', { path: thumbnailPath, attempt });
        return true;
      }
    } catch {
      // Ignore errors during polling
    }
    await new Promise((resolve) => setTimeout(resolve, delayMs));
  }
  logger.warn('Extension thumbnail timeout', { path: thumbnailPath, maxAttempts });
  return false;
}

export function buildThumbnailUrls(
  bucketName: string,
  thumbnailPaths: ReturnType<typeof getExtensionThumbnailPaths>
): {
  small: string;
  medium: string;
  large: string;
  all: {
    small: { jpg: string; webp: string; png: string };
    medium: { jpg: string; webp: string; png: string };
    large: { jpg: string; webp: string; png: string };
  };
} {
  const baseUrl = `https://storage.googleapis.com/${bucketName}`;

  return {
    small: `${baseUrl}/${thumbnailPaths.small.webp}`,
    medium: `${baseUrl}/${thumbnailPaths.medium.webp}`,
    large: `${baseUrl}/${thumbnailPaths.large.webp}`,
    all: {
      small: {
        jpg: `${baseUrl}/${thumbnailPaths.small.jpg}`,
        webp: `${baseUrl}/${thumbnailPaths.small.webp}`,
        png: `${baseUrl}/${thumbnailPaths.small.png}`,
      },
      medium: {
        jpg: `${baseUrl}/${thumbnailPaths.medium.jpg}`,
        webp: `${baseUrl}/${thumbnailPaths.medium.webp}`,
        png: `${baseUrl}/${thumbnailPaths.medium.png}`,
      },
      large: {
        jpg: `${baseUrl}/${thumbnailPaths.large.jpg}`,
        webp: `${baseUrl}/${thumbnailPaths.large.webp}`,
        png: `${baseUrl}/${thumbnailPaths.large.png}`,
      },
    },
  };
}

/**
 * @deprecated Use buildExtensionCompatiblePath() instead
 */
export function buildStoragePath(userId: string, category: FileCategory, fileName: string): string {
  const timestamp = Date.now();
  const sanitizedName = fileName.replace(/[^a-zA-Z0-9.-]/g, '_');

  if (category === 'profile-photo') {
    return `Users/${userId}/profile/avatar_${timestamp}.jpg`;
  }

  const extension = sanitizedName.split('.').pop() || 'bin';
  return `Users/${userId}/${category}/${timestamp}_${sanitizedName.split('.')[0]}.${extension}`;
}

// ============================================
// TUS HELPERS
// ============================================

export function parseTusMetadataHeader(
  header: string | string[] | undefined
): Record<string, string> {
  if (!header || Array.isArray(header)) return {};

  return header
    .split(',')
    .map((entry) => entry.trim())
    .filter(Boolean)
    .reduce<Record<string, string>>((acc, entry) => {
      const [rawKey, ...rest] = entry.split(' ');
      const key = rawKey?.trim().toLowerCase();
      if (!key) return acc;

      if (rest.length === 0) {
        acc[key] = 'true';
        return acc;
      }

      try {
        acc[key] = Buffer.from(rest.join(' '), 'base64').toString('utf8');
      } catch {
        acc[key] = '';
      }

      return acc;
    }, {});
}

export function buildTusMetadataHeader(metadata: Record<string, string>): string {
  return Object.entries(metadata)
    .filter(([, value]) => value.length > 0)
    .map(([key, value]) => `${key} ${Buffer.from(value, 'utf8').toString('base64')}`)
    .join(',');
}

export function getTusMetadataValue(
  metadata: Record<string, string>,
  keys: readonly string[]
): string | undefined {
  for (const key of keys) {
    const value = metadata[key.toLowerCase()];
    if (value) return value;
  }
  return undefined;
}

// ============================================
// CLOUDFLARE HELPERS
// ============================================

export function buildCloudflareVideoName(
  userId: string,
  context: string,
  fileName: string
): string {
  const timestamp = Date.now();
  const baseName = fileName.replace(/[^a-zA-Z0-9.-]/g, '_').split('.')[0] || 'video';
  const safeContext = context.replace(/[^a-zA-Z0-9_-]/g, '_') || 'general';
  return `nxt1-${safeContext}-${userId}-${timestamp}-${baseName}`;
}

export function extractCloudflareVideoId(uploadUrl: string): string | null {
  try {
    const url = new URL(uploadUrl);
    return url.pathname.split('/').filter(Boolean).pop() ?? null;
  } catch {
    return null;
  }
}

export function getCloudflareStreamHost(customerCode: string | undefined): string | null {
  if (!customerCode) return null;

  const normalizedCustomerCode = customerCode.startsWith('customer-')
    ? customerCode
    : `customer-${customerCode}`;

  return `https://${normalizedCustomerCode}.cloudflarestream.com`;
}

export function buildCloudflarePlaybackUrls(
  videoId: string,
  customerCode: string | undefined,
  playback?: { hls?: string; dash?: string }
): { hlsUrl: string | null; dashUrl: string | null; iframeUrl: string | null } {
  const streamHost = getCloudflareStreamHost(customerCode);

  return {
    hlsUrl: playback?.hls ?? (streamHost ? `${streamHost}/${videoId}/manifest/video.m3u8` : null),
    dashUrl: playback?.dash ?? (streamHost ? `${streamHost}/${videoId}/manifest/video.mpd` : null),
    iframeUrl: streamHost ? `${streamHost}/${videoId}/iframe` : null,
  };
}

export function normalizeCloudflareVideoForClient(
  videoId: string,
  payload: Record<string, unknown>,
  customerCode: string | undefined
): CloudflareVideoFinalizeResponse {
  const meta = ((payload['meta'] as Record<string, unknown> | undefined) ?? {}) as Record<
    string,
    unknown
  >;
  const status = ((payload['status'] as Record<string, unknown> | undefined) ?? {}) as Record<
    string,
    unknown
  >;
  const playback = ((payload['playback'] as Record<string, unknown> | undefined) ?? {}) as Record<
    string,
    unknown
  >;

  return {
    cloudflareVideoId: videoId,
    status: typeof status['state'] === 'string' ? status['state'] : 'unknown',
    readyToStream: payload['readyToStream'] === true,
    durationSeconds:
      typeof payload['duration'] === 'number'
        ? payload['duration']
        : Number(payload['duration']) || null,
    thumbnailUrl: typeof payload['thumbnail'] === 'string' ? payload['thumbnail'] : null,
    previewUrl: typeof payload['preview'] === 'string' ? payload['preview'] : null,
    uploadedAt: typeof payload['uploaded'] === 'string' ? payload['uploaded'] : null,
    name: typeof meta['name'] === 'string' ? meta['name'] : null,
    metadata: {
      userId: typeof meta['nxt1_user_id'] === 'string' ? meta['nxt1_user_id'] : '',
      context: typeof meta['nxt1_context'] === 'string' ? meta['nxt1_context'] : 'general',
      environment: typeof meta['nxt1_env'] === 'string' ? meta['nxt1_env'] : 'staging',
      originalFileName:
        typeof meta['nxt1_file_name'] === 'string' ? meta['nxt1_file_name'] : `${videoId}.mp4`,
      mimeType: typeof meta['nxt1_mime_type'] === 'string' ? meta['nxt1_mime_type'] : 'video/mp4',
    },
    playback: buildCloudflarePlaybackUrls(videoId, customerCode, {
      hls: typeof playback['hls'] === 'string' ? playback['hls'] : undefined,
      dash: typeof playback['dash'] === 'string' ? playback['dash'] : undefined,
    }),
  };
}

export function getCloudflareHighlightPostId(cloudflareVideoId: string): string {
  return `cf-stream-${cloudflareVideoId}`;
}

export function trimOptionalString(
  value: unknown,
  fieldName: string,
  maxLength: number
): string | undefined {
  if (value === undefined || value === null) {
    return undefined;
  }

  if (typeof value !== 'string') {
    throw fieldError(fieldName, `${fieldName} must be a string`, 'invalid');
  }

  const trimmed = value.trim();
  if (!trimmed) {
    return undefined;
  }

  if (trimmed.length > maxLength) {
    throw fieldError(fieldName, `${fieldName} must be ${maxLength} characters or fewer`, 'invalid');
  }

  return trimmed;
}

export function parsePinnedFlag(value: unknown): boolean | undefined {
  if (value === undefined) return undefined;
  if (typeof value !== 'boolean') {
    throw fieldError('isPinned', 'isPinned must be a boolean', 'invalid');
  }
  return value;
}

export function parsePostVisibility(value: unknown): PostVisibility | undefined {
  if (value === undefined || value === null || value === '') return undefined;
  if (typeof value !== 'string') {
    throw fieldError('visibility', 'visibility must be a string', 'invalid');
  }

  switch (value.trim().toLowerCase()) {
    case 'public':
      return PostVisibility.PUBLIC;
    case 'team':
      return PostVisibility.TEAM;
    case 'private':
      return PostVisibility.PRIVATE;
    default:
      throw fieldError('visibility', 'visibility must be public, team, or private', 'invalid');
  }
}

export function toVisibilityType(visibility: PostVisibility): 'public' | 'team' | 'private' {
  switch (visibility) {
    case PostVisibility.TEAM:
      return 'team';
    case PostVisibility.PRIVATE:
      return 'private';
    case PostVisibility.PUBLIC:
    default:
      return 'public';
  }
}

export function buildDefaultHighlightTitle(finalized: CloudflareVideoFinalizeResponse): string {
  const rawName = finalized.name ?? finalized.metadata.originalFileName;
  const baseName = rawName.split('/').pop() ?? rawName;
  return (
    baseName
      .replace(/\.[^.]+$/, '')
      .replace(/[_-]+/g, ' ')
      .trim() || 'Highlight Video'
  );
}

export async function fetchCloudflareFinalizedVideo(
  userId: string,
  cloudflareVideoId: string,
  accountId: string,
  apiToken: string,
  customerCode: string | undefined
): Promise<CloudflareVideoFinalizeResponse> {
  const response = await fetch(
    `${CLOUDFLARE_API_BASE_URL}/accounts/${accountId}/stream/${cloudflareVideoId}`,
    {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${apiToken}`,
        'Content-Type': 'application/json',
      },
    }
  );

  let responseBody: Record<string, unknown> | null;
  try {
    responseBody = (await response.json()) as Record<string, unknown>;
  } catch {
    responseBody = null;
  }

  if (!response.ok || responseBody?.['success'] === false) {
    const errors = Array.isArray(responseBody?.['errors'])
      ? (responseBody?.['errors'] as Array<Record<string, unknown>>)
      : [];
    const errorMessage =
      typeof errors[0]?.['message'] === 'string'
        ? (errors[0]['message'] as string)
        : `status ${response.status}`;

    logger.error('Cloudflare finalize fetch failed', {
      userId,
      cloudflareVideoId,
      error: errorMessage,
    });

    throw new Error(`Cloudflare finalize failed: ${errorMessage}`);
  }

  const payload =
    responseBody && typeof responseBody['result'] === 'object' && responseBody['result'] !== null
      ? (responseBody['result'] as Record<string, unknown>)
      : null;

  if (!payload) {
    logger.error('Cloudflare finalize returned no video payload', {
      userId,
      cloudflareVideoId,
    });

    throw new Error('Cloudflare finalize returned no video payload');
  }

  const finalized = normalizeCloudflareVideoForClient(cloudflareVideoId, payload, customerCode);

  if (finalized.metadata.userId && finalized.metadata.userId !== userId) {
    throw forbiddenError('owner');
  }

  return finalized;
}
