source "https://rubygems.org"

gem "fastlane", "~> 2.220"
gem "fastlane-plugin-firebase_app_distribution", "~> 0.9"
gem "multi_json", ">= 1.14.1"

pluginfile_path = File.join(__dir__, "fastlane", "Pluginfile")
eval_gemfile("fastlane/Pluginfile") if File.exist?(pluginfile_path)
