/**
 * @fileoverview Unit Tests — ExportService (CSV & PDF Generation)
 * @module @nxt1/backend/modules/agent/services
 *
 * Tests CSV generation (UTF-8 BOM, column headers, row data) and
 * PDF generation (valid PDF buffer output).
 */

import { describe, expect, it, beforeEach } from 'vitest';
import ExcelJS from 'exceljs';
import { ExportService } from '../export.service.js';
import type {
  CsvExportOptions,
  PdfExportOptions,
  XlsxExportOptions,
  ExportSection,
} from '../export.service.js';

const TINY_PNG_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGNgAAAAAgAB4iG8MwAAAABJRU5ErkJggg==';

// ── Helpers ──────────────────────────────────────────────────────────────────

const sampleColumns = [
  { key: 'name', label: 'Name' },
  { key: 'sport', label: 'Sport' },
  { key: 'gpa', label: 'GPA' },
] as const;

const sampleRows = [
  ['John Doe', 'Football', '3.8'],
  ['Jane Smith', 'Basketball', '3.9'],
  ['Alex Johnson', 'Soccer', '3.5'],
];

function csvOpts(overrides?: Partial<CsvExportOptions>): CsvExportOptions {
  return {
    columns: [...sampleColumns],
    rows: [...sampleRows],
    ...overrides,
  };
}

function pdfOpts(overrides?: Partial<PdfExportOptions>): PdfExportOptions {
  return {
    title: 'Test Report',
    description: 'A test PDF document.',
    includeTable: true,
    columns: [...sampleColumns],
    rows: [...sampleRows],
    ...overrides,
  };
}

function xlsxOpts(overrides?: Partial<XlsxExportOptions>): XlsxExportOptions {
  return {
    title: 'Top Prospects 2026',
    description: 'Generated by Agent X for staff review.',
    sheetName: 'Prospects',
    columns: [...sampleColumns],
    rows: [...sampleRows],
    ...overrides,
  };
}

function multiSectionContent(): readonly ExportSection[] {
  return [
    {
      title: 'Openers',
      description: 'First 15 script',
      bulletPoints: ['Tempo start', 'Protect launch point'],
      columns: [
        { key: 'play', label: 'Play' },
        { key: 'call', label: 'Call' },
      ],
      rows: [
        ['IZ', '11 Gun'],
        ['Boot', 'Trips Rt'],
      ],
    },
    {
      title: '3rd Down Menu',
      bodyParagraphs: ['Lean on motion to ID leverage before the snap.'],
      columns: [
        { key: 'distance', label: 'Distance' },
        { key: 'concept', label: 'Concept' },
      ],
      rows: [
        ['3rd & 4-6', 'Mesh'],
        ['3rd & 7+', 'Dagger'],
      ],
    },
  ] as const;
}

function callsheetSectionContent(): readonly ExportSection[] {
  return [
    {
      title: '1st & 10 - Base Run Game',
      columns: [
        { key: 'play', label: 'Play Name' },
        { key: 'formation', label: 'Formation' },
        { key: 'type', label: 'Type' },
        { key: 'notes', label: 'Coaching Notes' },
      ],
      rows: [
        ['Inside Zone', '11 Personnel Pro', 'Run', 'Hit crease behind double teams.'],
        ['Outside Zone', '11 Personnel Spread', 'Run', 'Press landmark, bend if sealed.'],
      ],
    },
    {
      title: '1st & 10 - Base Pass Game',
      columns: [
        { key: 'play', label: 'Play Name' },
        { key: 'formation', label: 'Formation' },
        { key: 'concept', label: 'Concept' },
        { key: 'notes', label: 'Coaching Notes' },
      ],
      rows: [
        ['Mesh', '11 Personnel Shotgun', 'Crossing Routes', 'Read hi-low over hook defenders.'],
      ],
    },
    {
      title: '2nd & Short (1-3 YDS)',
      columns: [
        { key: 'play', label: 'Play Name' },
        { key: 'formation', label: 'Formation' },
        { key: 'concept', label: 'Concept' },
        { key: 'notes', label: 'Coaching Notes' },
      ],
      rows: [['Power G', '22 Personnel I-Form', 'Gap Scheme', 'Trust puller and fall forward.']],
    },
  ] as const;
}

// ── Tests ────────────────────────────────────────────────────────────────────

describe('ExportService', () => {
  let service: ExportService;

  beforeEach(() => {
    service = new ExportService();
  });

  // ── CSV ──────────────────────────────────────────────────────────────────

  describe('generateCsv', () => {
    it('should return a Buffer', () => {
      const result = service.generateCsv(csvOpts());
      expect(result).toBeInstanceOf(Buffer);
    });

    it('should start with UTF-8 BOM for Excel compatibility', () => {
      const result = service.generateCsv(csvOpts());
      const str = result.toString('utf-8');
      expect(str.charCodeAt(0)).toBe(0xfeff);
    });

    it('should include column labels as header row', () => {
      const result = service.generateCsv(csvOpts());
      const str = result.toString('utf-8');
      const firstLine = str.split('\n')[0];
      expect(firstLine).toContain('"Name"');
      expect(firstLine).toContain('"Sport"');
      expect(firstLine).toContain('"GPA"');
    });

    it('should include all data rows', () => {
      const result = service.generateCsv(csvOpts());
      const str = result.toString('utf-8');
      const lines = str.trim().split('\n');
      // 1 header + 3 data rows
      expect(lines).toHaveLength(4);
      expect(str).toContain('John Doe');
      expect(str).toContain('Jane Smith');
      expect(str).toContain('Alex Johnson');
    });

    it('should handle empty rows', () => {
      const result = service.generateCsv(csvOpts({ rows: [] }));
      const str = result.toString('utf-8');
      const lines = str.trim().split('\n');
      // Only header row
      expect(lines).toHaveLength(1);
      expect(str).toContain('"Name"');
    });

    it('should handle single column', () => {
      const result = service.generateCsv(
        csvOpts({
          columns: [{ key: 'id', label: 'ID' }],
          rows: [['1'], ['2'], ['3']],
        })
      );
      const str = result.toString('utf-8');
      expect(str).toContain('"ID"');
      expect(str).toContain('"1"');
    });

    it('should quote values containing commas', () => {
      const result = service.generateCsv(
        csvOpts({
          columns: [{ key: 'name', label: 'Name' }],
          rows: [['Doe, John']],
        })
      );
      const str = result.toString('utf-8');
      expect(str).toContain('"Doe, John"');
    });

    it('should serialize multi-section CSV exports with section titles and repeated headers', () => {
      const result = service.generateCsv({
        title: 'Game Plan Export',
        description: 'Weekly offensive menu',
        sections: multiSectionContent(),
      });

      const str = result.toString('utf-8');
      expect(str).toContain('Game Plan Export');
      expect(str).toContain('Openers');
      expect(str).toContain('3rd Down Menu');
      expect(str).toContain('"Play","Call"');
      expect(str).toContain('"Distance","Concept"');
      expect(str).toContain('Lean on motion to ID leverage before the snap.');
    });
  });

  // ── XLSX ─────────────────────────────────────────────────────────────────

  describe('generateXlsx', () => {
    it('should return a Buffer', async () => {
      const result = await service.generateXlsx(xlsxOpts());
      expect(result).toBeInstanceOf(Buffer);
    });

    it('should generate a readable workbook with the expected worksheet name', async () => {
      const result = await service.generateXlsx(xlsxOpts());
      const workbook = new ExcelJS.Workbook();

      await workbook.xlsx.load(result);

      expect(workbook.worksheets).toHaveLength(1);
      expect(workbook.worksheets[0]?.name).toBe('Prospects');
    });

    it('should include the configured title, headers, and first data row', async () => {
      const result = await service.generateXlsx(xlsxOpts());
      const workbook = new ExcelJS.Workbook();

      await workbook.xlsx.load(result);

      const worksheet = workbook.getWorksheet('Prospects');
      expect(worksheet).toBeDefined();
      expect(worksheet?.getCell('A1').value).toBe('Top Prospects 2026');
      expect(worksheet?.getCell('A3').value).toBe('Name');
      expect(worksheet?.getCell('B3').value).toBe('Sport');
      expect(worksheet?.getCell('A4').value).toBe('John Doe');
      expect(worksheet?.getCell('B4').value).toBe('Football');
      expect((worksheet as { autoFilter?: string } | undefined)?.autoFilter).toBe('A3:C3');
      expect(worksheet?.views.at(0)?.ySplit).toBe(3);
    });

    it('should embed document-level chart images in XLSX workbooks', async () => {
      const result = await service.generateXlsx(
        xlsxOpts({
          imageUrls: [TINY_PNG_DATA_URL],
        })
      );

      expect(result.toString('binary')).toContain('xl/media/image1.png');
    });

    it('should embed section-level chart images in XLSX workbooks', async () => {
      const result = await service.generateXlsx(
        xlsxOpts({
          sections: [
            {
              title: 'Run/Pass Tendencies',
              columns: [{ key: 'tendency', label: 'Tendency' }],
              rows: [['Heavy pistol on 2nd and medium']],
              imageUrls: [TINY_PNG_DATA_URL],
            },
          ],
        })
      );

      expect(result.toString('binary')).toContain('xl/media/image1.png');
    });

    it('should render multi-section workbook content in order on one worksheet', async () => {
      const result = await service.generateXlsx({
        title: 'Callsheet Export',
        description: 'Coach-grade script layout',
        sheetName: 'Callsheet',
        columns: [...sampleColumns],
        rows: [...sampleRows],
        sections: multiSectionContent(),
      });
      const workbook = new ExcelJS.Workbook();

      await workbook.xlsx.load(result);

      const worksheet = workbook.getWorksheet('Callsheet');
      expect(worksheet).toBeDefined();
      expect(worksheet?.getCell('A1').value).toBe('Callsheet Export');
      expect(worksheet?.getCell('A3').value).toBe('Openers');
      expect(worksheet?.getCell('A7').value).toBe('Play');
      expect(worksheet?.getCell('A8').value).toBe('IZ');
      expect(worksheet?.getCell('A11').value).toBe('3rd Down Menu');
      expect(worksheet?.getCell('A13').value).toBe('Distance');
      expect(worksheet?.getCell('A14').value).toBe('3rd & 4-6');
      expect(worksheet?.getCell('A3').fill).toBeDefined();
    });

    it('should preserve print settings for section-based callsheet exports', async () => {
      const result = await service.generateXlsx({
        title: 'Callsheet Export',
        description: 'Coach-grade script layout',
        sheetName: 'Callsheet',
        columns: [...sampleColumns],
        rows: [...sampleRows],
        sections: multiSectionContent(),
        pageOrientation: 'landscape',
        pageSize: 'LEGAL',
      });
      const workbook = new ExcelJS.Workbook();

      await workbook.xlsx.load(result);

      const worksheet = workbook.getWorksheet('Callsheet');
      expect(worksheet).toBeDefined();
      expect(worksheet?.pageSetup.orientation).toBe('landscape');
      expect(worksheet?.pageSetup.paperSize).toBe(5);
      expect(worksheet?.pageSetup.margins.left).toBe(0.25);
      expect(worksheet?.pageSetup.fitToWidth).toBe(1);
    });

    it('should render multi_column_grid sections into side-by-side panels', async () => {
      const result = await service.generateXlsx({
        title: 'Crown Point Bulldogs - Game Callsheet',
        description: 'Game: Crown Point Bulldogs vs. Lake Central Indians',
        sheetName: 'Callsheet',
        columns: [...sampleColumns],
        rows: [...sampleRows],
        sections: callsheetSectionContent(),
        layoutMode: 'multi_column_grid',
        pageOrientation: 'landscape',
        pageSize: 'LEGAL',
      });
      const workbook = new ExcelJS.Workbook();

      await workbook.xlsx.load(result);

      const worksheet = workbook.getWorksheet('Callsheet');
      expect(worksheet).toBeDefined();
      expect(worksheet?.getCell('A1').value).toBe('Crown Point Bulldogs - Game Callsheet');
      expect(worksheet?.getCell('A4').value).toBe('1ST & 10 - BASE RUN GAME');
      expect(worksheet?.getCell('F4').value).toBe('1ST & 10 - BASE PASS GAME');
      expect(worksheet?.getCell('K4').value).toBe('2ND & SHORT (1-3 YDS)');
      expect(worksheet?.getCell('A5').value).toBe('Play Name');
      expect(worksheet?.getCell('B5').value).toBe('Formation');
      expect(worksheet?.getCell('C5').value).toBe('Type');
      expect(worksheet?.getCell('D5').value).toBe('Coaching Notes');
      expect(worksheet?.getCell('A6').value).toBe('Inside Zone');
      expect(worksheet?.getCell('F6').value).toBe('Mesh');
      expect(worksheet?.getCell('K6').value).toBe('Power G');
      expect(worksheet?.getCell('A5').value).not.toBe('#');
      expect(worksheet?.getCell('D5').value).not.toBe('Details');
    });

    it('should size standard worksheet columns and row heights from long wrapped content', async () => {
      const result = await service.generateXlsx({
        title: 'Long Notes Export',
        description:
          'This description is intentionally long so the merged title block and body sizing logic has to allocate more vertical space than a one-line export would need.',
        sheetName: 'LongNotes',
        columns: [
          { key: 'play', label: 'Play' },
          { key: 'notes', label: 'Detailed Coaching Notes' },
        ],
        rows: [
          [
            'Mesh',
            'Work across the field with patient footwork, confirm leverage before the break, and coach the quarterback through progression timing versus rotation so the note cell has to wrap across multiple visual lines.',
          ],
        ],
      });
      const workbook = new ExcelJS.Workbook();

      await workbook.xlsx.load(result);

      const worksheet = workbook.getWorksheet('LongNotes');
      expect(worksheet).toBeDefined();
      expect(worksheet?.getColumn(2).width ?? 0).toBeGreaterThan(
        worksheet?.getColumn(1).width ?? 0
      );
      expect(worksheet?.getRow(2).height ?? 0).toBeGreaterThan(20);
      expect(worksheet?.getRow(4).height ?? 0).toBeGreaterThan(18);
    });

    it('should widen callsheet note columns when panel content is longer', async () => {
      const result = await service.generateXlsx({
        title: 'Detailed Callsheet',
        description: 'Width regression coverage',
        sheetName: 'Callsheet',
        columns: [...sampleColumns],
        rows: [...sampleRows],
        sections: [
          {
            title: '1st & 10 - Script',
            columns: [
              { key: 'play', label: 'Play Name' },
              { key: 'formation', label: 'Formation' },
              { key: 'type', label: 'Type' },
              { key: 'notes', label: 'Detailed Coaching Notes' },
            ],
            rows: [
              [
                'Counter Trey',
                '11 Personnel Doubles',
                'Run',
                'Stress backside linebacker eyes, press downhill before bend, and alert the quarterback to kill the play versus overloaded front structure.',
              ],
            ],
          },
        ],
        layoutMode: 'multi_column_grid',
        pageOrientation: 'landscape',
        pageSize: 'LEGAL',
      });
      const workbook = new ExcelJS.Workbook();

      await workbook.xlsx.load(result);

      const worksheet = workbook.getWorksheet('Callsheet');
      expect(worksheet).toBeDefined();
      expect(worksheet?.getColumn(4).width ?? 0).toBeGreaterThan(
        worksheet?.getColumn(1).width ?? 0
      );
      expect(worksheet?.getRow(6).height ?? 0).toBeGreaterThan(18);
    });
  });

  // ── PDF ──────────────────────────────────────────────────────────────────

  describe('generatePdf', () => {
    it('should return a Buffer', async () => {
      const result = await service.generatePdf(pdfOpts());
      expect(result).toBeInstanceOf(Buffer);
    });

    it('should generate a valid PDF (starts with %PDF header)', async () => {
      const result = await service.generatePdf(pdfOpts());
      const header = result.subarray(0, 5).toString('ascii');
      expect(header).toBe('%PDF-');
    });

    it('should produce non-empty output', async () => {
      const result = await service.generatePdf(pdfOpts());
      expect(result.length).toBeGreaterThan(100);
    });

    it('should generate PDF with only body paragraphs (no table)', async () => {
      const result = await service.generatePdf(
        pdfOpts({
          includeTable: false,
          columns: undefined,
          rows: undefined,
          bodyParagraphs: ['This is paragraph one.', 'This is paragraph two.'],
        })
      );
      const header = result.subarray(0, 5).toString('ascii');
      expect(header).toBe('%PDF-');
    });

    it('should generate PDF with only bullet points', async () => {
      const result = await service.generatePdf(
        pdfOpts({
          includeTable: false,
          columns: undefined,
          rows: undefined,
          bulletPoints: ['Point A', 'Point B', 'Point C'],
        })
      );
      expect(result).toBeInstanceOf(Buffer);
      expect(result.length).toBeGreaterThan(100);
    });

    it('should generate PDF with all sections combined', async () => {
      const result = await service.generatePdf(
        pdfOpts({
          bodyParagraphs: ['Intro paragraph.'],
          bulletPoints: ['First bullet', 'Second bullet'],
          includeTable: true,
        })
      );
      const header = result.subarray(0, 5).toString('ascii');
      expect(header).toBe('%PDF-');
    });

    it('should embed provided image URLs into PDF', async () => {
      const result = await service.generatePdf(
        pdfOpts({
          includeTable: false,
          columns: undefined,
          rows: undefined,
          imageUrls: [TINY_PNG_DATA_URL],
        })
      );
      const header = result.subarray(0, 5).toString('ascii');
      expect(header).toBe('%PDF-');
      expect(result.length).toBeGreaterThan(100);
    });

    it('should use custom footer text when provided', async () => {
      const result = await service.generatePdf(pdfOpts({ footerText: 'Custom Footer' }));
      // Can't easily inspect rendered text, but should not throw
      expect(result).toBeInstanceOf(Buffer);
    });

    it('should handle title-only PDF (no table, no body, no bullets)', async () => {
      const result = await service.generatePdf(
        pdfOpts({
          includeTable: false,
          columns: undefined,
          rows: undefined,
          bodyParagraphs: undefined,
          bulletPoints: undefined,
        })
      );
      const header = result.subarray(0, 5).toString('ascii');
      expect(header).toBe('%PDF-');
    });

    it('should handle escaped newlines and markdown-like bold content', async () => {
      const result = await service.generatePdf(
        pdfOpts({
          includeTable: false,
          columns: undefined,
          rows: undefined,
          bodyParagraphs: [
            'Scouting Report: Line one\\n\\n**Offensive Identity**: Motion offense with pace.',
          ],
          bulletPoints: ['**Priority**: Control tempo', '## Adjustments'],
        })
      );
      const header = result.subarray(0, 5).toString('ascii');
      expect(header).toBe('%PDF-');
      expect(result.length).toBeGreaterThan(100);
    });

    it('should render inline numbered paragraphs as readable ordered list content', async () => {
      const result = await service.generatePdf(
        pdfOpts({
          includeTable: false,
          columns: undefined,
          rows: undefined,
          bodyParagraphs: [
            '1. Motion offense spacing. 2. Read-and-react pick-and-roll decisions. 3. Transition tempo control.',
          ],
        })
      );
      const header = result.subarray(0, 5).toString('ascii');
      expect(header).toBe('%PDF-');
      expect(result.length).toBeGreaterThan(100);
    });

    it('should generate PDF with multiple ordered sections', async () => {
      const result = await service.generatePdf(
        pdfOpts({
          includeTable: false,
          columns: undefined,
          rows: undefined,
          sections: multiSectionContent(),
        })
      );
      const header = result.subarray(0, 5).toString('ascii');
      expect(header).toBe('%PDF-');
      expect(result.length).toBeGreaterThan(100);
    });

    it('should generate landscape PDF exports without crashing on background rendering', async () => {
      const result = await service.generatePdf(
        pdfOpts({
          includeTable: false,
          columns: undefined,
          rows: undefined,
          theme: 'light',
          pageOrientation: 'landscape',
          sections: [
            {
              title: 'Offensive Game Plan',
              description: 'Landscape regression coverage',
              bodyParagraphs: [
                'IDENTITY & TEMPO: Spread-based passing attack with tempo.',
                'OPENING SCRIPT (First 3 Series):',
                '• Series 1: Boot weak off split action.',
              ],
              bulletPoints: [
                'Featured Plays: Y-Cross, Smash, Slot Fade',
                '3rd-Down Package: Spread, TE Seam/Flat option',
              ],
            },
          ],
        })
      );
      const header = result.subarray(0, 5).toString('ascii');
      expect(header).toBe('%PDF-');
      expect(result.length).toBeGreaterThan(100);
    });

    it('should generate multi-column PDF exports with watermarks and clickable link text', async () => {
      const result = await service.generatePdf(
        pdfOpts({
          includeTable: false,
          columns: undefined,
          rows: undefined,
          theme: 'light',
          layoutMode: 'multi_column_grid',
          pageOrientation: 'landscape',
          watermarkText: 'DRAFT',
          sections: [
            {
              title: 'Opponent Strengths',
              gridColumn: 1,
              bodyParagraphs: ['Film: https://example.com/film/clip-123'],
              bulletPoints: ['Power run game', 'Slot receiver creates space'],
            },
            {
              title: 'Our Answers',
              gridColumn: 2,
              bodyParagraphs: ['Answer with tempo and 4-wide spacing.'],
              bulletPoints: ['Check to mesh', 'Attack boundary leverage'],
            },
            {
              title: 'Critical Reminders',
              gridColumn: 3,
              bodyParagraphs: ['No substitution errors after explosives.'],
            },
          ],
        })
      );
      const header = result.subarray(0, 5).toString('ascii');
      expect(header).toBe('%PDF-');
      expect(result.length).toBeGreaterThan(100);
    });
  });
});
