/**
 * @fileoverview File Download Adapter — Platform-Agnostic Interface
 * @module @nxt1/core/storage
 *
 * ⭐ THIS FILE IS 100% PORTABLE - NO PLATFORM DEPENDENCIES ⭐
 *
 * Defines a platform-agnostic interface for downloading files from a URL.
 * The web and mobile apps each provide their own implementation:
 *
 * - **Web**: Uses an anchor tag with `download` attribute or `window.open`.
 * - **Mobile (Capacitor)**: Uses `@capacitor/filesystem` to write the file
 *   and `@capacitor-community/file-opener` to open it in the native viewer.
 *
 * This ensures that files generated by Agent X (PDFs, CSVs) download and
 * open correctly on all platforms — no silent failures in iOS/Android WebViews.
 *
 * @example Web
 * ```typescript
 * const downloader: FileDownloadAdapter = {
 *   download: async ({ url, fileName, mimeType }) => {
 *     const a = document.createElement('a');
 *     a.href = url;
 *     a.download = fileName;
 *     a.click();
 *   },
 * };
 * ```
 *
 * @example Capacitor
 * ```typescript
 * import { Filesystem, Directory } from '@capacitor/filesystem';
 * import { FileOpener } from '@capacitor-community/file-opener';
 *
 * const downloader: FileDownloadAdapter = {
 *   download: async ({ url, fileName, mimeType }) => {
 *     const result = await Filesystem.downloadFile({
 *       url,
 *       path: fileName,
 *       directory: Directory.Cache,
 *     });
 *     await FileOpener.open({ filePath: result.path!, contentType: mimeType });
 *   },
 * };
 * ```
 */

/**
 * Options for a single file download request.
 */
export interface FileDownloadOptions {
  /** The public URL of the file to download (signed URL or public CDN). */
  readonly url: string;
  /** Suggested file name including extension (e.g. "report.pdf"). */
  readonly fileName: string;
  /** MIME type of the file (e.g. "application/pdf", "text/csv"). */
  readonly mimeType: string;
}

/**
 * Platform-agnostic adapter for downloading and opening files.
 * Implemented differently on web vs. native mobile.
 */
export interface FileDownloadAdapter {
  /**
   * Download a file and present it to the user.
   * On web this triggers a browser download. On mobile this saves to
   * the device cache and opens the native file viewer.
   */
  download(options: FileDownloadOptions): Promise<void>;
}
