/**
 * @fileoverview Platform Registry & Category Display Info
 * @module @nxt1/core/platforms
 *
 * Authoritative list of every third-party platform a user can connect to their
 * NXT1 profile — sport-aware, category-grouped, and connection-type-aware.
 *
 * Used by:
 *   - Onboarding link-sources step  (connect your accounts)
 *   - Edit-profile connected-sources section
 *   - Agent X / Firecrawl data-sync (PLATFORM_REGISTRY lookup)
 *   - Intel report citations         (faviconUrl resolution)
 *   - Profile & Team "Connected" display chips
 *
 * ⭐ PURE DATA — No framework dependencies, no side effects.
 */

import type { PlatformDefinition, PlatformCategory } from './platform.types';

/**
 * All available platforms, categorized and sport-aware.
 * Sports use base names (e.g. 'football' not 'Football').
 * Empty sports array = available for all sports.
 *
 * ⭐ PURE DATA - No dependencies
 */
export const PLATFORM_REGISTRY: readonly PlatformDefinition[] = [
  // ---- Social (global — one link across all sports) ----
  {
    platform: 'instagram',
    label: 'Instagram',
    icon: 'link',
    connectionType: 'link',
    category: 'social',
    scope: 'global',
    sports: [],
    placeholder: 'username',
  },
  {
    platform: 'twitter',
    label: 'X',
    icon: 'link',
    connectionType: 'link',
    category: 'social',
    scope: 'global',
    sports: [],
    placeholder: '@username',
  },
  {
    platform: 'tiktok',
    label: 'TikTok',
    icon: 'link',
    connectionType: 'link',
    category: 'social',
    scope: 'global',
    sports: [],
    placeholder: '@username',
  },
  {
    platform: 'youtube',
    label: 'YouTube',
    icon: 'link',
    connectionType: 'link',
    category: 'social',
    scope: 'global',
    sports: [],
    placeholder: 'Channel URL',
  },
  {
    platform: 'facebook',
    label: 'Facebook',
    icon: 'link',
    connectionType: 'link',
    category: 'social',
    scope: 'global',
    sports: [],
    placeholder: 'Profile URL',
  },

  // ---- Film & Highlights (sport-scoped — different per sport) ----
  {
    platform: 'hudl',
    label: 'Hudl',
    icon: 'link',
    connectionType: 'link',
    category: 'film',
    scope: 'sport',
    sports: [
      'football',
      'basketball',
      'soccer',
      'lacrosse',
      'volleyball',
      'field_hockey',
      'baseball',
      'softball',
      'wrestling',
      'ice_hockey',
    ],
    placeholder: 'Hudl profile URL',
  },
  {
    platform: 'krossover',
    label: 'Krossover',
    icon: 'link',
    connectionType: 'link',
    category: 'film',
    scope: 'sport',
    sports: ['basketball', 'soccer', 'volleyball', 'lacrosse', 'ice_hockey', 'field_hockey'],
    placeholder: 'Krossover profile URL',
  },
  {
    platform: 'veo',
    label: 'Veo',
    icon: 'link',
    connectionType: 'link',
    category: 'film',
    scope: 'sport',
    sports: ['soccer', 'lacrosse', 'field_hockey', 'basketball', 'volleyball'],
    placeholder: 'Veo profile URL',
  },
  {
    platform: 'ballertv',
    label: 'BallerTV',
    icon: 'link',
    connectionType: 'link',
    category: 'film',
    scope: 'sport',
    sports: ['basketball', 'volleyball', 'wrestling', 'baseball', 'softball'],
    placeholder: 'BallerTV profile URL',
  },
  {
    platform: 'nfhsnetwork',
    label: 'NFHS Network',
    icon: 'link',
    connectionType: 'link',
    category: 'film',
    scope: 'sport',
    sports: [],
    placeholder: 'NFHS Network profile URL',
  },
  {
    platform: 'sportsengineplay',
    label: 'SportsEngine Play',
    icon: 'link',
    connectionType: 'link',
    category: 'film',
    scope: 'sport',
    sports: [],
    placeholder: 'SportsEngine Play profile URL',
  },
  {
    platform: 'vimeo',
    label: 'Vimeo',
    icon: 'link',
    connectionType: 'link',
    category: 'film',
    scope: 'global',
    sports: [],
    placeholder: 'Vimeo video or profile URL',
  },

  // ---- Recruiting (sport-scoped) ----
  {
    platform: 'ncsa',
    label: 'NCSA',
    icon: 'link',
    connectionType: 'link',
    category: 'recruiting',
    scope: 'sport',
    sports: [],
    placeholder: 'NCSA profile URL',
  },
  {
    platform: 'fieldlevel',
    label: 'FieldLevel',
    icon: 'link',
    connectionType: 'link',
    category: 'recruiting',
    scope: 'sport',
    sports: [],
    placeholder: 'FieldLevel profile URL',
  },
  {
    platform: 'captainu',
    label: 'CaptainU',
    icon: 'link',
    connectionType: 'link',
    category: 'recruiting',
    scope: 'sport',
    sports: [],
    placeholder: 'CaptainU profile URL',
  },
  {
    platform: 'sportsrecruits',
    label: 'SportsRecruits',
    icon: 'link',
    connectionType: 'link',
    category: 'recruiting',
    scope: 'sport',
    sports: [],
    placeholder: 'SportsRecruits profile URL',
  },
  {
    platform: 'streamlineathletes',
    label: 'Streamline Athletes',
    icon: 'link',
    connectionType: 'link',
    category: 'recruiting',
    scope: 'sport',
    sports: [],
    placeholder: 'Streamline Athletes profile URL',
  },
  {
    platform: 'recruitlook',
    label: 'RecruitLook',
    icon: 'link',
    connectionType: 'link',
    category: 'recruiting',
    scope: 'sport',
    sports: [],
    placeholder: 'RecruitLook profile URL',
  },
  {
    platform: 'collegeathtrack',
    label: 'College Ath Track',
    icon: 'link',
    connectionType: 'link',
    category: 'recruiting',
    scope: 'sport',
    sports: ['track_field', 'cross_country'],
    placeholder: 'College Athletic Track profile URL',
  },
  {
    platform: 'connectlax',
    label: 'ConnectLAX',
    icon: 'link',
    connectionType: 'link',
    category: 'recruiting',
    scope: 'sport',
    sports: ['lacrosse'],
    placeholder: 'ConnectLAX profile URL',
  },
  {
    platform: 'imlcarecruits',
    label: 'IMLCA Recruits',
    icon: 'link',
    connectionType: 'link',
    category: 'recruiting',
    scope: 'sport',
    sports: ['lacrosse'],
    placeholder: 'IMLCA Recruits profile URL',
  },
  {
    platform: 'berecruited',
    label: 'BeRecruited',
    icon: 'link',
    connectionType: 'link',
    category: 'recruiting',
    scope: 'sport',
    sports: [],
    placeholder: 'BeRecruited profile URL',
  },

  // ---- Stats (sport-scoped — different profiles per sport) ----
  {
    platform: 'maxpreps',
    label: 'MaxPreps',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: [
      'football',
      'basketball',
      'baseball',
      'softball',
      'soccer',
      'volleyball',
      'lacrosse',
      'wrestling',
      'track_field',
      'cross_country',
      'tennis',
      'golf',
      'swimming_diving',
      'field_hockey',
      'water_polo',
    ],
    placeholder: 'MaxPreps profile URL',
  },
  {
    platform: 'perfectgame',
    label: 'Perfect Game',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['baseball', 'softball'],
    placeholder: 'Perfect Game profile URL',
  },
  {
    platform: 'prepbaseballreport',
    label: 'Prep Baseball Report',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['baseball'],
    placeholder: 'PBR profile URL',
  },
  {
    platform: '247sports',
    label: '247Sports',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['football', 'basketball'],
    placeholder: '247Sports profile URL',
  },
  {
    platform: 'rivals',
    label: 'Rivals',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['football', 'basketball'],
    placeholder: 'Rivals profile URL',
  },
  {
    platform: 'on3',
    label: 'On3',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['football', 'basketball', 'baseball'],
    placeholder: 'On3 profile URL',
  },
  {
    platform: 'gamechanger',
    label: 'GameChanger',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['baseball', 'softball', 'basketball', 'volleyball'],
    placeholder: 'GameChanger team or profile URL',
  },
  {
    platform: 'scorebooklive',
    label: 'Scorebook Live',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['football', 'basketball', 'baseball', 'softball', 'soccer', 'volleyball'],
    placeholder: 'Scorebook Live profile URL',
  },
  {
    platform: 'athletic',
    label: 'Athletic.net',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['track_field', 'cross_country'],
    placeholder: 'Athletic.net profile URL',
  },
  {
    platform: 'milesplit',
    label: 'MileSplit',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['track_field', 'cross_country'],
    placeholder: 'MileSplit profile URL',
  },
  {
    platform: 'swimcloud',
    label: 'SwimCloud',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['swimming_diving'],
    placeholder: 'SwimCloud profile URL',
  },
  {
    platform: 'trackwrestling',
    label: 'TrackWrestling',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['wrestling'],
    placeholder: 'TrackWrestling profile URL',
  },
  {
    platform: 'tennisrecruiting',
    label: 'TennisRecruiting.net',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['tennis'],
    placeholder: 'TennisRecruiting profile URL',
  },
  {
    platform: 'usta',
    label: 'USTA',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['tennis'],
    placeholder: 'USTA profile URL',
  },
  {
    platform: 'utr',
    label: 'UTR Sports',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['tennis'],
    placeholder: 'UTR Sports profile URL',
  },
  {
    platform: 'prepsoccer',
    label: 'PrepSoccer',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['soccer'],
    placeholder: 'PrepSoccer profile URL',
  },
  {
    platform: 'usyouthsoccer',
    label: 'US Youth Soccer',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['soccer'],
    placeholder: 'US Youth Soccer profile URL',
  },
  {
    platform: 'golfstat',
    label: 'Golfstat',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['golf'],
    placeholder: 'Golfstat profile URL',
  },
  {
    platform: 'juniorgolf',
    label: 'Junior Golf Scoreboard',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['golf'],
    placeholder: 'Junior Golf profile URL',
  },
  {
    platform: 'prephoops',
    label: 'PrepHoops',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['basketball'],
    placeholder: 'PrepHoops player profile URL',
  },
  {
    platform: 'prepfootball',
    label: 'Prep Football',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['football'],
    placeholder: 'Prep Football player profile URL',
  },
  {
    platform: 'topdrawersoccer',
    label: 'TopDrawerSoccer',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['soccer'],
    placeholder: 'TopDrawerSoccer player profile URL',
  },
  {
    platform: 'prepvolleyball',
    label: 'PrepVolleyball',
    icon: 'link',
    connectionType: 'link',
    category: 'stats',
    scope: 'sport',
    sports: ['volleyball'],
    placeholder: 'PrepVolleyball player profile URL',
  },

  // ---- Schedule ----
  {
    platform: 'maxpreps',
    label: 'MaxPreps',
    icon: 'link',
    connectionType: 'link',
    category: 'schedule',
    scope: 'sport',
    sports: [
      'football',
      'basketball',
      'baseball',
      'softball',
      'soccer',
      'volleyball',
      'lacrosse',
      'wrestling',
      'track_field',
      'cross_country',
      'tennis',
      'golf',
      'swimming_diving',
      'field_hockey',
      'water_polo',
    ],
    placeholder: 'MaxPreps team or schedule URL',
  },
  {
    platform: 'gamechanger',
    label: 'GameChanger',
    icon: 'link',
    connectionType: 'link',
    category: 'schedule',
    scope: 'sport',
    sports: ['baseball', 'softball', 'basketball', 'volleyball'],
    placeholder: 'GameChanger team or schedule URL',
  },
  {
    platform: 'scorebooklive',
    label: 'Scorebook Live',
    icon: 'link',
    connectionType: 'link',
    category: 'schedule',
    scope: 'sport',
    sports: ['football', 'basketball', 'baseball', 'softball', 'soccer', 'volleyball'],
    placeholder: 'Scorebook Live team or schedule URL',
  },
  {
    platform: 'sportsengine',
    label: 'SportsEngine',
    icon: 'link',
    connectionType: 'link',
    category: 'schedule',
    scope: 'team',
    sports: [],
    placeholder: 'SportsEngine team page URL',
  },
  {
    platform: 'sidearm',
    label: 'SIDEARM Sports',
    icon: 'link',
    connectionType: 'link',
    category: 'schedule',
    scope: 'team',
    sports: [],
    placeholder: 'SIDEARM team schedule URL',
  },

  // ---- Metrics (mirrors athlete profile metrics surface) ----
  {
    platform: 'hudl',
    label: 'Hudl',
    icon: 'link',
    connectionType: 'link',
    category: 'metrics',
    scope: 'sport',
    sports: [
      'football',
      'basketball',
      'soccer',
      'lacrosse',
      'volleyball',
      'field_hockey',
      'baseball',
      'softball',
      'wrestling',
      'ice_hockey',
    ],
    placeholder: 'Hudl profile URL',
  },
  {
    platform: '247sports',
    label: '247Sports',
    icon: 'link',
    connectionType: 'link',
    category: 'metrics',
    scope: 'sport',
    sports: ['football', 'basketball'],
    placeholder: '247Sports profile URL',
  },
  {
    platform: 'rivals',
    label: 'Rivals',
    icon: 'link',
    connectionType: 'link',
    category: 'metrics',
    scope: 'sport',
    sports: ['football', 'basketball'],
    placeholder: 'Rivals profile URL',
  },
  {
    platform: 'on3',
    label: 'On3',
    icon: 'link',
    connectionType: 'link',
    category: 'metrics',
    scope: 'sport',
    sports: ['football', 'basketball', 'baseball'],
    placeholder: 'On3 profile URL',
  },
  {
    platform: 'athletic',
    label: 'Athletic.net',
    icon: 'link',
    connectionType: 'link',
    category: 'metrics',
    scope: 'sport',
    sports: ['track_field', 'cross_country'],
    placeholder: 'Athletic.net profile URL',
  },
  {
    platform: 'milesplit',
    label: 'MileSplit',
    icon: 'link',
    connectionType: 'link',
    category: 'metrics',
    scope: 'sport',
    sports: ['track_field', 'cross_country'],
    placeholder: 'MileSplit profile URL',
  },
  {
    platform: 'swimcloud',
    label: 'SwimCloud',
    icon: 'link',
    connectionType: 'link',
    category: 'metrics',
    scope: 'sport',
    sports: ['swimming_diving'],
    placeholder: 'SwimCloud profile URL',
  },
  {
    platform: 'trackwrestling',
    label: 'TrackWrestling',
    icon: 'link',
    connectionType: 'link',
    category: 'metrics',
    scope: 'sport',
    sports: ['wrestling'],
    placeholder: 'TrackWrestling profile URL',
  },
  {
    platform: 'utr',
    label: 'UTR Sports',
    icon: 'link',
    connectionType: 'link',
    category: 'metrics',
    scope: 'sport',
    sports: ['tennis'],
    placeholder: 'UTR Sports profile URL',
  },
  {
    platform: 'catapult',
    label: 'Catapult',
    icon: 'link',
    connectionType: 'link',
    category: 'metrics',
    scope: 'sport',
    sports: ['football', 'basketball', 'soccer', 'lacrosse', 'ice_hockey', 'field_hockey', 'rugby'],
    placeholder: 'Catapult profile or session URL',
  },

  // ---- Academic ----
  {
    platform: 'ncaaeligibility',
    label: 'NCAA Eligibility Center',
    icon: 'link',
    connectionType: 'signin',
    category: 'academic',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to NCAA Eligibility Center',
    loginUrl: 'https://web3.ncaa.org/ecwr3/',
  },
  {
    platform: 'naiaeligibility',
    label: 'NAIA Eligibility Center',
    icon: 'link',
    connectionType: 'signin',
    category: 'academic',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to NAIA Eligibility Center',
    loginUrl: 'https://play.mynaia.org/',
  },
  {
    platform: 'parchment',
    label: 'Parchment',
    icon: 'link',
    connectionType: 'signin',
    category: 'academic',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Parchment',
    loginUrl: 'https://www.parchment.com/u/auth/login',
  },
  {
    platform: 'collegeboard',
    label: 'College Board',
    icon: 'link',
    connectionType: 'signin',
    category: 'academic',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to College Board',
    loginUrl: 'https://account.collegeboard.org/login/login',
  },
  {
    platform: 'act',
    label: 'ACT',
    icon: 'link',
    connectionType: 'signin',
    category: 'academic',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to ACT',
    loginUrl: 'https://my.act.org/account/signin',
  },

  // ---- Contact / Website surfaces ----
  {
    platform: 'linktree',
    label: 'Linktree',
    icon: 'link',
    connectionType: 'link',
    category: 'contact',
    scope: 'global',
    sports: [],
    placeholder: 'Linktree URL',
  },
  {
    platform: 'beacons',
    label: 'Beacons',
    icon: 'link',
    connectionType: 'link',
    category: 'contact',
    scope: 'global',
    sports: [],
    placeholder: 'Beacons URL',
  },
  {
    platform: 'campsite',
    label: 'Campsite',
    icon: 'link',
    connectionType: 'link',
    category: 'contact',
    scope: 'global',
    sports: [],
    placeholder: 'Campsite URL',
  },
  {
    platform: 'sportsengine',
    label: 'SportsEngine',
    icon: 'link',
    connectionType: 'link',
    category: 'contact',
    scope: 'team',
    sports: [],
    placeholder: 'SportsEngine team page URL',
  },
  {
    platform: 'sidearm',
    label: 'SIDEARM Sports',
    icon: 'link',
    connectionType: 'link',
    category: 'contact',
    scope: 'team',
    sports: [],
    placeholder: 'SIDEARM athletics page URL',
  },

  // ---- Sign-In (OAuth) ----
  {
    platform: 'google',
    label: 'Google',
    icon: 'google',
    connectionType: 'signin',
    category: 'signin',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in with Google',
  },
  {
    platform: 'microsoft',
    label: 'Microsoft',
    icon: 'microsoft',
    connectionType: 'signin',
    category: 'signin',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in with Microsoft',
  },

  // ---- Sign-In (Firecrawl Persistent Profile — browser-based) ----
  {
    platform: 'instagram_signin',
    label: 'Instagram',
    icon: 'link',
    connectionType: 'signin',
    category: 'social',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Instagram',
    loginUrl: 'https://www.instagram.com/accounts/login/',
  },
  {
    platform: 'twitter_signin',
    label: 'X',
    icon: 'link',
    connectionType: 'signin',
    category: 'social',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to X',
    loginUrl: 'https://x.com/i/flow/login',
  },
  {
    platform: 'tiktok_signin',
    label: 'TikTok',
    icon: 'link',
    connectionType: 'signin',
    category: 'social',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to TikTok',
    loginUrl: 'https://www.tiktok.com/login',
  },
  {
    platform: 'youtube_signin',
    label: 'YouTube',
    icon: 'link',
    connectionType: 'signin',
    category: 'social',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to YouTube',
    loginUrl: 'https://accounts.google.com/ServiceLogin?service=youtube',
  },
  {
    platform: 'facebook_signin',
    label: 'Facebook',
    icon: 'link',
    connectionType: 'signin',
    category: 'social',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Facebook',
    loginUrl: 'https://www.facebook.com/login/',
  },
  {
    platform: 'hudl_signin',
    label: 'Hudl',
    icon: 'link',
    connectionType: 'signin',
    category: 'film',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Hudl',
    loginUrl: 'https://www.hudl.com/login',
  },
  {
    platform: 'krossover_signin',
    label: 'Krossover (Hudl)',
    icon: 'link',
    connectionType: 'signin',
    category: 'film',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in via Hudl (formerly Krossover)',
    loginUrl: 'https://www.hudl.com/login',
  },
  {
    platform: 'veo_signin',
    label: 'Veo',
    icon: 'link',
    connectionType: 'signin',
    category: 'film',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Veo',
    loginUrl: 'https://app.veo.co/accounts/login/',
  },
  {
    platform: 'ballertv_signin',
    label: 'BallerTV',
    icon: 'link',
    connectionType: 'signin',
    category: 'film',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to BallerTV',
    loginUrl: 'https://www.ballertv.com/users/login',
  },
  {
    platform: 'nfhsnetwork_signin',
    label: 'NFHS Network',
    icon: 'link',
    connectionType: 'signin',
    category: 'film',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to NFHS Network',
    loginUrl: 'https://www.nfhsnetwork.com/users/sign_in',
  },
  {
    platform: 'sportsengineplay_signin',
    label: 'SportsEngine Play',
    icon: 'link',
    connectionType: 'signin',
    category: 'film',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to SportsEngine Play',
    loginUrl: 'https://app.sportsengineplay.com/login',
  },
  {
    platform: 'vimeo_signin',
    label: 'Vimeo',
    icon: 'link',
    connectionType: 'signin',
    category: 'film',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Vimeo',
    loginUrl: 'https://vimeo.com/log_in',
  },
  {
    platform: 'maxpreps_signin',
    label: 'MaxPreps',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to MaxPreps',
    loginUrl: 'https://www.maxpreps.com/',
  },
  {
    platform: 'perfectgame_signin',
    label: 'Perfect Game',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Perfect Game',
    loginUrl: 'https://www.perfectgame.org/MyPg/signin.aspx',
  },
  {
    platform: '247sports_signin',
    label: '247Sports',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to 247Sports',
    loginUrl: 'https://247sports.com/Account/LogIn/',
  },
  {
    platform: 'rivals_signin',
    label: 'Rivals',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Rivals',
    loginUrl: 'https://www.on3.com/login/',
  },
  {
    platform: 'on3_signin',
    label: 'On3',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to On3',
    loginUrl: 'https://www.on3.com/login/',
  },
  {
    platform: 'gamechanger_signin',
    label: 'GameChanger',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to GameChanger',
    loginUrl: 'https://app.gc.com/login',
  },
  {
    platform: 'prepbaseballreport_signin',
    label: 'Prep Baseball Report',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Prep Baseball Report',
    loginUrl: 'https://www.prepbaseballreport.com/login',
  },
  {
    platform: 'scorebooklive_signin',
    label: 'Scorebook Live',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Scorebook Live',
    loginUrl: 'https://www.si.com/high-school/stats/login',
  },
  {
    platform: 'athletic_signin',
    label: 'Athletic.net',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Athletic.net',
    loginUrl: 'https://www.athletic.net/account/login',
  },
  {
    platform: 'milesplit_signin',
    label: 'MileSplit',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to MileSplit',
    loginUrl: 'https://www.milesplit.com/login',
  },
  {
    platform: 'swimcloud_signin',
    label: 'SwimCloud',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to SwimCloud',
    loginUrl: 'https://www.swimcloud.com/login/',
  },
  {
    platform: 'trackwrestling_signin',
    label: 'TrackWrestling',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to TrackWrestling',
    loginUrl: 'https://www.trackwrestling.com/login',
  },
  {
    platform: 'tennisrecruiting_signin',
    label: 'TennisRecruiting.net',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to TennisRecruiting.net',
    loginUrl: 'https://www.tennisrecruiting.net/',
  },
  {
    platform: 'usta_signin',
    label: 'USTA',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to USTA',
    loginUrl: 'https://member.usta.com/login',
  },
  {
    platform: 'utr_signin',
    label: 'UTR Sports',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to UTR Sports',
    loginUrl: 'https://app.utrsports.net/sign-in',
  },
  {
    platform: 'prepsoccer_signin',
    label: 'PrepSoccer',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to PrepSoccer',
    loginUrl: 'https://www.prepsoccer.com/login',
  },
  {
    platform: 'usyouthsoccer_signin',
    label: 'US Youth Soccer',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to US Youth Soccer',
    loginUrl: 'https://www.usyouthsoccer.org/login',
  },
  {
    platform: 'golfstat_signin',
    label: 'Golfstat',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Golfstat',
    loginUrl: 'https://www.golfstat.com/login',
  },
  {
    platform: 'juniorgolf_signin',
    label: 'Junior Golf Scoreboard',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Junior Golf Scoreboard',
    loginUrl: 'https://www.juniorgolfscoreboard.com/login-accounts.asp',
  },
  {
    platform: 'prephoops_signin',
    label: 'PrepHoops',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to PrepHoops',
    loginUrl: 'https://prephoops.com/login',
  },
  {
    platform: 'prepfootball_signin',
    label: 'Prep Football',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Prep Football',
    loginUrl: 'https://www.prepfootball.com/login',
  },
  {
    platform: 'topdrawersoccer_signin',
    label: 'TopDrawerSoccer',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to TopDrawerSoccer',
    loginUrl: 'https://www.topdrawersoccer.com/login',
  },
  {
    platform: 'prepvolleyball_signin',
    label: 'PrepVolleyball',
    icon: 'link',
    connectionType: 'signin',
    category: 'stats',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to PrepVolleyball',
    loginUrl: 'https://prepvolleyball.com/login',
  },
  {
    platform: 'catapult_signin',
    label: 'Catapult',
    icon: 'link',
    connectionType: 'signin',
    category: 'metrics',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Catapult',
    loginUrl: 'https://connect.catapultsports.com/login',
  },
  {
    platform: 'ncsa_signin',
    label: 'NCSA',
    icon: 'link',
    connectionType: 'signin',
    category: 'recruiting',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to NCSA',
    loginUrl: 'https://www.ncsasports.org/login',
  },
  {
    platform: 'fieldlevel_signin',
    label: 'FieldLevel',
    icon: 'link',
    connectionType: 'signin',
    category: 'recruiting',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to FieldLevel',
    loginUrl: 'https://www.fieldlevel.com/signin',
  },
  {
    platform: 'captainu_signin',
    label: 'Stack Athlete (CaptainU)',
    icon: 'link',
    connectionType: 'signin',
    category: 'recruiting',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Stack Athlete (formerly CaptainU)',
    loginUrl: 'https://app.stackathlete.com/login',
  },
  {
    platform: 'sportsrecruits_signin',
    label: 'SportsRecruits',
    icon: 'link',
    connectionType: 'signin',
    category: 'recruiting',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to SportsRecruits',
    loginUrl: 'https://my.sportsrecruits.com/athlete/user/login',
  },
  {
    platform: 'streamlineathletes_signin',
    label: 'Streamline Athletes',
    icon: 'link',
    connectionType: 'signin',
    category: 'recruiting',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Streamline Athletes',
    loginUrl: 'https://www.streamlineathletes.com/login',
  },
  {
    platform: 'recruitlook_signin',
    label: 'RecruitLook',
    icon: 'link',
    connectionType: 'signin',
    category: 'recruiting',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to RecruitLook',
    loginUrl: 'https://www.recruitlook.com/login',
  },
  {
    platform: 'collegeathtrack_signin',
    label: 'College Ath Track',
    icon: 'link',
    connectionType: 'signin',
    category: 'recruiting',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to College Athletic Track',
    loginUrl: 'https://www.collegeathtrack.com/login',
  },
  {
    platform: 'connectlax_signin',
    label: 'ConnectLAX',
    icon: 'link',
    connectionType: 'signin',
    category: 'recruiting',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to ConnectLAX',
    loginUrl: 'https://www.connectlax.com/login',
  },
  {
    platform: 'imlcarecruits_signin',
    label: 'IMLCA Recruits',
    icon: 'link',
    connectionType: 'signin',
    category: 'recruiting',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to IMLCA Recruits',
    loginUrl: 'https://www.imlcarecruits.com/login',
  },
  {
    platform: 'berecruited_signin',
    label: 'BeRecruited',
    icon: 'link',
    connectionType: 'signin',
    category: 'recruiting',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to BeRecruited',
    loginUrl: 'https://www.berecruited.com/login',
  },
  {
    platform: 'linktree_signin',
    label: 'Linktree',
    icon: 'link',
    connectionType: 'signin',
    category: 'contact',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Linktree',
    loginUrl: 'https://linktr.ee/login',
  },
  {
    platform: 'beacons_signin',
    label: 'Beacons',
    icon: 'link',
    connectionType: 'signin',
    category: 'contact',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Beacons',
    loginUrl: 'https://app.beacons.ai/',
  },
  {
    platform: 'campsite_signin',
    label: 'Campsite',
    icon: 'link',
    connectionType: 'signin',
    category: 'contact',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to Campsite',
    loginUrl: 'https://app.campsite.bio/login',
  },
  {
    platform: 'sportsengine_signin',
    label: 'SportsEngine',
    icon: 'link',
    connectionType: 'signin',
    category: 'contact',
    scope: 'global',
    sports: [],
    placeholder: 'Sign in to SportsEngine',
    loginUrl: 'https://user.sportngin.com/users/sign_in',
  },
] as const;

/** Category display info */
export const PLATFORM_CATEGORIES: readonly {
  readonly category: PlatformCategory;
  readonly label: string;
}[] = [
  { category: 'social', label: 'Social Links' },
  { category: 'film', label: 'Videos & Highlights' },
  { category: 'recruiting', label: 'Recruiting Profiles' },
  { category: 'metrics', label: 'Metrics' },
  { category: 'stats', label: 'Stats & Rankings' },
  { category: 'academic', label: 'Academic & Eligibility' },
  { category: 'schedule', label: 'Schedule' },
  { category: 'contact', label: 'Contact & Websites' },
  { category: 'signin', label: 'Sign-In Accounts' },
] as const;
