/**
 * @fileoverview Agent X Mode Content Constants & Mock Data
 * @module @nxt1/core/ai
 * @version 1.0.0
 *
 * Static content data for each Agent X mode tab.
 * Drafts use mock data (will come from backend later);
 * categories, bundles, and tasks are static config.
 *
 * ⭐ 100% PORTABLE — Zero framework dependencies ⭐
 */

import type {
  AgentXTemplateCategory,
  AgentXTemplate,
  AgentXBundle,
  AgentXTaskItem,
} from './agent-x-content.types';

// ============================================
// HIGHLIGHTS — Template Categories
// ============================================

export const HIGHLIGHT_CATEGORIES: readonly AgentXTemplateCategory[] = [
  {
    id: 'game-highlights',
    label: 'Game Highlights',
    description: 'Auto-edited game clips with music & transitions',
    icon: 'videocam-outline',
    templateCount: 12,
    mode: 'highlights',
    featured: true,
    xpReward: 150,
    accentColor: 'var(--nxt1-color-primary)',
  },
  {
    id: 'season-recap',
    label: 'Season Recap',
    description: 'Full season montage with stats overlay',
    icon: 'trophy-outline',
    templateCount: 8,
    mode: 'highlights',
    xpReward: 200,
  },
  {
    id: 'skill-showcase',
    label: 'Skill Showcase',
    description: 'Position-specific skill breakdowns',
    icon: 'flash-outline',
    templateCount: 10,
    mode: 'highlights',
    xpReward: 125,
  },
  {
    id: 'recruiting-reel',
    label: 'Recruiting Reel',
    description: 'College-ready highlight reel with contact info',
    icon: 'school-outline',
    templateCount: 6,
    mode: 'highlights',
    featured: true,
    xpReward: 250,
    accentColor: 'var(--nxt1-color-primary)',
  },
  {
    id: 'social-clips',
    label: 'Social Clips',
    description: 'Short-form clips optimized for social media',
    icon: 'share-social-outline',
    templateCount: 15,
    mode: 'highlights',
    xpReward: 75,
  },
  {
    id: 'training-montage',
    label: 'Training Montage',
    description: 'Workout and training compilation videos',
    icon: 'barbell-outline',
    templateCount: 7,
    mode: 'highlights',
    xpReward: 100,
  },
] as const;

// ============================================
// GRAPHICS — Template Categories
// ============================================

export const GRAPHIC_CATEGORIES: readonly AgentXTemplateCategory[] = [
  {
    id: 'stat-graphics',
    label: 'Stat Graphics',
    description: 'Dynamic stat cards with your latest numbers',
    icon: 'stats-chart-outline',
    templateCount: 18,
    mode: 'graphics',
    featured: true,
    xpReward: 100,
    accentColor: 'var(--nxt1-color-primary)',
  },
  {
    id: 'social-logos',
    label: 'Social Logos',
    description: 'Personal brand logos for profiles & watermarks',
    icon: 'logo-instagram',
    templateCount: 14,
    mode: 'graphics',
    xpReward: 125,
  },
  {
    id: 'banners',
    label: 'Banners',
    description: 'Profile banners for Twitter, YouTube & more',
    icon: 'image-outline',
    templateCount: 12,
    mode: 'graphics',
    featured: true,
    xpReward: 100,
    accentColor: 'var(--nxt1-color-primary)',
  },
  {
    id: 'stories',
    label: 'Stories',
    description: 'Instagram & Snapchat story templates',
    icon: 'phone-portrait-outline',
    templateCount: 20,
    mode: 'graphics',
    xpReward: 75,
  },
  {
    id: 'commitment-graphics',
    label: 'Commitment',
    description: 'College commitment announcements & graphics',
    icon: 'school-outline',
    templateCount: 8,
    mode: 'graphics',
    xpReward: 200,
  },
  {
    id: 'gameday-posters',
    label: 'Gameday Posters',
    description: 'Pre-game hype posters with schedules',
    icon: 'calendar-outline',
    templateCount: 10,
    mode: 'graphics',
    xpReward: 100,
  },
] as const;

// ============================================
// HIGHLIGHTS — Templates (Canva-style cards)
// ============================================

export const HIGHLIGHT_TEMPLATES: readonly AgentXTemplate[] = [
  {
    id: 'hl-tpl-1',
    title: 'Friday Night Lights',
    categoryId: 'game-highlights',
    mode: 'highlights',
    aspectRatio: '16:9',
    placeholderGradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    placeholderIcon: 'videocam',
    popular: true,
    usageCount: 4820,
    xpReward: 150,
  },
  {
    id: 'hl-tpl-2',
    title: 'Quick Cuts',
    categoryId: 'game-highlights',
    mode: 'highlights',
    aspectRatio: '9:16',
    placeholderGradient: 'linear-gradient(135deg, #2d1b69 0%, #11998e 100%)',
    placeholderIcon: 'flash',
    usageCount: 3210,
    xpReward: 100,
  },
  {
    id: 'hl-tpl-3',
    title: 'Season Highlight Reel',
    categoryId: 'season-recap',
    mode: 'highlights',
    aspectRatio: '16:9',
    placeholderGradient: 'linear-gradient(135deg, #e44d26 0%, #f7df1e 100%)',
    placeholderIcon: 'trophy',
    popular: true,
    usageCount: 6140,
    xpReward: 200,
  },
  {
    id: 'hl-tpl-4',
    title: 'Top 10 Plays',
    categoryId: 'game-highlights',
    mode: 'highlights',
    aspectRatio: '16:9',
    placeholderGradient: 'linear-gradient(135deg, #0c0c0c 0%, #1e3a5f 100%)',
    placeholderIcon: 'medal',
    usageCount: 2750,
    xpReward: 150,
  },
  {
    id: 'hl-tpl-5',
    title: 'Skills Breakdown',
    categoryId: 'skill-showcase',
    mode: 'highlights',
    aspectRatio: '16:9',
    placeholderGradient: 'linear-gradient(135deg, #141e30 0%, #243b55 100%)',
    placeholderIcon: 'flash-outline',
    popular: true,
    usageCount: 3890,
    xpReward: 125,
  },
  {
    id: 'hl-tpl-6',
    title: 'College Intro Reel',
    categoryId: 'recruiting-reel',
    mode: 'highlights',
    aspectRatio: '16:9',
    placeholderGradient: 'linear-gradient(135deg, #1a1a1a 0%, #ccff00 100%)',
    placeholderIcon: 'school',
    popular: true,
    pro: true,
    usageCount: 8200,
    xpReward: 250,
  },
  {
    id: 'hl-tpl-7',
    title: 'Vertical Hype Clip',
    categoryId: 'social-clips',
    mode: 'highlights',
    aspectRatio: '9:16',
    placeholderGradient: 'linear-gradient(135deg, #ff0844 0%, #ffb199 100%)',
    placeholderIcon: 'share-social',
    usageCount: 5100,
    xpReward: 75,
  },
  {
    id: 'hl-tpl-8',
    title: 'Cinematic Intro',
    categoryId: 'game-highlights',
    mode: 'highlights',
    aspectRatio: '16:9',
    placeholderGradient: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    placeholderIcon: 'film',
    pro: true,
    usageCount: 1920,
    xpReward: 175,
  },
  {
    id: 'hl-tpl-9',
    title: 'Beast Mode',
    categoryId: 'skill-showcase',
    mode: 'highlights',
    aspectRatio: '1:1',
    placeholderGradient: 'linear-gradient(135deg, #ff416c 0%, #ff4b2b 100%)',
    placeholderIcon: 'flame',
    popular: true,
    usageCount: 4300,
    xpReward: 125,
  },
  {
    id: 'hl-tpl-10',
    title: 'Pre-Game Hype',
    categoryId: 'training-montage',
    mode: 'highlights',
    aspectRatio: '9:16',
    placeholderGradient: 'linear-gradient(135deg, #000428 0%, #004e92 100%)',
    placeholderIcon: 'barbell',
    usageCount: 2100,
    xpReward: 100,
  },
  {
    id: 'hl-tpl-11',
    title: 'My Journey',
    categoryId: 'season-recap',
    mode: 'highlights',
    aspectRatio: '16:9',
    placeholderGradient: 'linear-gradient(135deg, #232526 0%, #414345 100%)',
    placeholderIcon: 'time',
    usageCount: 1600,
    xpReward: 200,
  },
  {
    id: 'hl-tpl-12',
    title: 'TikTok Drip',
    categoryId: 'social-clips',
    mode: 'highlights',
    aspectRatio: '9:16',
    placeholderGradient: 'linear-gradient(135deg, #ee0979 0%, #ff6a00 100%)',
    placeholderIcon: 'musical-notes',
    popular: true,
    usageCount: 7200,
    xpReward: 75,
  },
] as const;

// ============================================
// GRAPHICS — Templates (Canva-style cards)
// ============================================

export const GRAPHIC_TEMPLATES: readonly AgentXTemplate[] = [
  {
    id: 'gr-tpl-1',
    title: 'Season Stats Card',
    categoryId: 'stat-graphics',
    mode: 'graphics',
    aspectRatio: '1:1',
    placeholderGradient: 'linear-gradient(135deg, #0a0a0a 0%, #1e1e1e 50%, #ccff00 100%)',
    placeholderIcon: 'stats-chart',
    popular: true,
    usageCount: 9400,
    xpReward: 100,
  },
  {
    id: 'gr-tpl-2',
    title: 'Game Day Stat Drop',
    categoryId: 'stat-graphics',
    mode: 'graphics',
    aspectRatio: '4:5',
    placeholderGradient: 'linear-gradient(135deg, #1a1a2e 0%, #e94560 100%)',
    placeholderIcon: 'flame',
    popular: true,
    usageCount: 6700,
    xpReward: 100,
  },
  {
    id: 'gr-tpl-3',
    title: 'Personal Logo – Modern',
    categoryId: 'social-logos',
    mode: 'graphics',
    aspectRatio: '1:1',
    placeholderGradient: 'linear-gradient(135deg, #000000 0%, #434343 100%)',
    placeholderIcon: 'logo-electron',
    popular: true,
    pro: true,
    usageCount: 5200,
    xpReward: 125,
  },
  {
    id: 'gr-tpl-4',
    title: 'Twitter/X Banner',
    categoryId: 'banners',
    mode: 'graphics',
    aspectRatio: '16:9',
    placeholderGradient: 'linear-gradient(135deg, #0f0f0f 0%, #2c3e50 100%)',
    placeholderIcon: 'image',
    popular: true,
    usageCount: 7800,
    xpReward: 100,
  },
  {
    id: 'gr-tpl-5',
    title: 'Commitment Graphic',
    categoryId: 'commitment-graphics',
    mode: 'graphics',
    aspectRatio: '1:1',
    placeholderGradient: 'linear-gradient(135deg, #1a1a1a 0%, #ccff00 100%)',
    placeholderIcon: 'school',
    popular: true,
    pro: true,
    usageCount: 4100,
    xpReward: 200,
  },
  {
    id: 'gr-tpl-6',
    title: 'IG Story – Game Recap',
    categoryId: 'stories',
    mode: 'graphics',
    aspectRatio: '9:16',
    placeholderGradient: 'linear-gradient(135deg, #5f2c82 0%, #49a09d 100%)',
    placeholderIcon: 'phone-portrait',
    usageCount: 5500,
    xpReward: 75,
  },
  {
    id: 'gr-tpl-7',
    title: 'Gameday Poster',
    categoryId: 'gameday-posters',
    mode: 'graphics',
    aspectRatio: '4:5',
    placeholderGradient: 'linear-gradient(135deg, #200122 0%, #6f0000 100%)',
    placeholderIcon: 'calendar',
    popular: true,
    usageCount: 3900,
    xpReward: 100,
  },
  {
    id: 'gr-tpl-8',
    title: 'Minimalist Logo',
    categoryId: 'social-logos',
    mode: 'graphics',
    aspectRatio: '1:1',
    placeholderGradient: 'linear-gradient(135deg, #f5f5f5 0%, #c9c9c9 100%)',
    placeholderIcon: 'logo-apple',
    usageCount: 2300,
    xpReward: 125,
  },
  {
    id: 'gr-tpl-9',
    title: 'YouTube Banner',
    categoryId: 'banners',
    mode: 'graphics',
    aspectRatio: '16:9',
    placeholderGradient: 'linear-gradient(135deg, #c31432 0%, #240b36 100%)',
    placeholderIcon: 'logo-youtube',
    usageCount: 2800,
    xpReward: 100,
  },
  {
    id: 'gr-tpl-10',
    title: 'IG Story – Pre-Game',
    categoryId: 'stories',
    mode: 'graphics',
    aspectRatio: '9:16',
    placeholderGradient: 'linear-gradient(135deg, #fc4a1a 0%, #f7b733 100%)',
    placeholderIcon: 'flame',
    usageCount: 4600,
    xpReward: 75,
  },
  {
    id: 'gr-tpl-11',
    title: 'Weekly Stat Update',
    categoryId: 'stat-graphics',
    mode: 'graphics',
    aspectRatio: '1:1',
    placeholderGradient: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
    placeholderIcon: 'trending-up',
    usageCount: 3100,
    xpReward: 100,
  },
  {
    id: 'gr-tpl-12',
    title: 'Decommitment Graphic',
    categoryId: 'commitment-graphics',
    mode: 'graphics',
    aspectRatio: '1:1',
    placeholderGradient: 'linear-gradient(135deg, #373b44 0%, #4286f4 100%)',
    placeholderIcon: 'school-outline',
    usageCount: 890,
    xpReward: 200,
  },
] as const;

// ============================================
// BUNDLES
// ============================================

export const AGENT_X_BUNDLES: readonly AgentXBundle[] = [
  {
    id: 'ultimate-agent-kit',
    title: 'Ultimate Agent Kit',
    subtitle: 'Everything you need to get recruited',
    icon: 'diamond-outline',
    gradient: 'linear-gradient(135deg, #ccff00 0%, #88cc00 100%)',
    itemCount: 12,
    categoryIds: ['recruiting-reel', 'stat-graphics', 'social-logos', 'banners'],
    bonusXp: 500,
    badgeRarity: 'legendary',
    badgeLabel: 'Agent Elite',
    modes: ['highlights', 'graphics'],
  },
  {
    id: 'highlight-bundle',
    title: 'Highlight Bundle',
    subtitle: 'Complete video package for scouts',
    icon: 'videocam-outline',
    gradient: 'linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%)',
    itemCount: 6,
    categoryIds: ['game-highlights', 'season-recap', 'skill-showcase'],
    bonusXp: 300,
    badgeRarity: 'epic',
    badgeLabel: 'Film Star',
    modes: ['highlights'],
  },
  {
    id: 'brand-builder',
    title: 'Brand Builder',
    subtitle: 'Logo, banner & social media starter pack',
    icon: 'color-palette-outline',
    gradient: 'linear-gradient(135deg, #a29bfe 0%, #6c5ce7 100%)',
    itemCount: 5,
    categoryIds: ['social-logos', 'banners', 'stories'],
    bonusXp: 250,
    badgeRarity: 'rare',
    badgeLabel: 'Brand Pro',
    modes: ['graphics'],
  },
  {
    id: 'recruiting-starter',
    title: 'Recruiting Starter',
    subtitle: "Get on coaches' radar fast",
    icon: 'rocket-outline',
    gradient: 'linear-gradient(135deg, #00cec9 0%, #0984e3 100%)',
    itemCount: 4,
    categoryIds: ['recruiting-reel', 'commitment-graphics'],
    bonusXp: 200,
    badgeRarity: 'uncommon',
    badgeLabel: 'Scout Ready',
    modes: ['highlights', 'graphics'],
  },
] as const;

// ============================================
// RECRUITING — Tasks
// ============================================

export const RECRUITING_TASKS: readonly AgentXTaskItem[] = [
  {
    id: 'find-college-matches',
    title: 'Find My Best College Matches',
    description: 'AI analyzes your stats, academics & preferences to find your top 10 fits',
    icon: 'school-outline',
    mode: 'recruiting',
    priority: 'critical',
    xpReward: 200,
    estimatedTime: '2 min',
    socialProof: "94% of users found a match they hadn't considered",
    featured: true,
    accentColor: 'var(--nxt1-color-primary)',
  },
  {
    id: 'draft-recruiting-email',
    title: 'Draft a Recruiting Email',
    description: 'Personalized email to a coach with your highlights & stats attached',
    icon: 'mail-outline',
    mode: 'recruiting',
    priority: 'high',
    xpReward: 150,
    estimatedTime: '1 min',
    socialProof: '3x higher response rate vs generic emails',
  },
  {
    id: 'recruiting-timeline',
    title: 'My Recruiting Timeline',
    description: 'See what you should be doing right now based on your grad year',
    icon: 'calendar-outline',
    mode: 'recruiting',
    priority: 'high',
    xpReward: 100,
    estimatedTime: '1 min',
  },
  {
    id: 'coach-outreach-plan',
    title: 'Build Coach Outreach Plan',
    description: 'Automated 30-day outreach schedule with follow-up reminders',
    icon: 'paper-plane-outline',
    mode: 'recruiting',
    priority: 'normal',
    xpReward: 175,
    estimatedTime: '3 min',
    socialProof: 'Athletes who follow up are 5x more likely to get noticed',
  },
  {
    id: 'camp-finder',
    title: 'Find Camps & Showcases',
    description: 'Discover upcoming camps near you that fit your level',
    icon: 'location-outline',
    mode: 'recruiting',
    priority: 'normal',
    xpReward: 75,
    estimatedTime: '1 min',
  },
  {
    id: 'scholarship-estimator',
    title: 'Scholarship Estimator',
    description: 'Estimate your scholarship potential based on your profile strength',
    icon: 'cash-outline',
    mode: 'recruiting',
    priority: 'normal',
    xpReward: 125,
    estimatedTime: '2 min',
    featured: true,
    accentColor: 'var(--nxt1-color-primary)',
  },
] as const;

// ============================================
// EVALUATION — Tasks
// ============================================

export const EVALUATION_TASKS: readonly AgentXTaskItem[] = [
  {
    id: 'profile-strength',
    title: 'Profile Strength Report',
    description: 'Get a detailed score of your profile with actionable improvements',
    icon: 'shield-checkmark-outline',
    mode: 'evaluation',
    priority: 'critical',
    xpReward: 200,
    estimatedTime: '2 min',
    socialProof: 'Top profiles are 8x more likely to be viewed by coaches',
    featured: true,
    accentColor: 'var(--nxt1-color-primary)',
  },
  {
    id: 'film-review',
    title: 'AI Film Review',
    description: 'Agent X breaks down your film with coaching-level feedback',
    icon: 'film-outline',
    mode: 'evaluation',
    priority: 'high',
    xpReward: 250,
    estimatedTime: '5 min',
    socialProof: 'Used by 200+ coaches for quick evaluations',
  },
  {
    id: 'stat-comparison',
    title: 'Compare My Stats',
    description: 'See how your numbers stack up against committed athletes',
    icon: 'analytics-outline',
    mode: 'evaluation',
    priority: 'high',
    xpReward: 150,
    estimatedTime: '2 min',
  },
  {
    id: 'improvement-plan',
    title: 'Personalized Improvement Plan',
    description: 'Week-by-week training plan to boost your recruiting stock',
    icon: 'trending-up-outline',
    mode: 'evaluation',
    priority: 'normal',
    xpReward: 175,
    estimatedTime: '3 min',
  },
  {
    id: 'position-fit',
    title: 'Position Fit Analysis',
    description: 'Find the best position for your body type and skill set',
    icon: 'body-outline',
    mode: 'evaluation',
    priority: 'normal',
    xpReward: 125,
    estimatedTime: '2 min',
  },
  {
    id: 'prospect-grade',
    title: 'Prospect Grade',
    description: 'Get your overall recruiting grade with tier classification',
    icon: 'star-outline',
    mode: 'evaluation',
    priority: 'critical',
    xpReward: 200,
    estimatedTime: '2 min',
    featured: true,
    accentColor: 'var(--nxt1-color-primary)',
  },
] as const;
