export type B2BPartnerOutreachSequenceStep = 'initial' | 'follow_up' | 'final_follow_up';

export type B2BPartnerOutreachStatus =
  | 'not_sent'
  | 'sent'
  | 'follow_up_due'
  | 'follow_up_sent'
  | 'replied'
  | 'paused';

export interface B2BPartnerBrandAwarenessRecipient {
  readonly organization: string;
  readonly crmStage: 'Lead' | 'Contacted';
  readonly partnerType: 'School/University' | 'Club/Academy';
  readonly primaryContact: string;
  readonly email: string;
  readonly sendCount: number;
  readonly sequenceStep: B2BPartnerOutreachSequenceStep;
  readonly deliveryStatus: B2BPartnerOutreachStatus;
  readonly lastSentAt: string | null;
  readonly nextFollowUpAt: string | null;
  readonly notes: string;
}

export const B2B_PARTNER_BRAND_AWARENESS_RECIPIENTS: readonly B2BPartnerBrandAwarenessRecipient[] =
  [
    {
      organization: 'Centennial High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'David Carrillo',
      email: 'dcarrillo1@lcps.net',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Atrisco Heritage Academy',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Jana Villegas',
      email: 'villegas@aps.edu',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Grants High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Reyes Jaramillo',
      email: 'reyes.jaramillo@gccs.k12.nm.us',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Hope Christian High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Jim Murphy',
      email: 'athletics@hcsnm.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'General athletic department inbox.',
    },
    {
      organization: 'Eldorado High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Roy Sanchez',
      email: 'sanchez_roy@aps.edu',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Las Cruces High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Michelle Paz',
      email: 'mpaz@lcps.net',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Gallup High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Cara Bedonie',
      email: 'cbedonie@gmcs.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Del Norte High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Tom Herndon',
      email: 'thomas.herndon@aps.edu',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Capitan High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Nate Poss',
      email: 'nate.poss@capitantigers.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'McCurdy High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Ian Maestas',
      email: 'ian.maestas@mcsk12nm.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'House High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Jarred Hestand',
      email: 'hestand@houseschools.net',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Hozho Academy',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Cyle Balok',
      email: 'cbalok@hozhoacademy.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Gateway Christian High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Justin Stephens',
      email: 'jstephens@gatewaychristianschool.us',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Melrose High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Casey Jackson',
      email: 'cjackson@melroseschools.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Cobre High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Cory Gropp',
      email: 'cgropp@cobreschools.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Jal High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Brent Satterwhite',
      email: 'brent.satterwhite@jalnm.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Albuquerque High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Chad Jones',
      email: 'chad.jones@aps.edu',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Capital High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Nicholas Salazar',
      email: 'nisalazar@sfps.k12.nm.us',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Jemez Valley High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Julian Davis',
      email: 'jdavis@jvps.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Crownpoint High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Kelly Morris',
      email: 'kmorris@gmcs.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Logan High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Billy Burns',
      email: 'bburns@loganschool.net',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Hagerman High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Andrew Rodriguez',
      email: 'arodriguez@bobcat.net',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Escalante High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Isaac Royston',
      email: 'iroyston@chamaschools.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Clovis Christian School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Sky Saul',
      email: 'ssaul@cloviseagles.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Alamogordo High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Alan Edmonson',
      email: 'alan.edmonson@alamoqordoschools.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Verify school domain before full send.',
    },
    {
      organization: 'Maxwell High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Michael Glasman',
      email: 'mglasman@maxwellp12.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Albuquerque Academy',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Taryn Bachis',
      email: 'tarvn.bachis@aa.edu',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Verify address spelling before full send.',
    },
    {
      organization: 'Aztec High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'David Sweet',
      email: 'adsweeda@aztecschools.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Verify address spelling before full send.',
    },
    {
      organization: 'Lovington High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Kirk Murad',
      email: 'kirkmurad@lovingtonschools.net',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Bernalillo High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Ira Harge',
      email: 'iharge@bernalillops.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Academy for Technology and the Classics',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Jennifer Ferguson',
      email: 'jennifer.ferguson@atcschool.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Evangel Christian Academy',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Bryce Hammond',
      email: 'bryce.hammond@ecanm.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Cuba High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Frank Cordova',
      email: 'frcordova@cuba.k12.nm.us',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Grady High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Les Ciancio',
      email: 'lciancio@gradyschool.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Cimarron High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Alberta Martinez',
      email: 'almartinez@cimarronschools.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Floyd High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Adam Terry',
      email: 'aterry@floydbroncos.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Dexter High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Melissa Duran',
      email: 'duranm@dexterdemons.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Carrizozo High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Gid Allen',
      email: 'gid.allen@carrizozogrizzlies.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Los Lunas High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'William Hays',
      email: 'whays@llschools.net',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Lordsburg High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Dale Hooper',
      email: 'dhooper@lmsed.org',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Albuquerque Public Schools',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Adam Baysinger',
      email: 'adam.baysinger@aps.edu',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'District-level athletic operations contact.',
    },
    {
      organization: 'Fort Sumner High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Crystal Boyd',
      email: 'cboyd@ftsumnerk12.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Animas High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Jeff Gephart',
      email: 'gephart@animask12.net',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Coronado High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Ricky Lindblad',
      email: 'lindblad_r@jmsd.k12.nm.us',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'New Mexico school outreach list.',
    },
    {
      organization: 'Oakland Mills High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Kasen Bien-Aime',
      email: 'kasen2bienaime@gmail.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Personal email on supplied list.',
    },
    {
      organization: 'MAT ZONE',
      crmStage: 'Lead',
      partnerType: 'Club/Academy',
      primaryContact: 'Quen Jones',
      email: 'saucethekiid@gmail.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Club outreach list.',
    },
    {
      organization: 'West Creek',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Logan Adair',
      email: 'loganadair2008@aol.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Personal email on supplied list.',
    },
    {
      organization: 'Rockvale High School',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Maddox Holder',
      email: 'maddox.holder3@icloud.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Personal email on supplied list.',
    },
    {
      organization: 'Corinth Holders',
      crmStage: 'Lead',
      partnerType: 'Club/Academy',
      primaryContact: 'Lamont Hunt Jr',
      email: 'lamonthunt62@gmail.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Club outreach list.',
    },
    {
      organization: 'Acharnis',
      crmStage: 'Lead',
      partnerType: 'Club/Academy',
      primaryContact: 'Παναγιωτης Πετρουλακης',
      email: 'petroulakesp@gmail.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'International club outreach list.',
    },
    {
      organization: 'Haynes Academy',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Adnn Ali',
      email: 'legend45219@gmail.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Personal email on supplied list.',
    },
    {
      organization: 'Central Lakes College',
      crmStage: 'Lead',
      partnerType: 'School/University',
      primaryContact: 'Lonnel Harrison',
      email: 'tazz1911@yahoo.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Personal email on supplied list.',
    },
    {
      organization: 'Crimson Kings',
      crmStage: 'Lead',
      partnerType: 'Club/Academy',
      primaryContact: 'Sam Robinson',
      email: 'crimsonkings.elite@gmail.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Club outreach list.',
    },
    {
      organization: 'Firecrackers',
      crmStage: 'Lead',
      partnerType: 'Club/Academy',
      primaryContact: 'Michael Kruse',
      email: 'mskruse2@gmail.com',
      sendCount: 0,
      sequenceStep: 'initial',
      deliveryStatus: 'not_sent',
      lastSentAt: null,
      nextFollowUpAt: null,
      notes: 'Club outreach list.',
    },
  ];
