/**
 * @fileoverview Agent X Shell Component - AI Command Center
 * @module @nxt1/ui/agent-x
 * @version 2.0.0
 *
 * Redesigned AI-first command center with proactive Daily Briefing,
 * Active Operations queue, and contextual Action Chips.
 *
 * ⭐ SHARED BETWEEN WEB AND MOBILE ⭐
 *
 * Layout (top → bottom):
 * 1. Page Header — Agent X logo centered (no text title)
 * 2. Daily Briefing — Proactive AI insights card
 * 3. Coordinators — 2×2 grid of virtual staff cards (Recruiting, Media, Scout, Academics)
 * 4. Weekly Playbook — Always visible (with "Need a Game Plan" state if no goals)
 * 5. Daily Operations — Active background task cards (conditional)
 * 6. Input Bar — Fixed above footer (already exists)
 *
 * @example
 * ```html
 * <nxt1-agent-x-shell
 *   [user]="currentUser()"
 *   (avatarClick)="openSidenav()"
 * />
 * ```
 */

import {
  Component,
  ChangeDetectionStrategy,
  inject,
  input,
  output,
  signal,
  computed,
  afterNextRender,
  effect,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { IonContent } from '@ionic/angular/standalone';
import { NxtPageHeaderComponent } from '../components/page-header';
import { NxtRefresherComponent, type RefreshEvent } from '../components/refresh-container';
import { NxtIconComponent } from '../components/icon';
import { AgentXService } from './agent-x.service';

import { AgentXInputComponent } from './agent-x-input.component';
import {
  AgentXOperationChatComponent,
  type OperationQuickAction,
} from './agent-x-operation-chat.component';
import { AgentXDashboardSkeletonComponent } from './agent-x-dashboard-skeleton.component';
import { AgentXOperationsLogComponent } from './agent-x-operations-log.component';
import { HapticsService } from '../services/haptics/haptics.service';
import { NxtToastService } from '../services/toast/toast.service';
import { NxtBottomSheetService, SHEET_PRESETS } from '../components/bottom-sheet';
import { type ShellWeeklyPlaybookItem, type ShellActiveOperation } from '@nxt1/core/ai';

// ============================================
// INTERFACES
// ============================================

/** User info for header display. */
export interface AgentXUser {
  readonly profileImg?: string | null;
  readonly displayName?: string | null;
  readonly role?: string;
}

/** An active background operation Agent X is processing. */
export interface ActiveOperation {
  readonly id: string;
  readonly label: string;
  readonly progress: number; // 0–100
  readonly icon: string;
  readonly status: 'processing' | 'complete' | 'error';
  /** MongoDB thread ID — when set, opening this card loads the persisted worker conversation. */
  readonly threadId?: string;
}

/** A contextual action chip for quick workflows. */
export interface ActionChip {
  readonly id: string;
  readonly label: string;
  readonly subLabel?: string;
  readonly icon: string;
}

/** A group of related quick commands under a category. */
export interface CommandCategory {
  readonly id: string;
  readonly label: string;
  readonly icon: string;
  readonly description: string;
  readonly commands: readonly ActionChip[];
}

/** Daily briefing insight from Agent X. */
export interface BriefingInsight {
  readonly id: string;
  readonly text: string;
  readonly icon: string;
  readonly type: 'info' | 'warning' | 'success';
}

/** A goal tag linking a playbook task to a user objective. */
export interface GoalTag {
  readonly id: string;
  readonly label: string;
}

/** A weekly timeline item generated by Agent X. */
export interface WeeklyPlaybookItem {
  readonly id: string;
  readonly weekLabel: string;
  readonly title: string;
  readonly summary: string;
  readonly details: string;
  readonly actionLabel: string;
  readonly status: 'pending' | 'in-progress' | 'complete' | 'problem';
  readonly goal?: GoalTag;
}

@Component({
  selector: 'nxt1-agent-x-shell',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    IonContent,
    NxtPageHeaderComponent,
    NxtRefresherComponent,
    NxtIconComponent,
    AgentXDashboardSkeletonComponent,
    AgentXInputComponent,
  ],
  template: `
    <!-- ═══ PAGE HEADER — Agent X Logo Centered ═══ -->
    @if (!hideHeader()) {
      <nxt1-page-header (menuClick)="avatarClick.emit()">
        <!-- Agent X Title in center title slot -->
        <div pageHeaderSlot="title" class="header-logo">
          <span class="header-title-text">Agent</span>
          <svg
            class="header-agent-logo"
            viewBox="0 0 612 792"
            width="40"
            height="40"
            fill="currentColor"
            stroke="currentColor"
            stroke-width="10"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <path
              d="M505.93,251.93c5.52-5.52,1.61-14.96-6.2-14.96h-94.96c-2.32,0-4.55.92-6.2,2.57l-67.22,67.22c-4.2,4.2-11.28,3.09-13.99-2.2l-32.23-62.85c-1.49-2.91-4.49-4.75-7.76-4.76l-83.93-.34c-6.58-.03-10.84,6.94-7.82,12.78l66.24,128.23c1.75,3.39,1.11,7.52-1.59,10.22l-137.13,137.13c-11.58,11.58-3.36,31.38,13.02,31.35l71.89-.13c2.32,0,4.54-.93,6.18-2.57l82.89-82.89c4.19-4.19,11.26-3.1,13.98,2.17l40.68,78.74c1.5,2.91,4.51,4.74,7.78,4.74h82.61c6.55,0,10.79-6.93,7.8-12.76l-73.61-143.55c-1.74-3.38-1.09-7.5,1.6-10.19l137.98-137.98ZM346.75,396.42l69.48,134.68c1.77,3.43-.72,7.51-4.58,7.51h-51.85c-2.61,0-5.01-1.45-6.23-3.76l-48.11-91.22c-2.21-4.19-7.85-5.05-11.21-1.7l-94.71,94.62c-1.32,1.32-3.11,2.06-4.98,2.06h-62.66c-4.1,0-6.15-4.96-3.25-7.85l137.28-137.14c5.12-5.12,6.31-12.98,2.93-19.38l-61.51-116.63c-1.48-2.8.55-6.17,3.72-6.17h56.6c2.64,0,5.05,1.47,6.26,3.81l39.96,77.46c2.19,4.24,7.86,5.12,11.24,1.75l81.05-80.97c1.32-1.32,3.11-2.06,4.98-2.06h63.61c3.75,0,5.63,4.54,2.97,7.19l-129.7,129.58c-2.17,2.17-2.69,5.49-1.28,8.21Z"
            />
            <polygon
              points="390.96 303.68 268.3 411.05 283.72 409.62 205.66 489.34 336.63 377.83 321.21 379.73 390.96 303.68"
            />
          </svg>
        </div>

        <button
          pageHeaderSlot="end"
          type="button"
          class="agent-history-action"
          aria-label="Agent Logs"
          (click)="onActivityLogClick()"
        >
          <nxt1-icon name="time" [size]="22" className="agent-history-icon" />
        </button>
      </nxt1-page-header>
    }

    <!-- ═══ SCROLLABLE CONTENT ═══ -->
    <ion-content [fullscreen]="true" class="agent-x-content">
      <nxt-refresher (onRefresh)="handleRefresh($event)" (onTimeout)="handleRefreshTimeout()" />

      <div class="agent-x-container">
        @if (agentX.dashboardLoading() && !agentX.dashboardLoaded()) {
          <nxt1-agent-x-dashboard-skeleton />
        }

        <!-- ═══ 1. DAILY BRIEFING ═══ -->
        @if (!agentX.dashboardLoading()) {
          <section class="briefing-section" aria-label="Daily briefing">
            <!-- AI Pulse Indicator -->
            <div class="briefing-status">
              <div class="pulse-ring"></div>
              <div class="pulse-dot"></div>
              <span class="status-label">Active</span>
            </div>

            <!-- Greeting -->
            <h2 class="briefing-greeting">{{ greeting() }}</h2>

            <!-- Briefing Summary (Expandable) -->
            <div class="briefing-content">
              @if (!isBriefingExpanded()) {
                <p class="briefing-preview">
                  {{ briefingPreview() }}
                </p>
                <button type="button" class="btn-expand" (click)="isBriefingExpanded.set(true)">
                  Read full briefing
                </button>
              } @else {
                <ul class="briefing-list">
                  @for (insight of briefingInsights(); track insight.id) {
                    <li class="briefing-item">{{ insight.text }}</li>
                  }
                </ul>
                <button type="button" class="btn-expand" (click)="isBriefingExpanded.set(false)">
                  Show less
                </button>
              }
            </div>

            <!-- ═══ 2. DAILY OPERATIONS (Conditional) ═══ -->
            @if (activeOperations().length > 0) {
              <section class="operations-section" aria-label="Daily operations">
                <h3 class="section-title">Daily Operations</h3>
                <div class="operations-scroll">
                  @for (op of activeOperations(); track op.id) {
                    <button
                      type="button"
                      class="operation-card"
                      [class.operation-card--processing]="op.status === 'processing'"
                      [class.operation-card--complete]="op.status === 'complete'"
                      [class.operation-card--error]="op.status === 'error'"
                      (click)="onOperationTap(op)"
                    >
                      <!-- Top row: task icon + label -->
                      <div class="operation-top">
                        <div class="operation-icon">
                          <nxt1-icon [name]="op.icon" [size]="14" />
                        </div>
                        <span class="operation-label">{{ op.label }}</span>
                      </div>

                      <!-- Progress bar -->
                      <div
                        class="operation-progress"
                        [class.operation-progress--complete]="op.status === 'complete'"
                        [class.operation-progress--error]="op.status === 'error'"
                      >
                        <div
                          class="operation-progress-bar"
                          [class.operation-progress-bar--processing]="op.status === 'processing'"
                          [class.operation-progress-bar--complete]="op.status === 'complete'"
                          [class.operation-progress-bar--error]="op.status === 'error'"
                          [style.width.%]="op.status === 'complete' ? 100 : op.progress"
                        ></div>
                      </div>

                      <!-- Bottom row: status badge + spinner/icon -->
                      <div class="operation-status-row">
                        @switch (op.status) {
                          @case ('processing') {
                            <span class="operation-status-badge operation-status-badge--processing">
                              In progress
                            </span>
                            <span class="operation-spinner">
                              <nxt1-icon name="refresh" [size]="12" />
                            </span>
                          }
                          @case ('complete') {
                            <span class="operation-status-badge operation-status-badge--complete">
                              Complete
                            </span>
                            <span class="operation-status-icon operation-status-icon--complete">
                              <nxt1-icon name="checkmarkCircle" [size]="12" />
                            </span>
                          }
                          @case ('error') {
                            <span class="operation-status-badge operation-status-badge--error">
                              Failed
                            </span>
                            <span class="operation-status-icon operation-status-icon--error">
                              <nxt1-icon name="alertCircle" [size]="12" />
                            </span>
                          }
                        }
                      </div>
                    </button>
                  }
                </div>
              </section>
            }

            <!-- ═══ 3. COORDINATORS (2×2 Grid) ═══ -->
            <section class="coordinators-section" aria-label="Coordinators">
              <h3 class="section-title">Coordinators</h3>
              <div class="coordinators-grid">
                @for (cat of commandCategories(); track cat.id) {
                  <button type="button" class="coordinator-card" (click)="onCategoryTap(cat)">
                    <div class="coordinator-card-icon">
                      <nxt1-icon [name]="cat.icon" [size]="18" />
                    </div>
                    <span class="coordinator-card-label">{{ cat.label }}</span>
                  </button>
                }
              </div>
            </section>

            <!-- ═══ 4. WEEKLY PLAYBOOK (Always Visible) ═══ -->
            <section class="playbook-section" aria-label="Weekly playbook">
              <div class="playbook-section-header">
                <div class="playbook-title-row">
                  <h3 class="section-title">Weekly Playbook</h3>
                  @if (agentX.hasGoals() && agentX.canRegenerate()) {
                    <button
                      type="button"
                      class="playbook-regen-btn"
                      [disabled]="agentX.playbookGenerating()"
                      (click)="onRegeneratePlaybook()"
                    >
                      @if (agentX.playbookGenerating()) {
                        <span class="regen-spinner"></span>
                        Generating...
                      } @else {
                        <nxt1-icon name="refresh" [size]="14" />
                        Regenerate
                      }
                    </button>
                  }
                </div>
              </div>

              <!-- Pill Tabs -->
              <div class="playbook-pills" role="tablist" aria-label="Playbook tabs">
                <button
                  type="button"
                  role="tab"
                  class="playbook-pill"
                  [class.playbook-pill--active]="playbookTab() === 'get-started'"
                  [attr.aria-selected]="playbookTab() === 'get-started'"
                  (click)="playbookTab.set('get-started')"
                >
                  @if (agentX.hasGoals()) {
                    My Playbook
                  } @else {
                    Get Started
                  }
                </button>
                <button
                  type="button"
                  role="tab"
                  class="playbook-pill"
                  [class.playbook-pill--active]="playbookTab() === 'create-goals'"
                  [attr.aria-selected]="playbookTab() === 'create-goals'"
                  (click)="playbookTab.set('create-goals')"
                >
                  @if (agentX.hasGoals()) {
                    My Goals
                  } @else {
                    Create Goals
                  }
                </button>
              </div>

              <!-- Tab Content: Get Started -->
              @if (playbookTab() === 'get-started') {
                <ol class="weekly-timeline">
                  @for (item of weeklyPlaybook(); track item.id; let isLast = $last) {
                    <li class="timeline-item">
                      <div class="timeline-rail" aria-hidden="true">
                        <span
                          class="timeline-marker"
                          [class.timeline-marker--pending]="item.status === 'pending'"
                          [class.timeline-marker--in-progress]="item.status === 'in-progress'"
                          [class.timeline-marker--complete]="item.status === 'complete'"
                          [class.timeline-marker--problem]="item.status === 'problem'"
                        >
                          @if (item.status === 'in-progress') {
                            <nxt1-icon name="play" [size]="10" />
                          } @else if (item.status === 'complete') {
                            <nxt1-icon name="checkmark" [size]="12" />
                          } @else if (item.status === 'problem') {
                            <nxt1-icon name="pause" [size]="10" />
                          } @else {
                            <span class="timeline-marker-dot"></span>
                          }
                        </span>
                        @if (!isLast) {
                          <span class="timeline-line"></span>
                        }
                      </div>

                      <article class="timeline-card">
                        <button
                          type="button"
                          class="timeline-toggle"
                          (click)="onPlaybookAction(item)"
                        >
                          <div class="timeline-toggle-top">
                            <h4 class="timeline-title">{{ item.title }}</h4>
                            @if (item.goal) {
                              <span class="timeline-goal-tag">{{ item.goal.label }}</span>
                            }
                          </div>
                        </button>
                      </article>
                    </li>
                  }
                </ol>
              }

              <!-- Tab Content: Create Goals / My Goals -->
              @if (playbookTab() === 'create-goals') {
                <div class="playbook-create-goals">
                  @if (agentX.hasGoals()) {
                    <!-- Show existing goals -->
                    <ul class="goals-list">
                      @for (goal of agentX.goals(); track goal.id) {
                        <li class="goal-item">
                          <nxt1-icon
                            [name]="goal.icon ?? 'flag'"
                            [size]="18"
                            className="goal-icon"
                          />
                          <span class="goal-text">{{ goal.text }}</span>
                        </li>
                      }
                    </ul>
                    <button
                      type="button"
                      class="playbook-setup-btn playbook-setup-btn--secondary"
                      (click)="onSetupGoals()"
                    >
                      <nxt1-icon name="create" [size]="16" />
                      Update Goals
                    </button>
                  } @else {
                    <div class="playbook-empty">
                      <div class="playbook-empty-icon">
                        <nxt1-icon name="flag" [size]="24" />
                      </div>
                      <h4 class="playbook-empty-title">Set Your Goals</h4>
                      <p class="playbook-empty-description">
                        Tell Agent X what you want to achieve this season and it will build a
                        personalized weekly playbook for you.
                      </p>
                      <button type="button" class="playbook-setup-btn" (click)="onSetupGoals()">
                        <nxt1-icon name="plus" [size]="16" />
                        Create Goals
                      </button>
                    </div>
                  }
                </div>
              }
            </section>
          </section>
        }
      </div>
    </ion-content>

    <!-- ═══ INPUT BAR — Fixed above footer ═══ -->
    <nxt1-agent-x-input
      [hasMessages]="false"
      [selectedTask]="agentX.selectedTask()"
      [isLoading]="agentX.isLoading()"
      [canSend]="agentX.canSend()"
      [userMessage]="agentX.getUserMessage()"
      [placeholder]="'Message A Coordinator'"
      (messageChange)="agentX.setUserMessage($event)"
      (send)="onSendMessage()"
      (removeTask)="agentX.clearTask()"
      (toggleTasks)="onToggleTasks()"
    />
  `,
  styles: [
    `
      /* ============================================
         AGENT X COMMAND CENTER — 2026 AI-FIRST
         100% Theme Aware (Light + Dark Mode)
         ============================================ */

      :host {
        display: block;
        height: 100%;
        width: 100%;

        --agent-bg: var(--nxt1-color-bg-primary, var(--ion-background-color, #0a0a0a));
        --agent-surface: var(--nxt1-color-surface-100, rgba(255, 255, 255, 0.04));
        --agent-surface-hover: var(--nxt1-color-surface-200, rgba(255, 255, 255, 0.06));
        --agent-border: var(--nxt1-color-border-subtle, rgba(255, 255, 255, 0.08));
        --agent-text-primary: var(--nxt1-color-text-primary, #ffffff);
        --agent-text-secondary: var(--nxt1-color-text-secondary, rgba(255, 255, 255, 0.7));
        --agent-text-muted: var(--nxt1-color-text-tertiary, rgba(255, 255, 255, 0.5));
        --agent-primary: var(--nxt1-color-primary, #ccff00);
        --agent-primary-glow: var(--nxt1-color-alpha-primary10, rgba(204, 255, 0, 0.1));
        --agent-glass-bg: var(--nxt1-glass-bg, rgba(18, 18, 18, 0.8));
        --agent-glass-border: var(--nxt1-glass-border, rgba(255, 255, 255, 0.1));
      }

      :host-context(.light),
      :host-context([data-theme='light']) {
        --agent-bg: var(--nxt1-color-bg-primary, #ffffff);
        --agent-surface: var(--nxt1-color-surface-100, rgba(0, 0, 0, 0.03));
        --agent-surface-hover: var(--nxt1-color-surface-200, rgba(0, 0, 0, 0.05));
        --agent-border: var(--nxt1-color-border-subtle, rgba(0, 0, 0, 0.08));
        --agent-text-primary: var(--nxt1-color-text-primary, #1a1a1a);
        --agent-text-secondary: var(--nxt1-color-text-secondary, rgba(0, 0, 0, 0.7));
        --agent-text-muted: var(--nxt1-color-text-tertiary, rgba(0, 0, 0, 0.5));
        --agent-glass-bg: var(--nxt1-glass-bg, rgba(255, 255, 255, 0.8));
      }

      /* ── Header Logo ── */
      .header-logo {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 0;
        width: 100%;
        margin-top: -8px;
        margin-left: -18px;
      }

      .header-title-text {
        display: inline-flex;
        align-items: center;
        font-family: var(--nxt1-font-family-brand, var(--ion-font-family));
        font-size: var(--nxt1-font-size-xl, 20px);
        font-weight: var(--nxt1-font-weight-semibold, 600);
        letter-spacing: var(--nxt1-letter-spacing-tight, -0.01em);
        color: var(--agent-text-primary);
        line-height: 1;
        transform: translateY(1px);
      }

      .header-agent-logo {
        display: block;
        flex-shrink: 0;
        color: var(--agent-text-primary);
        transform: translateY(1px);
      }

      .agent-history-action {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 40px;
        height: 40px;
        border: 0;
        border-radius: 9999px;
        padding: 0;
        background: transparent;
        color: var(--agent-text-primary);
      }

      .agent-history-icon {
        display: block;
      }

      /* ── Content Area ── */
      .agent-x-content {
        --background: var(--agent-bg);
      }

      .agent-x-container {
        display: flex;
        flex-direction: column;
        min-height: 100%;
        padding: var(--nxt1-spacing-4, 16px);
        padding-bottom: calc(200px + env(safe-area-inset-bottom, 0px));
      }

      @media (max-width: 767px) {
        .agent-x-container {
          padding-bottom: calc(260px + env(safe-area-inset-bottom, 0px));
        }
      }

      /* ──────────────────────────────────
         1. DAILY OPERATIONS
         ────────────────────────────────── */

      /* Spin animation for processing spinner */
      @keyframes op-spin {
        from {
          transform: rotate(0deg);
        }
        to {
          transform: rotate(360deg);
        }
      }

      /* Subtle border glow for active processing cards */
      @keyframes op-pulse-border {
        0%,
        100% {
          border-color: var(--agent-primary-glow);
        }
        50% {
          border-color: var(--agent-primary);
        }
      }

      /* Glow on the progress bar fill */
      @keyframes op-bar-glow {
        0%,
        100% {
          box-shadow: 0 0 4px transparent;
        }
        50% {
          box-shadow: 0 0 6px var(--agent-primary);
        }
      }

      .operations-section {
        width: 100%;
        margin-bottom: var(--nxt1-spacing-5, 20px);
      }

      .operations-scroll {
        display: flex;
        gap: var(--nxt1-spacing-3, 12px);
        overflow-x: auto;
        scrollbar-width: none;
        -webkit-overflow-scrolling: touch;
        padding-bottom: 2px;
      }

      .operations-scroll::-webkit-scrollbar {
        display: none;
      }

      /* ── Card ── */
      .operation-card {
        display: flex;
        flex-direction: column;
        gap: var(--nxt1-spacing-2, 8px);
        flex-shrink: 0;
        width: 200px;
        padding: var(--nxt1-spacing-3, 12px);
        background: var(--agent-surface);
        border: 1px solid var(--agent-border);
        border-radius: var(--nxt1-radius-lg, 14px);
        cursor: pointer;
        font-family: inherit;
        -webkit-tap-highlight-color: transparent;
        transition:
          background 0.2s ease,
          border-color 0.3s ease,
          box-shadow 0.3s ease;
      }

      .operation-card:active {
        background: var(--agent-surface-hover);
      }

      /* Processing — breathing border glow */
      .operation-card--processing {
        border-color: var(--agent-primary-glow);
        animation: op-pulse-border 2.4s ease-in-out infinite;
      }

      /* Complete — subtle green tint */
      .operation-card--complete {
        border-color: var(--nxt1-color-success-border, rgba(76, 175, 80, 0.25));
        background: var(--nxt1-color-success-surface, rgba(76, 175, 80, 0.05));
      }

      /* Error — subtle red tint */
      .operation-card--error {
        border-color: var(--nxt1-color-error-border, rgba(244, 67, 54, 0.25));
        background: var(--nxt1-color-error-surface, rgba(244, 67, 54, 0.05));
      }

      /* ── Top row (icon + label) ── */
      .operation-top {
        display: flex;
        align-items: center;
        gap: var(--nxt1-spacing-2, 8px);
      }

      .operation-icon {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 26px;
        height: 26px;
        border-radius: var(--nxt1-radius-full, 9999px);
        background: var(--agent-primary-glow);
        color: var(--agent-primary);
        flex-shrink: 0;
      }

      .operation-card--complete .operation-icon {
        background: var(--nxt1-color-success-surface, rgba(76, 175, 80, 0.1));
        color: var(--nxt1-color-success, #4caf50);
      }

      .operation-card--error .operation-icon {
        background: var(--nxt1-color-error-surface, rgba(244, 67, 54, 0.1));
        color: var(--nxt1-color-error, #f44336);
      }

      .operation-label {
        font-size: var(--nxt1-font-size-sm, 13px);
        font-weight: var(--nxt1-font-weight-medium, 500);
        color: var(--agent-text-primary);
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        line-height: 1.3;
      }

      /* ── Progress bar ── */
      .operation-progress {
        width: 100%;
        height: 3px;
        background: var(--agent-border);
        border-radius: var(--nxt1-radius-full, 9999px);
        overflow: hidden;
      }

      .operation-progress-bar {
        height: 100%;
        background: var(--agent-primary);
        border-radius: var(--nxt1-radius-full, 9999px);
        transition: width 0.4s ease;
      }

      .operation-progress-bar--processing {
        animation: op-bar-glow 2s ease-in-out infinite;
      }

      .operation-progress-bar--complete {
        background: var(--nxt1-color-success, #4caf50);
      }

      .operation-progress-bar--error {
        background: var(--nxt1-color-error, #f44336);
      }

      /* ── Status row (badge + icon/spinner) ── */
      .operation-status-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
      }

      .operation-status-badge {
        font-size: 10px;
        font-weight: var(--nxt1-font-weight-semibold, 600);
        letter-spacing: 0.04em;
        text-transform: uppercase;
        line-height: 1;
      }

      .operation-status-badge--processing {
        color: var(--agent-primary);
      }

      .operation-status-badge--complete {
        color: var(--nxt1-color-success, #4caf50);
      }

      .operation-status-badge--error {
        color: var(--nxt1-color-error, #f44336);
      }

      /* Spinning refresh icon */
      .operation-spinner {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        color: var(--agent-primary);
        animation: op-spin 1.2s linear infinite;
      }

      /* Static status icons */
      .operation-status-icon {
        display: inline-flex;
        align-items: center;
        justify-content: center;
      }

      .operation-status-icon--complete {
        color: var(--nxt1-color-success, #4caf50);
      }

      .operation-status-icon--error {
        color: var(--nxt1-color-error, #f44336);
      }

      /* ──────────────────────────────────
         2. DAILY BRIEFING
         ────────────────────────────────── */
      .briefing-section {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        text-align: left;
        padding: var(--nxt1-spacing-6, 24px) 0 var(--nxt1-spacing-4, 16px);
      }

      /* AI Active Pulse */
      .briefing-status {
        display: flex;
        align-items: center;
        gap: var(--nxt1-spacing-2, 8px);
        margin-bottom: var(--nxt1-spacing-5, 20px);
        position: relative;
      }

      .pulse-dot {
        width: 8px;
        height: 8px;
        border-radius: 50%;
        background: var(--agent-primary);
      }

      .pulse-ring {
        position: absolute;
        left: 0;
        top: 50%;
        transform: translateY(-50%);
        width: 8px;
        height: 8px;
        border-radius: 50%;
        border: 1.5px solid var(--agent-primary);
        animation: pulse-expand 2s ease-out infinite;
      }

      @keyframes pulse-expand {
        0% {
          transform: translateY(-50%) scale(1);
          opacity: 0.8;
        }
        100% {
          transform: translateY(-50%) scale(3);
          opacity: 0;
        }
      }

      .status-label {
        font-size: 12px;
        font-weight: 600;
        letter-spacing: 0.03em;
        color: var(--agent-primary);
      }

      /* Greeting */
      .briefing-greeting {
        font-size: 22px;
        font-weight: 700;
        color: var(--agent-text-primary);
        margin: 0 0 var(--nxt1-spacing-5, 20px);
        line-height: 1.3;
      }

      /* Expandable Briefing */
      .briefing-content {
        width: 100%;
        margin-bottom: var(--nxt1-spacing-6, 24px);
      }

      .briefing-preview {
        font-size: 14px;
        line-height: 1.5;
        color: var(--agent-text-secondary);
        margin: 0 0 var(--nxt1-spacing-3, 12px);
        /* Simple truncation to 2 lines */
        display: -webkit-box;
        -webkit-line-clamp: 2;
        line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
      }

      .btn-expand {
        background: transparent;
        border: none;
        padding: 0;
        font-size: 13px;
        font-weight: 600;
        color: var(--agent-primary);
        cursor: pointer;
        display: inline-flex;
        align-items: center;
        gap: 4px;
      }

      /* Briefing List */
      .briefing-list {
        list-style: none;
        padding: 0;
        margin: 0 0 var(--nxt1-spacing-4, 16px);
        width: 100%;
        text-align: left;
      }

      .briefing-item {
        position: relative;
        padding-left: var(--nxt1-spacing-4, 16px);
        font-size: 14px;
        line-height: 1.6;
        color: var(--agent-text-secondary);
        margin-bottom: var(--nxt1-spacing-3, 12px);
      }

      .briefing-item:last-child {
        margin-bottom: 0;
      }

      .briefing-item::before {
        content: '';
        position: absolute;
        left: 0;
        top: 9px;
        width: 5px;
        height: 5px;
        border-radius: 50%;
        background: var(--agent-text-muted);
      }

      /* ──────────────────────────────────
         SHARED SECTION TITLE
         ────────────────────────────────── */
      .section-title {
        font-size: 13px;
        font-weight: 600;
        letter-spacing: 0.02em;
        color: var(--agent-text-muted);
        margin: 0 0 var(--nxt1-spacing-3, 12px);
      }

      /* ──────────────────────────────────
         3. WEEKLY PLAYBOOK (Timeline)
         ────────────────────────────────── */
      .playbook-section {
        width: 100%;
        margin-bottom: var(--nxt1-spacing-6, 24px);
      }

      .playbook-section-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: var(--nxt1-spacing-2, 8px);
        margin-bottom: var(--nxt1-spacing-3, 12px);
      }

      .playbook-title-row {
        display: flex;
        align-items: center;
        gap: var(--nxt1-spacing-2, 8px);
        min-width: 0;
        flex: 1;
      }

      .playbook-section-header .section-title {
        margin: 0;
        flex-shrink: 0;
      }

      /* Playbook Pill Tabs */
      .playbook-pills {
        display: flex;
        gap: var(--nxt1-spacing-2, 8px);
        margin-bottom: var(--nxt1-spacing-4, 16px);
      }

      .playbook-pill {
        display: inline-flex;
        align-items: center;
        padding: 6px 16px;
        border-radius: var(--nxt1-radius-full, 9999px);
        border: 1px solid var(--agent-border);
        background: var(--agent-surface);
        color: var(--agent-text-secondary);
        font-size: 13px;
        font-weight: 600;
        cursor: pointer;
        font-family: inherit;
        -webkit-tap-highlight-color: transparent;
        transition: all 0.15s ease;
        white-space: nowrap;
      }

      .playbook-pill:active {
        background: var(--agent-surface-hover);
      }

      .playbook-pill--active {
        background: var(--agent-primary);
        border-color: var(--agent-primary);
        color: #000;
      }

      .playbook-pill--active:active {
        background: var(--agent-primary);
        opacity: 0.9;
      }

      .playbook-create-goals {
        margin-top: var(--nxt1-spacing-1, 4px);
      }

      .weekly-timeline {
        list-style: none;
        margin: 0;
        padding: 0;
        display: flex;
        flex-direction: column;
        gap: var(--nxt1-spacing-3, 12px);
      }

      .timeline-item {
        display: flex;
        align-items: stretch;
        gap: var(--nxt1-spacing-2, 8px);
      }

      .timeline-rail {
        width: 18px;
        display: flex;
        flex-direction: column;
        align-items: center;
      }

      .timeline-marker {
        width: 18px;
        height: 18px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        border-radius: 50%;
        margin-top: 9px;
        background: var(--agent-surface);
        border: 1px solid var(--agent-border);
      }

      .timeline-marker-dot {
        width: 8px;
        height: 8px;
        border-radius: 50%;
        background: var(--agent-primary);
      }

      .timeline-marker--pending {
        border-color: color-mix(in srgb, var(--agent-primary) 40%, var(--agent-border));
      }

      .timeline-marker--in-progress {
        border-color: var(--agent-primary);
        background: var(--agent-primary-glow);
        color: var(--agent-primary);
      }

      .timeline-marker--complete {
        border-color: var(--nxt1-color-success, #4caf50);
        background: color-mix(in srgb, var(--nxt1-color-success, #4caf50) 16%, transparent);
        color: var(--nxt1-color-success, #4caf50);
      }

      .timeline-marker--problem {
        border-color: var(--nxt1-color-warning, #ffb020);
        background: color-mix(in srgb, var(--nxt1-color-warning, #ffb020) 16%, transparent);
        color: var(--nxt1-color-warning, #ffb020);
      }

      .timeline-line {
        flex: 1;
        width: 1px;
        margin-top: 6px;
        background: var(--agent-border);
      }

      .timeline-card {
        flex: 1;
        background: var(--agent-surface);
        border: 1px solid var(--agent-border);
        border-radius: var(--nxt1-radius-lg, 12px);
        transition:
          border-color 0.2s ease,
          background 0.2s ease;
        overflow: hidden;
      }

      .timeline-item--expanded .timeline-card,
      .timeline-card:active {
        background: var(--agent-surface-hover);
        border-color: var(--agent-primary);
      }

      .timeline-toggle {
        display: block;
        width: 100%;
        padding: var(--nxt1-spacing-3, 12px) var(--nxt1-spacing-4, 16px);
        border: 0;
        background: transparent;
        color: inherit;
        text-align: left;
        cursor: pointer;
      }

      .timeline-toggle-top {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: var(--nxt1-spacing-2, 8px);
        margin-bottom: 0;
      }

      .timeline-goal-tag {
        display: inline-flex;
        align-items: center;
        padding: 2px 8px;
        background: var(--agent-primary-glow);
        border-radius: var(--nxt1-radius-full, 9999px);
        color: var(--agent-primary);
        font-size: 11px;
        font-weight: 600;
        white-space: nowrap;
        flex-shrink: 0;
      }

      .timeline-title {
        font-size: 15px;
        font-weight: 600;
        color: var(--agent-text-primary);
        margin: 0;
        line-height: 1.3;
        min-width: 0;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }

      .timeline-summary {
        font-size: 13px;
        line-height: 1.4;
        color: var(--agent-text-secondary);
        margin: 0;
      }

      .timeline-details {
        border-top: 1px solid var(--agent-border);
        padding: var(--nxt1-spacing-3, 12px) var(--nxt1-spacing-4, 16px);
      }

      .timeline-details-text {
        margin: 0 0 var(--nxt1-spacing-3, 12px);
        font-size: 13px;
        line-height: 1.45;
        color: var(--agent-text-secondary);
      }

      .timeline-actions {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: var(--nxt1-spacing-2, 8px);
      }

      .timeline-status {
        font-size: 11px;
        font-weight: 600;
        letter-spacing: 0.03em;
        text-transform: uppercase;
      }

      .timeline-status--pending {
        color: var(--agent-text-muted);
      }

      .timeline-status--in-progress {
        color: var(--agent-primary);
      }

      .timeline-status--complete {
        color: #4caf50;
      }

      .playbook-action-btn {
        display: inline-flex;
        align-items: center;
        gap: 6px;
        padding: 6px 14px;
        background: var(--agent-primary);
        color: #000;
        border: none;
        border-radius: var(--nxt1-radius-full, 9999px);
        font-size: 13px;
        font-weight: 600;
        cursor: pointer;
        transition: opacity 0.15s ease;
        -webkit-tap-highlight-color: transparent;
      }

      .playbook-action-btn:active {
        opacity: 0.85;
      }

      /* ── Playbook Empty State (No Goals) ── */
      .playbook-empty {
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
        padding: var(--nxt1-spacing-6, 24px) var(--nxt1-spacing-4, 16px);
        background: var(--agent-surface);
        border: 1px dashed var(--agent-border);
        border-radius: var(--nxt1-radius-lg, 14px);
      }

      .playbook-empty-icon {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 48px;
        height: 48px;
        border-radius: var(--nxt1-radius-full, 9999px);
        background: var(--agent-primary-glow);
        color: var(--agent-primary);
        margin-bottom: var(--nxt1-spacing-3, 12px);
      }

      .playbook-empty-title {
        font-size: 15px;
        font-weight: 600;
        color: var(--agent-text-primary);
        margin: 0 0 var(--nxt1-spacing-2, 8px);
        line-height: 1.3;
      }

      .playbook-empty-description {
        font-size: 13px;
        line-height: 1.5;
        color: var(--agent-text-secondary);
        margin: 0 0 var(--nxt1-spacing-4, 16px);
        max-width: 280px;
      }

      .playbook-setup-btn {
        display: inline-flex;
        align-items: center;
        gap: 6px;
        padding: 10px 20px;
        background: var(--agent-primary);
        color: #000;
        border: none;
        border-radius: var(--nxt1-radius-full, 9999px);
        font-size: 14px;
        font-weight: 600;
        cursor: pointer;
        font-family: inherit;
        -webkit-tap-highlight-color: transparent;
        transition: opacity 0.15s ease;
      }

      .playbook-setup-btn:active {
        opacity: 0.85;
      }

      .playbook-setup-btn--secondary {
        background: var(--agent-surface);
        color: var(--agent-text-primary);
        border: 1px solid var(--agent-border);
      }

      .playbook-regen-btn {
        display: inline-flex;
        align-items: center;
        gap: 4px;
        padding: 6px 12px;
        font-size: 12px;
        font-weight: 600;
        color: var(--agent-text-secondary);
        background: var(--agent-surface);
        border: 1px solid var(--agent-border);
        border-radius: var(--nxt1-radius-full, 9999px);
        cursor: pointer;
        font-family: inherit;
        -webkit-tap-highlight-color: transparent;
        transition: all 0.15s ease;
      }

      .playbook-regen-btn:active:not(:disabled) {
        background: var(--agent-surface-hover);
        color: var(--agent-text-primary);
      }

      .playbook-regen-btn:disabled {
        opacity: 0.6;
        cursor: not-allowed;
      }

      .regen-spinner {
        display: inline-block;
        width: 12px;
        height: 12px;
        border: 2px solid var(--agent-border);
        border-top-color: var(--agent-text-secondary);
        border-radius: 50%;
        animation: regen-spin 0.6s linear infinite;
      }

      @keyframes regen-spin {
        to {
          transform: rotate(360deg);
        }
      }

      .goals-list {
        list-style: none;
        margin: 0 0 var(--nxt1-spacing-4, 16px);
        padding: 0;
        display: flex;
        flex-direction: column;
        gap: var(--nxt1-spacing-2, 8px);
      }

      .goal-item {
        display: flex;
        align-items: center;
        gap: var(--nxt1-spacing-3, 12px);
        padding: var(--nxt1-spacing-3, 12px) var(--nxt1-spacing-4, 16px);
        background: var(--agent-surface);
        border: 1px solid var(--agent-border);
        border-radius: var(--nxt1-radius-md, 8px);
      }

      .goal-icon {
        color: var(--agent-primary);
        flex-shrink: 0;
      }

      .goal-text {
        font-size: 14px;
        font-weight: 500;
        color: var(--agent-text-primary);
      }

      /* ──────────────────────────────────
         2. COORDINATORS (2×2 Grid)
         ────────────────────────────────── */
      .coordinators-section {
        display: flex;
        flex-direction: column;
        gap: var(--nxt1-spacing-3, 12px);
        margin-bottom: var(--nxt1-spacing-5, 20px);
        width: 100%;
      }

      .coordinators-section .section-title {
        margin-bottom: 0;
      }

      .coordinators-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: var(--nxt1-spacing-3, 12px);
      }

      .coordinator-card {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: var(--nxt1-spacing-2, 8px);
        padding: var(--nxt1-spacing-4, 16px) var(--nxt1-spacing-3, 12px);
        background: var(--agent-surface);
        border: 1px solid var(--agent-border);
        border-radius: var(--nxt1-radius-lg, 12px);
        cursor: pointer;
        -webkit-tap-highlight-color: transparent;
        transition:
          background 0.15s ease,
          border-color 0.15s ease;
      }

      .coordinator-card:active {
        background: var(--agent-surface-hover);
        border-color: var(--agent-primary);
      }

      .coordinator-card-icon {
        width: 36px;
        height: 36px;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: var(--nxt1-radius-md, 8px);
        background: var(--agent-primary-glow);
        color: var(--agent-primary);
      }

      .coordinator-card-label {
        font-size: 12px;
        font-weight: 600;
        color: var(--agent-text-primary);
        text-align: center;
        line-height: 1.3;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AgentXShellComponent {
  protected readonly agentX = inject(AgentXService);
  private readonly haptics = inject(HapticsService);
  private readonly toast = inject(NxtToastService);
  private readonly bottomSheet = inject(NxtBottomSheetService);

  // ============================================
  // INPUTS
  // ============================================

  /** Current user info. */
  readonly user = input<AgentXUser | null>(null);

  /** Hide page header (desktop sidebar provides navigation). */
  readonly hideHeader = input(false);

  // ============================================
  // LOCAL STATE
  // ============================================

  /** Whether the full briefing list is expanded. */
  protected readonly isBriefingExpanded = signal(false);

  /** Active playbook tab. */
  protected readonly playbookTab = signal<'get-started' | 'create-goals'>('get-started');

  // ============================================
  // OUTPUTS
  // ============================================

  /** Emitted when avatar/hamburger is clicked (open sidenav). */
  readonly avatarClick = output<void>();

  /** Emitted when an action chip is tapped. */
  readonly chipTap = output<ActionChip>();

  // ============================================
  // COMPUTED
  // ============================================

  /** Display name for header avatar fallback. */
  protected displayName(): string {
    return this.user()?.displayName ?? 'User';
  }

  /** Time-aware greeting for the Daily Briefing. */
  protected readonly greeting = computed(() => {
    const name = this.user()?.displayName?.split(' ')[0] ?? '';
    const hour = new Date().getHours();
    const timeGreeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening';
    return name ? `${timeGreeting}, ${name}.` : `${timeGreeting}.`;
  });

  // ============================================
  // ROLE-AWARE SHELL CONTENT
  // Uses live dashboard data from AgentXService only.
  // Static fallback content is intentionally disabled to avoid mock-data flashes.
  // ============================================

  /** Active background operations — live from service only. */
  protected readonly activeOperations = computed<ShellActiveOperation[]>(() =>
    this.agentX.activeOperations()
  );

  /** Proactive insights from Agent X — live from service only. */
  protected readonly briefingInsights = computed(() => this.agentX.briefingInsights());

  /** Briefing preview text — live from service only. */
  protected readonly briefingPreview = computed(() => this.agentX.briefingPreviewText());

  /** AI-generated weekly playbook timeline items — live from service only. */
  protected readonly weeklyPlaybook = computed<ShellWeeklyPlaybookItem[]>(() =>
    this.agentX.weeklyPlaybook()
  );

  /** Number of completed playbook tasks. */
  protected readonly playbookCompletedCount = computed(
    () => this.weeklyPlaybook().filter((t) => t.status === 'complete').length
  );

  /** Total number of playbook tasks. */
  protected readonly playbookTotalCount = computed(() => this.weeklyPlaybook().length);

  // ============================================
  // COORDINATORS — Role-Aware Virtual Staff
  // ============================================

  /** Coordinator cards — live from service only. */
  protected readonly commandCategories = computed(() => this.agentX.coordinators());

  // ============================================
  // HEADER CONFIG
  // ============================================

  constructor() {
    afterNextRender(() => {
      this.agentX.startTitleAnimation();
      this.agentX.loadDashboard();
    });

    effect(() => {
      const pending = this.agentX.pendingThread();
      if (!pending) return;

      // Consume the request immediately to prevent duplicate sheet opens
      // if dashboard signals or route rendering re-run the effect.
      this.agentX.clearPendingThread();

      void this.openOperationChat(
        pending.operationId ?? pending.threadId,
        pending.title,
        pending.icon ?? 'sparkles',
        'operation',
        [],
        '',
        pending.threadId
      );
    });
  }

  // ============================================
  // EVENT HANDLERS
  // ============================================

  protected async onActivityLogClick(): Promise<void> {
    await this.haptics.impact('light');
    await this.bottomSheet.openSheet({
      component: AgentXOperationsLogComponent,
      ...SHEET_PRESETS.FULL,
      showHandle: true,
      handleBehavior: 'cycle',
      backdropDismiss: true,
      cssClass: 'agent-x-operations-log-sheet',
    });
  }

  /**
   * Handle "Set Your Goals" button from the empty playbook state.
   * Opens Agent X goal setup conversation.
   */
  protected async onSetupGoals(): Promise<void> {
    await this.haptics.impact('medium');
    await this.openOperationChat('goal-setup', 'Set Your Goals', 'flag', 'command');
  }

  /**
   * Handle "Regenerate" playbook button.
   */
  protected async onRegeneratePlaybook(): Promise<void> {
    await this.haptics.impact('medium');
    await this.agentX.generatePlaybook(true);
  }

  /**
   * Handle weekly playbook action tap — dispatches real job when dashboard loaded,
   * otherwise opens dedicated bottom sheet chat.
   */
  protected async onPlaybookAction(task: WeeklyPlaybookItem): Promise<void> {
    await this.haptics.impact('medium');
    if (task.id === 'goal-setup') {
      await this.onSetupGoals();
      return;
    }
    if (this.agentX.dashboardLoaded()) {
      await this.agentX.executePlaybookAction(task as ShellWeeklyPlaybookItem);
    } else {
      await this.openOperationChat(task.id, task.title, 'clipboard', 'command');
    }
  }

  /**
   * Handle category pill tap — opens bottom sheet with sub-commands as suggestion chips.
   */
  protected async onCategoryTap(cat: CommandCategory): Promise<void> {
    await this.haptics.impact('light');
    const quickActions: OperationQuickAction[] = cat.commands.map((cmd) => ({
      id: cmd.id,
      label: cmd.label,
      icon: cmd.icon,
    }));
    await this.openOperationChat(
      cat.id,
      cat.label,
      cat.icon,
      'command',
      quickActions,
      cat.description
    );
  }

  /**
   * Handle action chip tap — opens dedicated bottom sheet chat.
   */
  protected async onChipTap(chip: ActionChip): Promise<void> {
    await this.haptics.impact('light');
    this.chipTap.emit(chip);
    await this.openOperationChat(chip.id, chip.label, chip.icon, 'command');
  }

  /**
   * Handle active operation card tap — opens dedicated bottom sheet chat.
   */
  protected async onOperationTap(op: ActiveOperation): Promise<void> {
    await this.haptics.impact('light');
    // Pass the persisted thread ID so the sheet loads the worker's actual output logs
    // rather than opening a blank new chat session.
    await this.openOperationChat(op.id, op.label, op.icon, 'operation', [], '', op.threadId ?? '');
  }

  /**
   * Open the dedicated bottom sheet chat for an operation or command.
   */
  private async openOperationChat(
    contextId: string,
    contextTitle: string,
    contextIcon: string,
    contextType: 'operation' | 'command',
    quickActions: OperationQuickAction[] = [],
    contextDescription = '',
    threadId = ''
  ): Promise<void> {
    await this.bottomSheet.openSheet({
      component: AgentXOperationChatComponent,
      componentProps: {
        contextId,
        contextTitle,
        contextIcon,
        contextType,
        quickActions,
        contextDescription,
        threadId,
      },
      ...SHEET_PRESETS.FULL,
      showHandle: true,
      handleBehavior: 'cycle',
      backdropDismiss: true,
      cssClass: 'agent-x-operation-sheet',
    });
  }

  /**
   * Handle send message — opens the Agent X bottom sheet chat
   * with the user's message instead of displaying inline.
   */
  protected async onSendMessage(): Promise<void> {
    const message = this.agentX.getUserMessage().trim();
    if (!message) return;

    // Clear the shell input immediately
    this.agentX.setUserMessage('');
    this.agentX.clearTask();
    await this.haptics.impact('light');

    // Open the operation chat bottom sheet with the message
    await this.bottomSheet.openSheet({
      component: AgentXOperationChatComponent,
      componentProps: {
        contextId: 'agent-x-chat',
        contextTitle: 'Agent X',
        contextIcon: 'bolt',
        contextType: 'command',
        initialMessage: message,
      },
      ...SHEET_PRESETS.FULL,
      showHandle: true,
      handleBehavior: 'cycle',
      backdropDismiss: true,
      cssClass: 'agent-x-operation-sheet',
    });
  }

  /**
   * Handle toggle tasks panel.
   */
  protected async onToggleTasks(): Promise<void> {
    await this.haptics.impact('light');
    this.toast.info('Task panel coming soon');
  }

  /**
   * Handle pull-to-refresh — reloads dashboard data.
   */
  protected async handleRefresh(event: RefreshEvent): Promise<void> {
    await this.agentX.loadDashboard();
    event.complete();
  }

  /**
   * Handle refresh timeout.
   */
  protected async handleRefreshTimeout(): Promise<void> {
    await this.haptics.notification('warning');
    this.toast.warning('Refresh timed out');
  }
}
