/**
 * @fileoverview Agent X Shell Component - AI Command Center
 * @module @nxt1/ui/agent-x
 * @version 2.0.0
 *
 * Redesigned AI-first command center with proactive Daily Briefing,
 * Active Operations queue, and contextual Action Chips.
 *
 * ⭐ SHARED BETWEEN WEB AND MOBILE ⭐
 *
 * Layout (top → bottom):
 * 1. Page Header — Agent X logo centered (no text title)
 * 2. Active Operations — Horizontal WIP task cards (conditional)
 * 3. Daily Briefing — Proactive AI insights card
 * 4. Weekly Playbook — Collapsible weekly timeline
 * 5. Quick Commands — Utility action pills
 * 6. Activity Log — Operation records and context
 * 7. Input Bar — Fixed above footer (already exists)
 *
 * @example
 * ```html
 * <nxt1-agent-x-shell
 *   [user]="currentUser()"
 *   (avatarClick)="openSidenav()"
 * />
 * ```
 */

import {
  Component,
  ChangeDetectionStrategy,
  inject,
  input,
  output,
  signal,
  computed,
  afterNextRender,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { IonContent } from '@ionic/angular/standalone';
import { NxtPageHeaderComponent } from '../components/page-header';
import { NxtRefresherComponent, type RefreshEvent } from '../components/refresh-container';
import { NxtIconComponent } from '../components/icon';
import { AgentXService } from './agent-x.service';
import { AgentXChatComponent } from './agent-x-chat.component';
import { AgentXInputComponent } from './agent-x-input.component';
import {
  AgentXOperationChatComponent,
  type OperationQuickAction,
} from './agent-x-operation-chat.component';
import { AgentXOperationsLogComponent } from './agent-x-operations-log.component';
import { HapticsService } from '../services/haptics/haptics.service';
import { NxtToastService } from '../services/toast/toast.service';
import { NxtBottomSheetService } from '../components/bottom-sheet';

// ============================================
// INTERFACES
// ============================================

/** User info for header display. */
export interface AgentXUser {
  readonly profileImg?: string | null;
  readonly displayName?: string | null;
  readonly role?: string;
}

/** An active background operation Agent X is processing. */
export interface ActiveOperation {
  readonly id: string;
  readonly label: string;
  readonly progress: number; // 0–100
  readonly icon: string;
  readonly status: 'processing' | 'complete' | 'error';
}

/** A contextual action chip for quick workflows. */
export interface ActionChip {
  readonly id: string;
  readonly label: string;
  readonly subLabel?: string;
  readonly icon: string;
}

/** A group of related quick commands under a category. */
export interface CommandCategory {
  readonly id: string;
  readonly label: string;
  readonly icon: string;
  readonly commands: readonly ActionChip[];
}

/** Daily briefing insight from Agent X. */
export interface BriefingInsight {
  readonly id: string;
  readonly text: string;
  readonly icon: string;
  readonly type: 'info' | 'warning' | 'success';
}

/** A goal tag linking a playbook task to a user objective. */
export interface GoalTag {
  readonly id: string;
  readonly label: string;
}

/** A weekly timeline item generated by Agent X. */
export interface WeeklyPlaybookItem {
  readonly id: string;
  readonly weekLabel: string;
  readonly title: string;
  readonly summary: string;
  readonly details: string;
  readonly actionLabel: string;
  readonly status: 'pending' | 'in-progress' | 'complete' | 'problem';
  readonly goal?: GoalTag;
}

@Component({
  selector: 'nxt1-agent-x-shell',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    IonContent,
    NxtPageHeaderComponent,
    NxtRefresherComponent,
    NxtIconComponent,
    AgentXChatComponent,
    AgentXInputComponent,
  ],
  template: `
    <!-- ═══ PAGE HEADER — Agent X Logo Centered ═══ -->
    @if (!hideHeader()) {
      <nxt1-page-header (menuClick)="avatarClick.emit()">
        <!-- Agent X Title in center title slot -->
        <div pageHeaderSlot="title" class="header-logo">
          <span class="header-title-text">Agent</span>
          <svg
            class="header-agent-logo"
            viewBox="0 0 612 792"
            width="40"
            height="40"
            fill="currentColor"
            stroke="currentColor"
            stroke-width="10"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <path
              d="M505.93,251.93c5.52-5.52,1.61-14.96-6.2-14.96h-94.96c-2.32,0-4.55.92-6.2,2.57l-67.22,67.22c-4.2,4.2-11.28,3.09-13.99-2.2l-32.23-62.85c-1.49-2.91-4.49-4.75-7.76-4.76l-83.93-.34c-6.58-.03-10.84,6.94-7.82,12.78l66.24,128.23c1.75,3.39,1.11,7.52-1.59,10.22l-137.13,137.13c-11.58,11.58-3.36,31.38,13.02,31.35l71.89-.13c2.32,0,4.54-.93,6.18-2.57l82.89-82.89c4.19-4.19,11.26-3.1,13.98,2.17l40.68,78.74c1.5,2.91,4.51,4.74,7.78,4.74h82.61c6.55,0,10.79-6.93,7.8-12.76l-73.61-143.55c-1.74-3.38-1.09-7.5,1.6-10.19l137.98-137.98ZM346.75,396.42l69.48,134.68c1.77,3.43-.72,7.51-4.58,7.51h-51.85c-2.61,0-5.01-1.45-6.23-3.76l-48.11-91.22c-2.21-4.19-7.85-5.05-11.21-1.7l-94.71,94.62c-1.32,1.32-3.11,2.06-4.98,2.06h-62.66c-4.1,0-6.15-4.96-3.25-7.85l137.28-137.14c5.12-5.12,6.31-12.98,2.93-19.38l-61.51-116.63c-1.48-2.8.55-6.17,3.72-6.17h56.6c2.64,0,5.05,1.47,6.26,3.81l39.96,77.46c2.19,4.24,7.86,5.12,11.24,1.75l81.05-80.97c1.32-1.32,3.11-2.06,4.98-2.06h63.61c3.75,0,5.63,4.54,2.97,7.19l-129.7,129.58c-2.17,2.17-2.69,5.49-1.28,8.21Z"
            />
            <polygon
              points="390.96 303.68 268.3 411.05 283.72 409.62 205.66 489.34 336.63 377.83 321.21 379.73 390.96 303.68"
            />
          </svg>
        </div>

        <button
          pageHeaderSlot="end"
          type="button"
          class="agent-history-action"
          aria-label="Activity log"
          (click)="onActivityLogClick()"
        >
          <nxt1-icon name="time" [size]="22" className="agent-history-icon" />
        </button>
      </nxt1-page-header>
    }

    <!-- ═══ SCROLLABLE CONTENT ═══ -->
    <ion-content [fullscreen]="true" class="agent-x-content">
      <nxt-refresher (onRefresh)="handleRefresh($event)" (onTimeout)="handleRefreshTimeout()" />

      <div class="agent-x-container">
        <!-- ═══ 1. DAILY BRIEFING ═══ -->
        @if (agentX.isEmpty()) {
          <section class="briefing-section" aria-label="Daily briefing">
            <!-- AI Pulse Indicator -->
            <div class="briefing-status">
              <div class="pulse-ring"></div>
              <div class="pulse-dot"></div>
              <span class="status-label">Active</span>
            </div>

            <!-- Greeting -->
            <h2 class="briefing-greeting">{{ greeting() }}</h2>

            <!-- Briefing Summary (Expandable) -->
            <div class="briefing-content">
              @if (!isBriefingExpanded()) {
                <p class="briefing-preview">
                  I've reviewed your latest data, including {{ briefingInsights().length }} new
                  updates to your profile and Scout Report.
                </p>
                <button type="button" class="btn-expand" (click)="isBriefingExpanded.set(true)">
                  Read full briefing
                </button>
              } @else {
                <ul class="briefing-list">
                  @for (insight of briefingInsights(); track insight.id) {
                    <li class="briefing-item">{{ insight.text }}</li>
                  }
                </ul>
                <button type="button" class="btn-expand" (click)="isBriefingExpanded.set(false)">
                  Show less
                </button>
              }
            </div>

            <!-- ═══ 2. QUICK COMMANDS — Category Pills ═══ -->
            <section class="commands-section" aria-label="Quick commands">
              <h3 class="section-title">Quick Commands</h3>
              <div class="cmd-categories">
                @for (cat of commandCategories(); track cat.id) {
                  <button type="button" class="cmd-category-pill" (click)="onCategoryTap(cat)">
                    <div class="cmd-category-pill-icon">
                      <nxt1-icon [name]="cat.icon" [size]="14" />
                    </div>
                    <span>{{ cat.label }}</span>
                    <nxt1-icon
                      name="chevronForward"
                      [size]="10"
                      className="cmd-category-pill-arrow"
                    />
                  </button>
                }
              </div>
            </section>

            <!-- ═══ 3. DAILY OPERATIONS ═══ -->
            @if (activeOperations().length > 0) {
              <section class="operations-section" aria-label="Daily operations">
                <h3 class="section-title">Daily Operations</h3>
                <div class="operations-scroll">
                  @for (op of activeOperations(); track op.id) {
                    <button
                      type="button"
                      class="operation-card"
                      [class.operation-card--processing]="op.status === 'processing'"
                      [class.operation-card--complete]="op.status === 'complete'"
                      [class.operation-card--error]="op.status === 'error'"
                      (click)="onOperationTap(op)"
                    >
                      <!-- Top row: task icon + label -->
                      <div class="operation-top">
                        <div class="operation-icon">
                          <nxt1-icon [name]="op.icon" [size]="14" />
                        </div>
                        <span class="operation-label">{{ op.label }}</span>
                      </div>

                      <!-- Progress bar -->
                      <div
                        class="operation-progress"
                        [class.operation-progress--complete]="op.status === 'complete'"
                        [class.operation-progress--error]="op.status === 'error'"
                      >
                        <div
                          class="operation-progress-bar"
                          [class.operation-progress-bar--processing]="op.status === 'processing'"
                          [class.operation-progress-bar--complete]="op.status === 'complete'"
                          [class.operation-progress-bar--error]="op.status === 'error'"
                          [style.width.%]="op.status === 'complete' ? 100 : op.progress"
                        ></div>
                      </div>

                      <!-- Bottom row: status badge + spinner/icon -->
                      <div class="operation-status-row">
                        @switch (op.status) {
                          @case ('processing') {
                            <span class="operation-status-badge operation-status-badge--processing">
                              In progress
                            </span>
                            <span class="operation-spinner">
                              <nxt1-icon name="refresh" [size]="12" />
                            </span>
                          }
                          @case ('complete') {
                            <span class="operation-status-badge operation-status-badge--complete">
                              Complete
                            </span>
                            <span class="operation-status-icon operation-status-icon--complete">
                              <nxt1-icon name="checkmarkCircle" [size]="12" />
                            </span>
                          }
                          @case ('error') {
                            <span class="operation-status-badge operation-status-badge--error">
                              Failed
                            </span>
                            <span class="operation-status-icon operation-status-icon--error">
                              <nxt1-icon name="alertCircle" [size]="12" />
                            </span>
                          }
                        }
                      </div>
                    </button>
                  }
                </div>
              </section>
            }

            <!-- ═══ 4. WEEKLY PLAYBOOK ═══ -->
            @if (weeklyPlaybook().length > 0) {
              <section class="playbook-section" aria-label="Weekly playbook">
                <div class="playbook-section-header">
                  <div class="playbook-title-row">
                    <h3 class="section-title">Weekly Playbook</h3>
                    <span class="playbook-counter"
                      >{{ playbookCompletedCount() }}/{{ playbookTotalCount() }}</span
                    >
                  </div>
                  <button
                    type="button"
                    class="playbook-goal-pill"
                    (click)="onGoalTap(primaryGoal() ?? null)"
                    aria-label="Goals"
                  >
                    <nxt1-icon name="flag" [size]="12" />
                    <span class="playbook-goal-pill-text">Goals</span>
                  </button>
                </div>

                <ol class="weekly-timeline">
                  @for (item of weeklyPlaybook(); track item.id; let isLast = $last) {
                    <li class="timeline-item">
                      <div class="timeline-rail" aria-hidden="true">
                        <span
                          class="timeline-marker"
                          [class.timeline-marker--pending]="item.status === 'pending'"
                          [class.timeline-marker--in-progress]="item.status === 'in-progress'"
                          [class.timeline-marker--complete]="item.status === 'complete'"
                          [class.timeline-marker--problem]="item.status === 'problem'"
                        >
                          @if (item.status === 'in-progress') {
                            <nxt1-icon name="play" [size]="10" />
                          } @else if (item.status === 'complete') {
                            <nxt1-icon name="checkmark" [size]="12" />
                          } @else if (item.status === 'problem') {
                            <nxt1-icon name="pause" [size]="10" />
                          } @else {
                            <span class="timeline-marker-dot"></span>
                          }
                        </span>
                        @if (!isLast) {
                          <span class="timeline-line"></span>
                        }
                      </div>

                      <article class="timeline-card">
                        <button
                          type="button"
                          class="timeline-toggle"
                          (click)="onPlaybookAction(item)"
                        >
                          <div class="timeline-toggle-top">
                            <h4 class="timeline-title">{{ item.title }}</h4>
                            @if (item.goal) {
                              <span class="timeline-goal-tag">{{ item.goal.label }}</span>
                            }
                          </div>
                        </button>
                      </article>
                    </li>
                  }
                </ol>
              </section>
            }
          </section>
        }

        <!-- ═══ CHAT MESSAGES ═══ -->
        @if (!agentX.isEmpty()) {
          <nxt1-agent-x-chat [messages]="agentX.messages()" />
        }
      </div>
    </ion-content>

    <!-- ═══ INPUT BAR — Fixed above footer ═══ -->
    <nxt1-agent-x-input
      [hasMessages]="!agentX.isEmpty()"
      [selectedTask]="agentX.selectedTask()"
      [isLoading]="agentX.isLoading()"
      [canSend]="agentX.canSend()"
      [userMessage]="agentX.getUserMessage()"
      (messageChange)="agentX.setUserMessage($event)"
      (send)="onSendMessage()"
      (removeTask)="agentX.clearTask()"
      (toggleTasks)="onToggleTasks()"
    />
  `,
  styles: [
    `
      /* ============================================
         AGENT X COMMAND CENTER — 2026 AI-FIRST
         100% Theme Aware (Light + Dark Mode)
         ============================================ */

      :host {
        display: block;
        height: 100%;
        width: 100%;

        --agent-bg: var(--nxt1-color-bg-primary, var(--ion-background-color, #0a0a0a));
        --agent-surface: var(--nxt1-color-surface-100, rgba(255, 255, 255, 0.04));
        --agent-surface-hover: var(--nxt1-color-surface-200, rgba(255, 255, 255, 0.06));
        --agent-border: var(--nxt1-color-border-subtle, rgba(255, 255, 255, 0.08));
        --agent-text-primary: var(--nxt1-color-text-primary, #ffffff);
        --agent-text-secondary: var(--nxt1-color-text-secondary, rgba(255, 255, 255, 0.7));
        --agent-text-muted: var(--nxt1-color-text-tertiary, rgba(255, 255, 255, 0.5));
        --agent-primary: var(--nxt1-color-primary, #ccff00);
        --agent-primary-glow: var(--nxt1-color-alpha-primary10, rgba(204, 255, 0, 0.1));
        --agent-glass-bg: var(--nxt1-glass-bg, rgba(18, 18, 18, 0.8));
        --agent-glass-border: var(--nxt1-glass-border, rgba(255, 255, 255, 0.1));
      }

      :host-context(.light),
      :host-context([data-theme='light']) {
        --agent-bg: var(--nxt1-color-bg-primary, #ffffff);
        --agent-surface: var(--nxt1-color-surface-100, rgba(0, 0, 0, 0.03));
        --agent-surface-hover: var(--nxt1-color-surface-200, rgba(0, 0, 0, 0.05));
        --agent-border: var(--nxt1-color-border-subtle, rgba(0, 0, 0, 0.08));
        --agent-text-primary: var(--nxt1-color-text-primary, #1a1a1a);
        --agent-text-secondary: var(--nxt1-color-text-secondary, rgba(0, 0, 0, 0.7));
        --agent-text-muted: var(--nxt1-color-text-tertiary, rgba(0, 0, 0, 0.5));
        --agent-glass-bg: var(--nxt1-glass-bg, rgba(255, 255, 255, 0.8));
      }

      /* ── Header Logo ── */
      .header-logo {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 0;
        width: 100%;
        margin-top: -8px;
        margin-left: -18px;
      }

      .header-title-text {
        display: inline-flex;
        align-items: center;
        font-family: var(--nxt1-font-family-brand, var(--ion-font-family));
        font-size: var(--nxt1-font-size-xl, 20px);
        font-weight: var(--nxt1-font-weight-semibold, 600);
        letter-spacing: var(--nxt1-letter-spacing-tight, -0.01em);
        color: var(--agent-text-primary);
        line-height: 1;
        transform: translateY(1px);
      }

      .header-agent-logo {
        display: block;
        flex-shrink: 0;
        color: var(--agent-text-primary);
        transform: translateY(1px);
      }

      .agent-history-action {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 40px;
        height: 40px;
        border: 0;
        border-radius: 9999px;
        padding: 0;
        background: transparent;
        color: var(--agent-text-primary);
      }

      .agent-history-icon {
        display: block;
      }

      /* ── Content Area ── */
      .agent-x-content {
        --background: var(--agent-bg);
      }

      .agent-x-container {
        display: flex;
        flex-direction: column;
        min-height: 100%;
        padding: var(--nxt1-spacing-4, 16px);
        padding-bottom: calc(200px + env(safe-area-inset-bottom, 0px));
      }

      @media (max-width: 767px) {
        .agent-x-container {
          padding-bottom: calc(260px + env(safe-area-inset-bottom, 0px));
        }
      }

      /* ──────────────────────────────────
         1. ACTIVE OPERATIONS
         ────────────────────────────────── */

      /* Spin animation for processing spinner */
      @keyframes op-spin {
        from {
          transform: rotate(0deg);
        }
        to {
          transform: rotate(360deg);
        }
      }

      /* Subtle border glow for active processing cards */
      @keyframes op-pulse-border {
        0%,
        100% {
          border-color: var(--agent-primary-glow);
        }
        50% {
          border-color: var(--agent-primary);
        }
      }

      /* Glow on the progress bar fill */
      @keyframes op-bar-glow {
        0%,
        100% {
          box-shadow: 0 0 4px transparent;
        }
        50% {
          box-shadow: 0 0 6px var(--agent-primary);
        }
      }

      .operations-section {
        width: 100%;
        margin-bottom: var(--nxt1-spacing-5, 20px);
      }

      .operations-scroll {
        display: flex;
        gap: var(--nxt1-spacing-3, 12px);
        overflow-x: auto;
        scrollbar-width: none;
        -webkit-overflow-scrolling: touch;
        padding-bottom: 2px;
      }

      .operations-scroll::-webkit-scrollbar {
        display: none;
      }

      /* ── Card ── */
      .operation-card {
        display: flex;
        flex-direction: column;
        gap: var(--nxt1-spacing-2, 8px);
        flex-shrink: 0;
        width: 200px;
        padding: var(--nxt1-spacing-3, 12px);
        background: var(--agent-surface);
        border: 1px solid var(--agent-border);
        border-radius: var(--nxt1-radius-lg, 14px);
        cursor: pointer;
        font-family: inherit;
        -webkit-tap-highlight-color: transparent;
        transition:
          background 0.2s ease,
          border-color 0.3s ease,
          box-shadow 0.3s ease;
      }

      .operation-card:active {
        background: var(--agent-surface-hover);
      }

      /* Processing — breathing border glow */
      .operation-card--processing {
        border-color: var(--agent-primary-glow);
        animation: op-pulse-border 2.4s ease-in-out infinite;
      }

      /* Complete — subtle green tint */
      .operation-card--complete {
        border-color: var(--nxt1-color-success-border, rgba(76, 175, 80, 0.25));
        background: var(--nxt1-color-success-surface, rgba(76, 175, 80, 0.05));
      }

      /* Error — subtle red tint */
      .operation-card--error {
        border-color: var(--nxt1-color-error-border, rgba(244, 67, 54, 0.25));
        background: var(--nxt1-color-error-surface, rgba(244, 67, 54, 0.05));
      }

      /* ── Top row (icon + label) ── */
      .operation-top {
        display: flex;
        align-items: center;
        gap: var(--nxt1-spacing-2, 8px);
      }

      .operation-icon {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 26px;
        height: 26px;
        border-radius: var(--nxt1-radius-full, 9999px);
        background: var(--agent-primary-glow);
        color: var(--agent-primary);
        flex-shrink: 0;
      }

      .operation-card--complete .operation-icon {
        background: var(--nxt1-color-success-surface, rgba(76, 175, 80, 0.1));
        color: var(--nxt1-color-success, #4caf50);
      }

      .operation-card--error .operation-icon {
        background: var(--nxt1-color-error-surface, rgba(244, 67, 54, 0.1));
        color: var(--nxt1-color-error, #f44336);
      }

      .operation-label {
        font-size: var(--nxt1-font-size-sm, 13px);
        font-weight: var(--nxt1-font-weight-medium, 500);
        color: var(--agent-text-primary);
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        line-height: 1.3;
      }

      /* ── Progress bar ── */
      .operation-progress {
        width: 100%;
        height: 3px;
        background: var(--agent-border);
        border-radius: var(--nxt1-radius-full, 9999px);
        overflow: hidden;
      }

      .operation-progress-bar {
        height: 100%;
        background: var(--agent-primary);
        border-radius: var(--nxt1-radius-full, 9999px);
        transition: width 0.4s ease;
      }

      .operation-progress-bar--processing {
        animation: op-bar-glow 2s ease-in-out infinite;
      }

      .operation-progress-bar--complete {
        background: var(--nxt1-color-success, #4caf50);
      }

      .operation-progress-bar--error {
        background: var(--nxt1-color-error, #f44336);
      }

      /* ── Status row (badge + icon/spinner) ── */
      .operation-status-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
      }

      .operation-status-badge {
        font-size: 10px;
        font-weight: var(--nxt1-font-weight-semibold, 600);
        letter-spacing: 0.04em;
        text-transform: uppercase;
        line-height: 1;
      }

      .operation-status-badge--processing {
        color: var(--agent-primary);
      }

      .operation-status-badge--complete {
        color: var(--nxt1-color-success, #4caf50);
      }

      .operation-status-badge--error {
        color: var(--nxt1-color-error, #f44336);
      }

      /* Spinning refresh icon */
      .operation-spinner {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        color: var(--agent-primary);
        animation: op-spin 1.2s linear infinite;
      }

      /* Static status icons */
      .operation-status-icon {
        display: inline-flex;
        align-items: center;
        justify-content: center;
      }

      .operation-status-icon--complete {
        color: var(--nxt1-color-success, #4caf50);
      }

      .operation-status-icon--error {
        color: var(--nxt1-color-error, #f44336);
      }

      /* ──────────────────────────────────
         2. DAILY BRIEFING
         ────────────────────────────────── */
      .briefing-section {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        text-align: left;
        padding: var(--nxt1-spacing-6, 24px) 0 var(--nxt1-spacing-4, 16px);
      }

      /* AI Active Pulse */
      .briefing-status {
        display: flex;
        align-items: center;
        gap: var(--nxt1-spacing-2, 8px);
        margin-bottom: var(--nxt1-spacing-5, 20px);
        position: relative;
      }

      .pulse-dot {
        width: 8px;
        height: 8px;
        border-radius: 50%;
        background: var(--agent-primary);
      }

      .pulse-ring {
        position: absolute;
        left: 0;
        top: 50%;
        transform: translateY(-50%);
        width: 8px;
        height: 8px;
        border-radius: 50%;
        border: 1.5px solid var(--agent-primary);
        animation: pulse-expand 2s ease-out infinite;
      }

      @keyframes pulse-expand {
        0% {
          transform: translateY(-50%) scale(1);
          opacity: 0.8;
        }
        100% {
          transform: translateY(-50%) scale(3);
          opacity: 0;
        }
      }

      .status-label {
        font-size: 12px;
        font-weight: 600;
        letter-spacing: 0.03em;
        color: var(--agent-primary);
      }

      /* Greeting */
      .briefing-greeting {
        font-size: 22px;
        font-weight: 700;
        color: var(--agent-text-primary);
        margin: 0 0 var(--nxt1-spacing-5, 20px);
        line-height: 1.3;
      }

      /* Expandable Briefing */
      .briefing-content {
        width: 100%;
        margin-bottom: var(--nxt1-spacing-6, 24px);
      }

      .briefing-preview {
        font-size: 14px;
        line-height: 1.5;
        color: var(--agent-text-secondary);
        margin: 0 0 var(--nxt1-spacing-3, 12px);
        /* Simple truncation to 2 lines */
        display: -webkit-box;
        -webkit-line-clamp: 2;
        line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
      }

      .btn-expand {
        background: transparent;
        border: none;
        padding: 0;
        font-size: 13px;
        font-weight: 600;
        color: var(--agent-primary);
        cursor: pointer;
        display: inline-flex;
        align-items: center;
        gap: 4px;
      }

      /* Briefing List */
      .briefing-list {
        list-style: none;
        padding: 0;
        margin: 0 0 var(--nxt1-spacing-4, 16px);
        width: 100%;
        text-align: left;
      }

      .briefing-item {
        position: relative;
        padding-left: var(--nxt1-spacing-4, 16px);
        font-size: 14px;
        line-height: 1.6;
        color: var(--agent-text-secondary);
        margin-bottom: var(--nxt1-spacing-3, 12px);
      }

      .briefing-item:last-child {
        margin-bottom: 0;
      }

      .briefing-item::before {
        content: '';
        position: absolute;
        left: 0;
        top: 9px;
        width: 5px;
        height: 5px;
        border-radius: 50%;
        background: var(--agent-text-muted);
      }

      /* ──────────────────────────────────
         SHARED SECTION TITLE
         ────────────────────────────────── */
      .section-title {
        font-size: 13px;
        font-weight: 600;
        letter-spacing: 0.02em;
        color: var(--agent-text-muted);
        margin: 0 0 var(--nxt1-spacing-3, 12px);
      }

      /* ──────────────────────────────────
         3. WEEKLY PLAYBOOK (Timeline)
         ────────────────────────────────── */
      .playbook-section {
        width: 100%;
        margin-bottom: var(--nxt1-spacing-6, 24px);
      }

      .playbook-section-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: var(--nxt1-spacing-2, 8px);
        margin-bottom: var(--nxt1-spacing-3, 12px);
      }

      .playbook-title-row {
        display: flex;
        align-items: center;
        gap: var(--nxt1-spacing-2, 8px);
        min-width: 0;
        flex: 1;
      }

      .playbook-section-header .section-title {
        margin: 0;
        flex-shrink: 0;
      }

      .playbook-counter {
        font-size: 12px;
        font-weight: 600;
        color: var(--agent-text-muted);
        white-space: nowrap;
        flex-shrink: 0;
      }

      /* Goal pill — tappable badge next to the title */
      .playbook-goal-pill {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        gap: 6px;
        padding: 8px 16px;
        border: 1px solid var(--agent-primary-glow);
        border-radius: var(--nxt1-radius-full, 9999px);
        background: var(--agent-primary-glow);
        color: var(--agent-primary);
        font-size: 13px;
        font-weight: var(--nxt1-font-weight-semibold, 600);
        letter-spacing: 0.01em;
        line-height: 1;
        white-space: nowrap;
        cursor: pointer;
        font-family: inherit;
        flex-shrink: 0;
        -webkit-tap-highlight-color: transparent;
        transition:
          background 0.15s ease,
          border-color 0.15s ease;
      }

      .playbook-goal-pill:active {
        background: var(--agent-primary);
        color: var(--agent-bg);
        border-color: var(--agent-primary);
      }

      .playbook-goal-pill-text {
        display: inline-block;
        white-space: nowrap;
      }

      .playbook-section-toggle {
        border: 1px solid var(--agent-border);
        background: var(--agent-surface);
        color: var(--agent-text-secondary);
        border-radius: var(--nxt1-radius-full, 9999px);
        padding: 4px 10px;
        font-size: 12px;
        font-weight: 600;
      }

      .weekly-timeline {
        list-style: none;
        margin: 0;
        padding: 0;
        display: flex;
        flex-direction: column;
        gap: var(--nxt1-spacing-3, 12px);
      }

      .timeline-item {
        display: flex;
        align-items: stretch;
        gap: var(--nxt1-spacing-2, 8px);
      }

      .timeline-rail {
        width: 18px;
        display: flex;
        flex-direction: column;
        align-items: center;
      }

      .timeline-marker {
        width: 18px;
        height: 18px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        border-radius: 50%;
        margin-top: 9px;
        background: var(--agent-surface);
        border: 1px solid var(--agent-border);
      }

      .timeline-marker-dot {
        width: 8px;
        height: 8px;
        border-radius: 50%;
        background: var(--agent-primary);
      }

      .timeline-marker--pending {
        border-color: color-mix(in srgb, var(--agent-primary) 40%, var(--agent-border));
      }

      .timeline-marker--in-progress {
        border-color: var(--agent-primary);
        background: var(--agent-primary-glow);
        color: var(--agent-primary);
      }

      .timeline-marker--complete {
        border-color: var(--nxt1-color-success, #4caf50);
        background: color-mix(in srgb, var(--nxt1-color-success, #4caf50) 16%, transparent);
        color: var(--nxt1-color-success, #4caf50);
      }

      .timeline-marker--problem {
        border-color: var(--nxt1-color-warning, #ffb020);
        background: color-mix(in srgb, var(--nxt1-color-warning, #ffb020) 16%, transparent);
        color: var(--nxt1-color-warning, #ffb020);
      }

      .timeline-line {
        flex: 1;
        width: 1px;
        margin-top: 6px;
        background: var(--agent-border);
      }

      .timeline-card {
        flex: 1;
        background: var(--agent-surface);
        border: 1px solid var(--agent-border);
        border-radius: var(--nxt1-radius-lg, 12px);
        transition:
          border-color 0.2s ease,
          background 0.2s ease;
        overflow: hidden;
      }

      .timeline-item--expanded .timeline-card,
      .timeline-card:active {
        background: var(--agent-surface-hover);
        border-color: var(--agent-primary);
      }

      .timeline-toggle {
        display: block;
        width: 100%;
        padding: var(--nxt1-spacing-3, 12px) var(--nxt1-spacing-4, 16px);
        border: 0;
        background: transparent;
        color: inherit;
        text-align: left;
        cursor: pointer;
      }

      .timeline-toggle-top {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: var(--nxt1-spacing-2, 8px);
        margin-bottom: 0;
      }

      .timeline-goal-tag {
        display: inline-flex;
        align-items: center;
        padding: 2px 8px;
        background: var(--agent-primary-glow);
        border-radius: var(--nxt1-radius-full, 9999px);
        color: var(--agent-primary);
        font-size: 11px;
        font-weight: 600;
        white-space: nowrap;
        flex-shrink: 0;
      }

      .timeline-title {
        font-size: 15px;
        font-weight: 600;
        color: var(--agent-text-primary);
        margin: 0;
        line-height: 1.3;
        min-width: 0;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
      }

      .timeline-summary {
        font-size: 13px;
        line-height: 1.4;
        color: var(--agent-text-secondary);
        margin: 0;
      }

      .timeline-details {
        border-top: 1px solid var(--agent-border);
        padding: var(--nxt1-spacing-3, 12px) var(--nxt1-spacing-4, 16px);
      }

      .timeline-details-text {
        margin: 0 0 var(--nxt1-spacing-3, 12px);
        font-size: 13px;
        line-height: 1.45;
        color: var(--agent-text-secondary);
      }

      .timeline-actions {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: var(--nxt1-spacing-2, 8px);
      }

      .timeline-status {
        font-size: 11px;
        font-weight: 600;
        letter-spacing: 0.03em;
        text-transform: uppercase;
      }

      .timeline-status--pending {
        color: var(--agent-text-muted);
      }

      .timeline-status--in-progress {
        color: var(--agent-primary);
      }

      .timeline-status--complete {
        color: #4caf50;
      }

      .playbook-action-btn {
        display: inline-flex;
        align-items: center;
        gap: 6px;
        padding: 6px 14px;
        background: var(--agent-primary);
        color: #000;
        border: none;
        border-radius: var(--nxt1-radius-full, 9999px);
        font-size: 13px;
        font-weight: 600;
        cursor: pointer;
        transition: opacity 0.15s ease;
        -webkit-tap-highlight-color: transparent;
      }

      .playbook-action-btn:active {
        opacity: 0.85;
      }

      /* ──────────────────────────────────
         4. QUICK COMMANDS — Category Pills
         ────────────────────────────────── */
      .commands-section {
        display: flex;
        flex-direction: column;
        gap: var(--nxt1-spacing-3, 12px);
        margin-bottom: var(--nxt1-spacing-5, 20px);
      }

      .commands-section .section-title {
        margin-bottom: 0;
      }

      .cmd-categories {
        display: flex;
        flex-wrap: nowrap;
        gap: var(--nxt1-spacing-2, 8px);
        overflow-x: auto;
        scrollbar-width: none;
        -webkit-overflow-scrolling: touch;
        padding-bottom: 2px;
      }

      .cmd-categories::-webkit-scrollbar {
        display: none;
      }

      .cmd-category-pill {
        display: inline-flex;
        align-items: center;
        flex-shrink: 0;
        gap: var(--nxt1-spacing-2, 8px);
        padding: var(--nxt1-spacing-2, 8px) var(--nxt1-spacing-3, 12px);
        border: 1px solid var(--agent-border);
        border-radius: var(--nxt1-radius-full, 9999px);
        background: var(--agent-surface);
        color: var(--agent-text-primary);
        font-size: var(--nxt1-font-size-sm, 13px);
        font-weight: var(--nxt1-font-weight-semibold, 600);
        font-family: inherit;
        cursor: pointer;
        white-space: nowrap;
        -webkit-tap-highlight-color: transparent;
        transition:
          background 0.15s ease,
          border-color 0.15s ease;
      }

      .cmd-category-pill:active {
        background: var(--agent-surface-hover);
        border-color: var(--agent-primary);
      }

      .cmd-category-pill-icon {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 24px;
        height: 24px;
        border-radius: var(--nxt1-radius-full, 9999px);
        background: var(--agent-primary-glow);
        color: var(--agent-primary);
        flex-shrink: 0;
      }

      .cmd-category-pill-arrow {
        color: var(--agent-text-muted);
        opacity: 0.5;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AgentXShellComponent {
  protected readonly agentX = inject(AgentXService);
  private readonly haptics = inject(HapticsService);
  private readonly toast = inject(NxtToastService);
  private readonly bottomSheet = inject(NxtBottomSheetService);

  // ============================================
  // INPUTS
  // ============================================

  /** Current user info. */
  readonly user = input<AgentXUser | null>(null);

  /** Hide page header (desktop sidebar provides navigation). */
  readonly hideHeader = input(false);

  // ============================================
  // LOCAL STATE
  // ============================================

  /** Whether the full briefing list is expanded. */
  protected readonly isBriefingExpanded = signal(false);

  // ============================================
  // OUTPUTS
  // ============================================

  /** Emitted when avatar/hamburger is clicked (open sidenav). */
  readonly avatarClick = output<void>();

  /** Emitted when an action chip is tapped. */
  readonly chipTap = output<ActionChip>();

  // ============================================
  // COMPUTED
  // ============================================

  /** Display name for header avatar fallback. */
  protected displayName(): string {
    return this.user()?.displayName ?? 'User';
  }

  /** Time-aware greeting for the Daily Briefing. */
  protected readonly greeting = computed(() => {
    const name = this.user()?.displayName?.split(' ')[0] ?? '';
    const hour = new Date().getHours();
    const timeGreeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening';
    return name ? `${timeGreeting}, ${name}.` : `${timeGreeting}.`;
  });

  // ============================================
  // MOCK DATA — Active Operations
  // ============================================

  /** Active background operations (mock). */
  protected readonly activeOperations = signal<ActiveOperation[]>([
    {
      id: 'op-1',
      label: 'Analyzing game film...',
      progress: 45,
      icon: 'play',
      status: 'processing',
    },
    {
      id: 'op-2',
      label: 'Recruiter emails sent',
      progress: 100,
      icon: 'mail',
      status: 'complete',
    },
    {
      id: 'op-3',
      label: 'Highlight reel export',
      progress: 62,
      icon: 'videocam',
      status: 'error',
    },
  ]);

  // ============================================
  // MOCK DATA — Daily Briefing Insights
  // ============================================

  /** Proactive insights from Agent X (mock). */
  protected readonly briefingInsights = signal<BriefingInsight[]>([
    {
      id: 'bi-1',
      text: 'Your Scout Report was updated with new metrics from your last synced game film.',
      icon: 'clipboard',
      type: 'success',
    },
    {
      id: 'bi-2',
      text: '3 college programs viewed your profile this week. Two are D-I schools.',
      icon: 'eye',
      type: 'info',
    },
    {
      id: 'bi-3',
      text: 'Your GPA data is 30 days old. Sync your academic portal to stay current.',
      icon: 'alertCircle',
      type: 'warning',
    },
  ]);

  // ============================================
  // PRIMARY GOAL (Drives Weekly Playbook)
  // ============================================

  /** The user's active primary goal powering the Weekly Playbook (mock). */
  protected readonly primaryGoal = signal<{ id: string; label: string } | null>({
    id: 'goal-1',
    label: 'D1 Recruitment',
  });

  // ============================================
  // WEEKLY PLAYBOOK (Timeline)
  // ============================================

  /** AI-generated weekly playbook timeline items. */
  protected readonly weeklyPlaybook = signal<WeeklyPlaybookItem[]>([
    {
      id: 'wp-1',
      weekLabel: 'Mon',
      title: 'Finalize Recruiting Storyline',
      summary: 'Align your profile, headline metrics, and highlight context for recruiters.',
      details:
        'Agent X prepared a recruiting narrative from your latest film, stats, and profile views. Confirm it so all outbound content stays consistent this week.',
      actionLabel: 'Review Draft',
      status: 'in-progress',
      goal: { id: 'goal-1', label: 'D1 Recruitment' },
    },
    {
      id: 'wp-2',
      weekLabel: 'Tue',
      title: 'Ship Recruiter Outreach Batch',
      summary: 'Send personalized messages to your top priority programs.',
      details:
        'Your draft set is ready with coach-specific personalization. Approve and send to trigger tracking for opens and replies in Activity.',
      actionLabel: 'Send Batch',
      status: 'pending',
      goal: { id: 'goal-1', label: 'D1 Recruitment' },
    },
    {
      id: 'wp-3',
      weekLabel: 'Wed',
      title: 'Publish Midweek Performance Post',
      summary: 'Share your latest clip + stat proof point to keep momentum.',
      details:
        'Agent X generated copy and media options optimized for engagement windows. Choose one and publish directly from Create Post.',
      actionLabel: 'Publish Post',
      status: 'pending',
      goal: { id: 'goal-2', label: 'Grow Brand' },
    },
    {
      id: 'wp-4',
      weekLabel: 'Thu',
      title: 'Refresh Compliance & Academics',
      summary: 'Keep GPA and transcript context current for eligibility confidence.',
      details:
        'Sync your academic portal and verify profile fields used in eligibility summaries. This reduces recruiter friction during evaluation.',
      actionLabel: 'Sync Academics',
      status: 'pending',
    },
    {
      id: 'wp-5',
      weekLabel: 'Fri',
      title: 'Weekly Review and Next-Week Setup',
      summary: "Close this week and auto-generate next week's top priorities.",
      details:
        'Agent X will summarize completed tasks, update progress signals, and propose next-week objectives tailored to engagement and recruiter activity.',
      actionLabel: 'Run Weekly Review',
      status: 'pending',
    },
  ]);

  /** Number of completed playbook tasks. */
  protected readonly playbookCompletedCount = computed(
    () => this.weeklyPlaybook().filter((t) => t.status === 'complete').length
  );

  /** Total number of playbook tasks. */
  protected readonly playbookTotalCount = computed(() => this.weeklyPlaybook().length);

  // ============================================
  // QUICK COMMANDS — Categorized Grid
  // ============================================

  /** Categorized quick commands grouped by workflow domain (Personalized). */
  protected readonly commandCategories = signal<CommandCategory[]>([
    {
      id: 'cat-recruiting',
      label: 'Recruiting',
      icon: 'graduationCap',
      commands: [
        {
          id: 'cmd-colleges',
          label: 'Find Programs',
          subLabel: 'Matched to your 3.8 GPA & film',
          icon: 'search',
        },
        {
          id: 'cmd-email',
          label: 'Draft Coach Email',
          subLabel: '3 new templates ready',
          icon: 'mail',
        },
        {
          id: 'cmd-timeline',
          label: 'My Timeline',
          subLabel: 'Next: NCAA Dead Period',
          icon: 'calendar',
        },
        {
          id: 'cmd-eligibility',
          label: 'Eligibility Check',
          subLabel: 'Verify NCAA/NAIA status',
          icon: 'shieldCheck',
        },
      ],
    },
    {
      id: 'cat-content',
      label: 'Brand',
      icon: 'sparkles',
      commands: [
        {
          id: 'cmd-post',
          label: 'Create Post',
          subLabel: 'Trending: #GameDay',
          icon: 'plus',
        },
        {
          id: 'cmd-highlight',
          label: 'Highlight Reel',
          subLabel: '12 new clips from Friday',
          icon: 'videocam',
        },
        {
          id: 'cmd-brand',
          label: 'Brand Strategy',
          subLabel: 'AI-powered growth plan',
          icon: 'rocket',
        },
      ],
    },
    {
      id: 'cat-film',
      label: 'Film Room',
      icon: 'barChart',
      commands: [
        {
          id: 'cmd-scout',
          label: 'Scout Report',
          subLabel: 'Updated 2h ago',
          icon: 'clipboard',
        },
        {
          id: 'cmd-analyze',
          label: 'Analyze Film',
          subLabel: 'Upload Hudl link',
          icon: 'play',
        },
        {
          id: 'cmd-trends',
          label: 'Stat Trends',
          subLabel: 'Week-over-week growth',
          icon: 'trendingUp',
        },
      ],
    },
  ]);

  // ============================================
  // HEADER CONFIG
  // ============================================

  constructor() {
    afterNextRender(() => {
      this.agentX.startTitleAnimation();
    });
  }

  // ============================================
  // EVENT HANDLERS
  // ============================================

  protected async onActivityLogClick(): Promise<void> {
    await this.haptics.impact('light');
    await this.bottomSheet.openSheet({
      component: AgentXOperationsLogComponent,
      breakpoints: [0, 0.5, 0.92],
      initialBreakpoint: 0.92,
      showHandle: true,
      handleBehavior: 'cycle',
      backdropDismiss: true,
      cssClass: 'agent-x-operations-log-sheet',
    });
  }

  /**
   * Handle goal pill tap — opens bottom sheet to update primary goal via conversation.
   */
  protected async onGoalTap(goal: { id: string; label: string } | null): Promise<void> {
    await this.haptics.impact('light');
    await this.openOperationChat(goal?.id ?? 'goal-edit', 'Edit Goals', 'flag', 'command');
  }

  /**
   * Handle weekly playbook action tap — opens dedicated bottom sheet chat.
   */
  protected async onPlaybookAction(task: WeeklyPlaybookItem): Promise<void> {
    await this.haptics.impact('medium');
    await this.openOperationChat(task.id, task.title, 'clipboard', 'command');
  }

  /**
   * Handle category pill tap — opens bottom sheet with sub-commands as suggestion chips.
   */
  protected async onCategoryTap(cat: CommandCategory): Promise<void> {
    await this.haptics.impact('light');
    const quickActions: OperationQuickAction[] = cat.commands.map((cmd) => ({
      id: cmd.id,
      label: cmd.label,
      icon: cmd.icon,
    }));
    await this.openOperationChat(cat.id, cat.label, cat.icon, 'command', quickActions);
  }

  /**
   * Handle action chip tap — opens dedicated bottom sheet chat.
   */
  protected async onChipTap(chip: ActionChip): Promise<void> {
    await this.haptics.impact('light');
    this.chipTap.emit(chip);
    await this.openOperationChat(chip.id, chip.label, chip.icon, 'command');
  }

  /**
   * Handle active operation card tap — opens dedicated bottom sheet chat.
   */
  protected async onOperationTap(op: ActiveOperation): Promise<void> {
    await this.haptics.impact('light');
    await this.openOperationChat(op.id, op.label, op.icon, 'operation');
  }

  /**
   * Open the dedicated bottom sheet chat for an operation or command.
   */
  private async openOperationChat(
    contextId: string,
    contextTitle: string,
    contextIcon: string,
    contextType: 'operation' | 'command',
    quickActions: OperationQuickAction[] = []
  ): Promise<void> {
    await this.bottomSheet.openSheet({
      component: AgentXOperationChatComponent,
      componentProps: { contextId, contextTitle, contextIcon, contextType, quickActions },
      breakpoints: [0, 0.5, 0.92],
      initialBreakpoint: 0.92,
      showHandle: true,
      handleBehavior: 'cycle',
      backdropDismiss: true,
      cssClass: 'agent-x-operation-sheet',
    });
  }

  /**
   * Handle send message.
   */
  protected async onSendMessage(): Promise<void> {
    await this.agentX.sendMessage();
  }

  /**
   * Handle toggle tasks panel.
   */
  protected async onToggleTasks(): Promise<void> {
    await this.haptics.impact('light');
    this.toast.info('Task panel coming soon');
  }

  /**
   * Handle pull-to-refresh.
   */
  protected async handleRefresh(event: RefreshEvent): Promise<void> {
    await this.agentX.clearMessages();
    event.complete();
  }

  /**
   * Handle refresh timeout.
   */
  protected async handleRefreshTimeout(): Promise<void> {
    await this.haptics.notification('warning');
    this.toast.warning('Refresh timed out');
  }
}
