/**
 * @fileoverview Auth Routes — Analytics & Unicode
 * @module @nxt1/backend/routes/auth
 *
 * Handles:
 * - POST /analytics/hear-about
 * - POST /generate-unicode
 * - GET /unicode
 */

import { Router } from 'express';
import type { Request, Response, Router as RouterType } from 'express';
import { asyncHandler, sendError } from '@nxt1/core/errors/express';
import { validationError, unauthorizedError, internalError } from '@nxt1/core/errors';
import { generateUnicodeForUser, getUserUnicode } from '../../utils/unicode-generator.js';
import { logger } from '../../utils/logger.js';

const router: RouterType = Router();

/**
 * POST /auth/analytics/hear-about
 * Save referral source ("How did you hear about us").
 */
router.post(
  '/analytics/hear-about',
  asyncHandler(async (req: Request, res: Response): Promise<void> => {
    const { db } = req.firebase!;
    const { userId, source, details, clubName, otherSpecify } = req.body as {
      userId: string;
      source: string;
      details?: string;
      clubName?: string;
      otherSpecify?: string;
    };

    if (!userId?.trim() || !source?.trim()) {
      const error = validationError([
        ...(!userId?.trim()
          ? [{ field: 'userId', message: 'User ID is required', rule: 'required' }]
          : []),
        ...(!source?.trim()
          ? [{ field: 'source', message: 'Source is required', rule: 'required' }]
          : []),
      ]);
      sendError(res, error);
      return;
    }

    const nowISO = new Date().toISOString();

    const updatePayload: Record<string, unknown> = {
      referralSource: source.trim(),
      showedHearAbout: true,
      updatedAt: nowISO,
    };
    const trimmedDetails = details?.trim();
    const trimmedClubName = clubName?.trim();
    const trimmedOtherSpecify = otherSpecify?.trim();
    if (trimmedDetails) updatePayload['referralDetails'] = trimmedDetails;
    if (trimmedClubName) updatePayload['referralClubName'] = trimmedClubName;
    if (trimmedOtherSpecify) updatePayload['referralOtherSpecify'] = trimmedOtherSpecify;

    await db.collection('Users').doc(userId.trim()).update(updatePayload);

    res.json({ success: true });
  })
);

/**
 * POST /auth/generate-unicode
 * Manually generate unicode for the authenticated user.
 * Normally auto-generated by Cloud Function onUserCreated — this is a fallback/retry endpoint.
 */
router.post(
  '/generate-unicode',
  asyncHandler(async (req: Request, res: Response) => {
    const user = req.user;

    if (!user?.uid) {
      return sendError(res, unauthorizedError('missing'));
    }

    const userId = user.uid;
    const db = req.firebase!.db;

    logger.info('[Unicode] Manual generation requested', { userId });

    // Return existing unicode if already assigned
    const existingUnicode = await getUserUnicode(db, userId);
    if (existingUnicode) {
      logger.info('[Unicode] User already has unicode', { userId, unicode: existingUnicode });
      return res.status(200).json({
        success: true,
        unicode: existingUnicode,
        message: 'Unicode already exists',
      });
    }

    try {
      const unicode = await generateUnicodeForUser(db, userId);

      logger.info('[Unicode] Manual generation successful', { userId, unicode });

      return res.status(200).json({
        success: true,
        unicode,
        message: 'Unicode generated successfully',
      });
    } catch (error) {
      logger.error('[Unicode] Manual generation failed', {
        userId,
        error: error instanceof Error ? error.message : String(error),
      });

      return sendError(res, internalError(error));
    }
  })
);

/**
 * GET /auth/unicode
 * Get current user's unicode.
 */
router.get(
  '/unicode',
  asyncHandler(async (req: Request, res: Response) => {
    const user = req.user;

    if (!user?.uid) {
      return sendError(res, unauthorizedError('missing'));
    }

    const userId = user.uid;
    const db = req.firebase!.db;

    const unicode = await getUserUnicode(db, userId);

    if (!unicode) {
      logger.warn('[Unicode] User has no unicode', { userId });
      return res.status(404).json({
        success: false,
        message: 'Unicode not found. Please generate one.',
      });
    }

    return res.status(200).json({
      success: true,
      unicode,
    });
  })
);

export default router;
