/**
 * @fileoverview XP Economy Rewards Preview Section (Interactive)
 * @module @nxt1/ui/xp
 * @version 3.0.0
 *
 * Interactive section presenting "The XP Economy" reward store.
 * 4 reward cards in a single horizontal row (desktop) → 2-col (tablet) → 1-col (mobile).
 * Each card has a square placeholder image, hover/focus lift, click-to-expand detail,
 * and a premium shimmer animation on the image area.
 *
 * Width uses the same `--nxt1-section-max-width` / `--nxt1-section-padding-x`
 * tokens as sibling landing-page sections so everything aligns seamlessly.
 *
 * 100% design-token styling · SSR-safe semantic markup · Accessibility-first.
 */

import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';

interface RewardTier {
  readonly id: string;
  readonly xp: number;
  readonly xpLabel: string;
  readonly title: string;
  readonly subtitle: string;
  readonly description: string;
  /** SVG path data for the reward-type icon (24×24 viewBox). */
  readonly iconPath: string;
}

const REWARD_TIERS: readonly RewardTier[] = [
  {
    id: 'banner',
    xp: 500,
    xpLabel: '500 XP',
    title: 'Custom Profile Banner',
    subtitle: 'Stand Out Instantly',
    description:
      'Unlock a premium banner for your recruiting profile. Coaches see it first — make the impression count.',
    iconPath:
      'M4 5a2 2 0 012-2h12a2 2 0 012 2v10a2 2 0 01-2 2H6a2 2 0 01-2-2V5zm14 0H6v10h12V5zm-5 12v2H5a1 1 0 01-1-1v-1h9zm6 0v1a1 1 0 01-1 1h-3v-2h4z',
  },
  {
    id: 'agent-x',
    xp: 2000,
    xpLabel: '2,000 XP',
    title: 'Agent X Graphic',
    subtitle: 'AI-Powered Content',
    description:
      'Get a custom social-media graphic generated by Agent X — your personal hype machine. Ready to post in seconds.',
    iconPath: 'M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5',
  },
  {
    id: 'featured-athlete',
    xp: 10000,
    xpLabel: '10,000 XP',
    title: 'Featured Athlete Spotlight',
    subtitle: '1 Week Premium Visibility',
    description:
      'Your profile gets pinned in the Featured section for 7 days. Maximum exposure to college coaches actively scouting.',
    iconPath:
      'M12 2l3.09 6.26L22 9.27l-5 4.87L18.18 21 12 17.27 5.82 21 7 14.14 2 9.27l6.91-1.01L12 2z',
  },
  {
    id: 'scout-report',
    xp: 25000,
    xpLabel: '25,000 XP',
    title: 'Scout Report + Newsletter',
    subtitle: 'The Ultimate Exposure Play',
    description:
      'A full AI-supported scouting report published to your profile plus a feature in our weekly coach newsletter reaching 5,000+ programs.',
    iconPath:
      'M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z',
  },
] as const;

let xpEconomyInstanceCounter = 0;

@Component({
  selector: 'nxt1-xp-economy-rewards',
  standalone: true,
  template: `
    <section class="xp-economy" [attr.aria-labelledby]="titleId()">
      <header class="xp-economy__header">
        <p class="xp-economy__eyebrow">The XP Economy (Rewards)</p>
        <h2 [id]="titleId()" class="xp-economy__title">Grind Now. Cash In Later.</h2>
        <p class="xp-economy__subtitle">
          Real rewards for real effort. Not fake currency — actual recruiting advantages.
        </p>
      </header>

      <div class="xp-store" [attr.aria-labelledby]="storeTitleId()">
        <div class="xp-store__top-row">
          <h3 [id]="storeTitleId()" class="xp-store__title">Reward Store Preview</h3>
          <span class="xp-store__pill" aria-label="Rewards are live">
            <span class="xp-store__pill-dot" aria-hidden="true"></span>
            Live Rewards
          </span>
        </div>

        <!-- Reward Cards — 4-across row -->
        <div class="xp-store__grid" role="list" aria-label="Available rewards">
          @for (tier of rewardTiers; track tier.id) {
            <article
              class="reward-card"
              [class.reward-card--selected]="isSelected(tier.id)"
              role="listitem"
              [attr.aria-expanded]="isSelected(tier.id)"
              tabindex="0"
              (click)="selectReward(tier.id)"
              (keydown.enter)="selectReward(tier.id)"
              (keydown.space)="selectReward(tier.id); $event.preventDefault()"
            >
              <!-- Square Placeholder Image -->
              <div class="reward-card__image" aria-hidden="true">
                <div class="reward-card__shimmer"></div>
                <div class="reward-card__icon-wrap">
                  <svg
                    class="reward-card__icon"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="1.5"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    aria-hidden="true"
                  >
                    <path [attr.d]="tier.iconPath" />
                  </svg>
                </div>
                <span class="reward-card__image-label">Preview</span>
              </div>

              <!-- Card Body -->
              <div class="reward-card__body">
                <span class="reward-card__xp-badge">{{ tier.xpLabel }}</span>
                <h4 class="reward-card__name">{{ tier.title }}</h4>
                <p class="reward-card__subtitle">{{ tier.subtitle }}</p>
              </div>

              <!-- Expand chevron -->
              <div class="reward-card__expand-row">
                <span class="reward-card__expand-hint">{{
                  isSelected(tier.id) ? 'Hide details' : 'View details'
                }}</span>
                <svg
                  class="reward-card__chevron"
                  [class.reward-card__chevron--open]="isSelected(tier.id)"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </div>

              <!-- Inline Detail Panel -->
              @if (isSelected(tier.id)) {
                <div
                  class="reward-card__detail"
                  role="region"
                  [attr.aria-label]="tier.title + ' details'"
                >
                  <p class="reward-card__description">{{ tier.description }}</p>
                  <div class="reward-card__meta">
                    <span class="reward-card__cost">{{ tier.xpLabel }} to redeem</span>
                    <span class="reward-card__tag">Recruiting Advantage</span>
                  </div>
                </div>
              }
            </article>
          }
        </div>
      </div>

      <p class="xp-economy__cta">Tap any reward to see what you're grinding toward.</p>
    </section>
  `,
  styles: [
    `
      :host {
        display: block;
      }

      /* ============================================
         SECTION — matches sibling section widths
         ============================================ */

      .xp-economy {
        display: grid;
        gap: var(--nxt1-spacing-5);
        max-width: var(--nxt1-section-max-width);
        margin: 0 auto;
        padding: var(--nxt1-section-padding-y, var(--nxt1-spacing-8))
          var(--nxt1-section-padding-x, var(--nxt1-spacing-4));
      }

      .xp-economy__header {
        display: grid;
        gap: var(--nxt1-spacing-2);
        text-align: center;
      }

      .xp-economy__eyebrow {
        margin: 0;
        color: var(--nxt1-color-primary);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-xs);
        font-weight: var(--nxt1-fontWeight-semibold);
        letter-spacing: var(--nxt1-letterSpacing-wide);
        text-transform: uppercase;
      }

      .xp-economy__title {
        margin: 0;
        color: var(--nxt1-color-text-primary);
        font-family: var(--nxt1-fontFamily-display);
        font-size: var(--nxt1-fontSize-2xl);
        font-weight: var(--nxt1-fontWeight-bold);
        line-height: var(--nxt1-lineHeight-tight);
      }

      .xp-economy__subtitle {
        margin: 0;
        color: var(--nxt1-color-text-secondary);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-sm);
        font-weight: var(--nxt1-fontWeight-medium);
        line-height: var(--nxt1-lineHeight-relaxed);
      }

      /* ============================================
         STORE CONTAINER
         ============================================ */

      .xp-store {
        display: grid;
        gap: var(--nxt1-spacing-5);
      }

      .xp-store__top-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: var(--nxt1-spacing-3);
        flex-wrap: wrap;
      }

      .xp-store__title {
        margin: 0;
        color: var(--nxt1-color-text-primary);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-lg);
        font-weight: var(--nxt1-fontWeight-semibold);
      }

      .xp-store__pill {
        display: inline-flex;
        align-items: center;
        gap: var(--nxt1-spacing-1_5);
        padding: var(--nxt1-spacing-1_5) var(--nxt1-spacing-3);
        border-radius: var(--nxt1-borderRadius-full);
        background: var(--nxt1-color-alpha-primary20);
        color: var(--nxt1-color-primary);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-2xs);
        font-weight: var(--nxt1-fontWeight-semibold);
        letter-spacing: var(--nxt1-letterSpacing-wide);
        text-transform: uppercase;
      }

      .xp-store__pill-dot {
        width: 6px;
        height: 6px;
        border-radius: var(--nxt1-borderRadius-full);
        background: var(--nxt1-color-feedback-success);
        animation: xp-pulse-dot 2s ease-in-out infinite;
      }

      @keyframes xp-pulse-dot {
        0%,
        100% {
          opacity: 1;
          transform: scale(1);
        }
        50% {
          opacity: 0.5;
          transform: scale(0.8);
        }
      }

      /* ============================================
         GRID — 1-col (mobile) → 2-col → 4-col
         ============================================ */

      .xp-store__grid {
        display: grid;
        grid-template-columns: 1fr;
        gap: var(--nxt1-spacing-4);
      }

      /* ============================================
         REWARD CARD
         ============================================ */

      .reward-card {
        display: flex;
        flex-direction: column;
        border: 1px solid var(--nxt1-color-border-subtle);
        border-radius: var(--nxt1-borderRadius-xl);
        background: var(--nxt1-color-surface-100);
        overflow: hidden;
        cursor: pointer;
        transition:
          transform 180ms ease,
          border-color 200ms ease,
          box-shadow 200ms ease;
      }

      .reward-card:hover {
        transform: translateY(-3px);
        border-color: var(--nxt1-color-alpha-primary40);
        box-shadow:
          0 8px 24px var(--nxt1-color-alpha-primary10),
          0 0 0 1px var(--nxt1-color-alpha-primary15);
      }

      .reward-card:focus-visible {
        outline: 2px solid var(--nxt1-color-primary);
        outline-offset: 2px;
      }

      .reward-card:active {
        transform: translateY(0) scale(0.98);
      }

      .reward-card--selected {
        border-color: var(--nxt1-color-alpha-primary50);
        box-shadow:
          0 0 0 1px var(--nxt1-color-alpha-primary25),
          0 8px 28px var(--nxt1-color-alpha-primary15);
      }

      .reward-card--selected:hover {
        transform: none;
      }

      /* ============================================
         SQUARE PLACEHOLDER IMAGE
         ============================================ */

      .reward-card__image {
        position: relative;
        /* Square: width = 100%, height = width via aspect-ratio */
        aspect-ratio: 1 / 1;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: var(--nxt1-spacing-2);
        background: linear-gradient(
          145deg,
          var(--nxt1-color-alpha-primary8),
          var(--nxt1-color-surface-200) 55%,
          var(--nxt1-color-alpha-primary5)
        );
        overflow: hidden;
      }

      /* Premium shimmer sweep */
      .reward-card__shimmer {
        position: absolute;
        inset: 0;
        background: linear-gradient(
          105deg,
          transparent 38%,
          var(--nxt1-color-alpha-primary10) 50%,
          transparent 62%
        );
        background-size: 250% 100%;
        animation: xp-shimmer 3.5s ease-in-out infinite;
        pointer-events: none;
      }

      @keyframes xp-shimmer {
        0% {
          background-position: 250% 0;
        }
        100% {
          background-position: -250% 0;
        }
      }

      .reward-card__icon-wrap {
        position: relative;
        z-index: 1;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 52px;
        height: 52px;
        border-radius: var(--nxt1-borderRadius-xl);
        background: var(--nxt1-color-alpha-primary12);
        border: 1px solid var(--nxt1-color-alpha-primary25);
        color: var(--nxt1-color-primary);
        transition:
          transform 200ms ease,
          background 200ms ease;
      }

      .reward-card:hover .reward-card__icon-wrap {
        transform: scale(1.1);
        background: var(--nxt1-color-alpha-primary20);
      }

      .reward-card--selected .reward-card__icon-wrap {
        background: var(--nxt1-color-alpha-primary25);
        transform: scale(1.06);
      }

      .reward-card__icon {
        width: 26px;
        height: 26px;
      }

      .reward-card__image-label {
        position: relative;
        z-index: 1;
        color: var(--nxt1-color-text-tertiary);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-2xs);
        font-weight: var(--nxt1-fontWeight-semibold);
        letter-spacing: var(--nxt1-letterSpacing-wide);
        text-transform: uppercase;
        opacity: 0.7;
      }

      /* ============================================
         CARD BODY
         ============================================ */

      .reward-card__body {
        display: grid;
        gap: var(--nxt1-spacing-1_5);
        padding: var(--nxt1-spacing-3_5) var(--nxt1-spacing-4);
      }

      .reward-card__xp-badge {
        width: fit-content;
        display: inline-flex;
        align-items: center;
        padding: var(--nxt1-spacing-0_5) var(--nxt1-spacing-2);
        border-radius: var(--nxt1-borderRadius-full);
        background: var(--nxt1-color-alpha-primary12);
        border: 1px solid var(--nxt1-color-alpha-primary20);
        color: var(--nxt1-color-primary);
        font-family: var(--nxt1-fontFamily-display);
        font-size: var(--nxt1-fontSize-2xs);
        font-weight: var(--nxt1-fontWeight-bold);
        letter-spacing: var(--nxt1-letterSpacing-wide);
        text-transform: uppercase;
      }

      .reward-card__name {
        margin: 0;
        color: var(--nxt1-color-text-primary);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-sm);
        font-weight: var(--nxt1-fontWeight-bold);
        line-height: var(--nxt1-lineHeight-snug);
      }

      .reward-card__subtitle {
        margin: 0;
        color: var(--nxt1-color-text-secondary);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-xs);
        font-weight: var(--nxt1-fontWeight-medium);
        line-height: var(--nxt1-lineHeight-normal);
      }

      /* ============================================
         EXPAND ROW
         ============================================ */

      .reward-card__expand-row {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: var(--nxt1-spacing-1);
        padding: var(--nxt1-spacing-2) var(--nxt1-spacing-4) var(--nxt1-spacing-3);
        border-top: 1px solid var(--nxt1-color-border-subtle);
      }

      .reward-card__expand-hint {
        color: var(--nxt1-color-primary);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-2xs);
        font-weight: var(--nxt1-fontWeight-semibold);
        letter-spacing: var(--nxt1-letterSpacing-wide);
        text-transform: uppercase;
      }

      .reward-card__chevron {
        width: 14px;
        height: 14px;
        color: var(--nxt1-color-primary);
        transition: transform 200ms ease;
        flex-shrink: 0;
      }

      .reward-card__chevron--open {
        transform: rotate(180deg);
      }

      /* ============================================
         INLINE DETAIL PANEL
         ============================================ */

      .reward-card__detail {
        padding: 0 var(--nxt1-spacing-4) var(--nxt1-spacing-4);
        animation: xp-expand 220ms ease-out;
      }

      @keyframes xp-expand {
        from {
          opacity: 0;
          transform: translateY(-6px);
        }
        to {
          opacity: 1;
          transform: translateY(0);
        }
      }

      .reward-card__description {
        margin: 0 0 var(--nxt1-spacing-3) 0;
        color: var(--nxt1-color-text-primary);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-xs);
        font-weight: var(--nxt1-fontWeight-medium);
        line-height: var(--nxt1-lineHeight-relaxed);
      }

      .reward-card__meta {
        display: flex;
        align-items: center;
        gap: var(--nxt1-spacing-2);
        flex-wrap: wrap;
      }

      .reward-card__cost {
        color: var(--nxt1-color-primary);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-2xs);
        font-weight: var(--nxt1-fontWeight-semibold);
      }

      .reward-card__tag {
        display: inline-flex;
        align-items: center;
        padding: var(--nxt1-spacing-0_5) var(--nxt1-spacing-2);
        border-radius: var(--nxt1-borderRadius-full);
        background: var(--nxt1-color-feedback-successBg, var(--nxt1-color-alpha-primary8));
        color: var(--nxt1-color-feedback-success);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-2xs);
        font-weight: var(--nxt1-fontWeight-semibold);
        letter-spacing: var(--nxt1-letterSpacing-wide);
        text-transform: uppercase;
      }

      /* ============================================
         CTA TEXT
         ============================================ */

      .xp-economy__cta {
        margin: 0;
        text-align: center;
        color: var(--nxt1-color-text-tertiary);
        font-family: var(--nxt1-fontFamily-brand);
        font-size: var(--nxt1-fontSize-xs);
        font-weight: var(--nxt1-fontWeight-medium);
        line-height: var(--nxt1-lineHeight-relaxed);
      }

      /* ============================================
         RESPONSIVE BREAKPOINTS
         ============================================ */

      /* Tablet — 2 columns */
      @media (min-width: 640px) {
        .xp-store__grid {
          grid-template-columns: repeat(2, minmax(0, 1fr));
        }
      }

      /* Desktop — 4 columns, single row */
      @media (min-width: 1024px) {
        .xp-economy__title {
          font-size: var(--nxt1-fontSize-3xl);
        }

        .xp-economy__subtitle {
          font-size: var(--nxt1-fontSize-base);
        }

        .xp-store__grid {
          grid-template-columns: repeat(4, minmax(0, 1fr));
        }

        .reward-card__name {
          font-size: var(--nxt1-fontSize-base);
        }
      }

      /* ============================================
         REDUCED MOTION
         ============================================ */

      @media (prefers-reduced-motion: reduce) {
        .reward-card {
          transition: none;
        }

        .reward-card:hover,
        .reward-card:active {
          transform: none;
        }

        .reward-card__icon-wrap {
          transition: none;
        }

        .reward-card__chevron {
          transition: none;
        }

        .reward-card__shimmer {
          animation: none;
        }

        .xp-store__pill-dot {
          animation: none;
        }

        .reward-card__detail {
          animation: none;
        }
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NxtXpEconomyRewardsComponent {
  protected readonly rewardTiers = REWARD_TIERS;

  private readonly instanceId = ++xpEconomyInstanceCounter;
  private readonly _selectedId = signal<string | null>(null);

  /** Deterministic SSR-safe IDs. */
  protected readonly titleId = computed(() => `xp-economy-title-${this.instanceId}`);
  protected readonly storeTitleId = computed(() => `xp-economy-store-${this.instanceId}`);

  /** Toggle selection — tap again to collapse. */
  protected selectReward(id: string): void {
    this._selectedId.update((current) => (current === id ? null : id));
  }

  /** Check if a tier is the currently selected one. */
  protected isSelected(id: string): boolean {
    return this._selectedId() === id;
  }
}
